Repository basedosdados/sdk, pull requests merged in 2021-06, with the labels that each got.

#475 [dados] br_ibge_inflacao
  bases/br_ibge_inflacao/README.md
  bases/br_ibge_inflacao/code/ipca15.R
  bases/br_ibge_inflacao/dataset_config.yaml
  bases/br_ibge_inflacao/ipca15/publish.sql
  bases/br_ibge_inflacao/ipca15/schema-prod.json
  bases/br_ibge_inflacao/ipca15/schema-staging.json
  bases/br_ibge_inflacao/ipca15/table_config.yaml
  bases/br_ibge_inflacao/ipca15/table_description.txt
Labels: data

#446 [infra] r-package - protótipo da função bdplyr() para tornar compatíveis as bases do BD ao pacote {dplyr}
  r-package/.gitignore
  r-package/DESCRIPTION
  r-package/NAMESPACE
  r-package/R/bdplyr.R
  r-package/man/bd_collect.Rd
  r-package/man/bd_write.Rd
  r-package/man/bdplyr.Rd
  r-package/tests/testthat/test-bdplyr.R
Labels: R, enhancement

#458 [dados]br_bd_diretorios_brasil instituicao_ensino_superior
  bases/br_bd_diretorios_brasil/code/diretorios_cursos.ipynb
  bases/br_bd_diretorios_brasil/code/diretorios_ies.R
  bases/br_bd_diretorios_brasil/code/diretorios_pais.ipynb
  bases/br_bd_diretorios_brasil/curso_superior/publish.sql
  bases/br_bd_diretorios_brasil/curso_superior/schema-prod.json
  bases/br_bd_diretorios_brasil/curso_superior/schema-staging.json
  bases/br_bd_diretorios_brasil/curso_superior/table_config.yaml
  bases/br_bd_diretorios_brasil/curso_superior/table_description.txt
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/schema-prod.json
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/schema-staging.json
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/table_config.yaml
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/table_description.txt
  bases/br_bd_diretorios_brasil/pais/publish.sql
  bases/br_bd_diretorios_brasil/pais/schema-prod.json
  bases/br_bd_diretorios_brasil/pais/schema-staging.json
  bases/br_bd_diretorios_brasil/pais/table_config.yaml
  bases/br_bd_diretorios_brasil/pais/table_description.txt
Labels: data

#478 [dados] br_bd_diretorios_brasil.municipio
  bases/br_bd_diretorios_brasil/municipio/schema-staging.json
  bases/br_bd_diretorios_brasil/municipio/table_config.yaml
Labels: data

#490 [dados] Adiciona população de município, UF, Brasil.
  bases/br_ibge_populacao/brasil/publish.sql
  bases/br_ibge_populacao/brasil/schema-prod.json
  bases/br_ibge_populacao/brasil/schema-staging.json
  bases/br_ibge_populacao/brasil/table_config.yaml
  bases/br_ibge_populacao/brasil/table_description.txt
  bases/br_ibge_populacao/municipio/publish.sql
  bases/br_ibge_populacao/municipio/schema-prod.json
  bases/br_ibge_populacao/municipio/schema-staging.json
  bases/br_ibge_populacao/municipio/table_config.yaml
  bases/br_ibge_populacao/municipio/table_description.txt
  bases/br_ibge_populacao/municipios/schema-prod.json
  bases/br_ibge_populacao/uf/publish.sql
  bases/br_ibge_populacao/uf/schema-prod.json
  bases/br_ibge_populacao/uf/schema-staging.json
  bases/br_ibge_populacao/uf/table_config.yaml
  bases/br_ibge_populacao/uf/table_description.txt
Labels: data

#489 [dados] Atualiza diretório de municípios com DDD e comarcas do Ipea.
  bases/br_bd_diretorios_brasil/municipio/publish.sql
  bases/br_bd_diretorios_brasil/municipio/schema-prod.json
  bases/br_bd_diretorios_brasil/municipio/schema-staging.json
  bases/br_bd_diretorios_brasil/municipio/table_config.yaml
  bases/br_bd_diretorios_brasil/municipio/table_description.txt
Labels: data

#485 [dados] br_inep_censo_escolar.dicionario
  bases/br_inep_censo_escolar/dicionario/publish.sql
  bases/br_inep_censo_escolar/dicionario/schema-prod.json
  bases/br_inep_censo_escolar/dicionario/schema-staging.json
  bases/br_inep_censo_escolar/dicionario/table_config.yaml
  bases/br_inep_censo_escolar/dicionario/table_description.txt
Labels: data

#483 [dados] br_rj_rio_de_janeiro_ipp_ips
  bases/br_rj_rio_de_janeiro_ipp_ips/README.md
  bases/br_rj_rio_de_janeiro_ipp_ips/code/ips_rj.R
  bases/br_rj_rio_de_janeiro_ipp_ips/dataset_config.yaml
  bases/br_rj_rio_de_janeiro_ipp_ips/dimensoes_componentes/publish.sql
  bases/br_rj_rio_de_janeiro_ipp_ips/dimensoes_componentes/schema-prod.json
  bases/br_rj_rio_de_janeiro_ipp_ips/dimensoes_componentes/schema-staging.json
  bases/br_rj_rio_de_janeiro_ipp_ips/dimensoes_componentes/table_config.yaml
  bases/br_rj_rio_de_janeiro_ipp_ips/dimensoes_componentes/table_description.txt
  bases/br_rj_rio_de_janeiro_ipp_ips/indicadores/publish.sql
  bases/br_rj_rio_de_janeiro_ipp_ips/indicadores/schema-prod.json
  bases/br_rj_rio_de_janeiro_ipp_ips/indicadores/schema-staging.json
  bases/br_rj_rio_de_janeiro_ipp_ips/indicadores/table_config.yaml
  bases/br_rj_rio_de_janeiro_ipp_ips/indicadores/table_description.txt
Labels: data

#495 [dados] br_sp_alesp | update data
  bases/br_sp_alesp/assessores_lideranca/table_config.yaml
  bases/br_sp_alesp/assessores_parlamentares/table_config.yaml
  bases/br_sp_alesp/deputados/table_config.yaml
  bases/br_sp_alesp/despesas_gabinete/table_config.yaml
  bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
Labels: data

#494 [docs] Atualiza colaboração de dados
  docs/access_data_bq.md
  docs/colab_data.md
  docs/colab_infrastructure.md
  docs/style_data.md
  docs/style_naming_columns.md
  docs/style_naming_datasets_tables.md
  mkdocs.yml
Labels: docs

#445 [infra] add data checks
  .github/workflows/data-check.yml
  .github/workflows/data-check/action.yml
  .github/workflows/data-check/bd_credential.py
  .github/workflows/data-check/checks.yaml
  .github/workflows/data-check/conftest.py
  .github/workflows/data-check/test_data.py
  README.md
  bases/br_sp_gov_ssp/produtividade_policial/table_config.yaml
  docs/colab_checks.md
  mkdocs.yml
Labels: data-check-trigger, docs, enhancement, infra

#488 [infra] add link checker
  .github/workflows/check-links.yml
  .github/workflows/check-links/Dockerfile
  .github/workflows/check-links/action.yml
  .github/workflows/check-links/entrypoint.sh
  .github/workflows/check-links/to_markdown.py
Labels: enhancement, infra

#499 [dados] mundo_transrespect_transphobia
  bases/mundo_transrespect_transphobia/README.md
  bases/mundo_transrespect_transphobia/causa_obito/publish.sql
  bases/mundo_transrespect_transphobia/causa_obito/schema-prod.json
  bases/mundo_transrespect_transphobia/causa_obito/schema-staging.json
  bases/mundo_transrespect_transphobia/causa_obito/table_config.yaml
  bases/mundo_transrespect_transphobia/causa_obito/table_description.txt
  bases/mundo_transrespect_transphobia/code/transfobia.R
  bases/mundo_transrespect_transphobia/dataset_config.yaml
  bases/mundo_transrespect_transphobia/local/publish.sql
  bases/mundo_transrespect_transphobia/local/schema-prod.json
  bases/mundo_transrespect_transphobia/local/schema-staging.json
  bases/mundo_transrespect_transphobia/local/table_config.yaml
  bases/mundo_transrespect_transphobia/local/table_description.txt
  bases/mundo_transrespect_transphobia/pais/publish.sql
  bases/mundo_transrespect_transphobia/pais/schema-prod.json
  bases/mundo_transrespect_transphobia/pais/schema-staging.json
  bases/mundo_transrespect_transphobia/pais/table_config.yaml
  bases/mundo_transrespect_transphobia/pais/table_description.txt
Labels: data, data-check-trigger

#492 [dados] eu_fra_lgbt
  bases/eu_fra_lgbt/README.md
  bases/eu_fra_lgbt/code/pride.R
  bases/eu_fra_lgbt/consciencia_direitos/publish.sql
  bases/eu_fra_lgbt/consciencia_direitos/schema-prod.json
  bases/eu_fra_lgbt/consciencia_direitos/schema-staging.json
  bases/eu_fra_lgbt/consciencia_direitos/table_config.yaml
  bases/eu_fra_lgbt/consciencia_direitos/table_description.txt
  bases/eu_fra_lgbt/cotidiano/publish.sql
  bases/eu_fra_lgbt/cotidiano/schema-prod.json
  bases/eu_fra_lgbt/cotidiano/schema-staging.json
  bases/eu_fra_lgbt/cotidiano/table_config.yaml
  bases/eu_fra_lgbt/cotidiano/table_description.txt
  bases/eu_fra_lgbt/dataset_config.yaml
  bases/eu_fra_lgbt/discriminacao/publish.sql
  bases/eu_fra_lgbt/discriminacao/schema-prod.json
  bases/eu_fra_lgbt/discriminacao/schema-staging.json
  bases/eu_fra_lgbt/discriminacao/table_config.yaml
  bases/eu_fra_lgbt/discriminacao/table_description.txt
  bases/eu_fra_lgbt/especifico_transgenero/publish.sql
  bases/eu_fra_lgbt/especifico_transgenero/schema-prod.json
  bases/eu_fra_lgbt/especifico_transgenero/schema-staging.json
  bases/eu_fra_lgbt/especifico_transgenero/table_config.yaml
  bases/eu_fra_lgbt/especifico_transgenero/table_description.txt
  bases/eu_fra_lgbt/violencia_abuso/publish.sql
  bases/eu_fra_lgbt/violencia_abuso/schema-prod.json
  bases/eu_fra_lgbt/violencia_abuso/schema-staging.json
  bases/eu_fra_lgbt/violencia_abuso/table_config.yaml
  bases/eu_fra_lgbt/violencia_abuso/table_description.txt
Labels: data, data-check-trigger

#508 [dados] br_ggb_relatorio_lgbtqi
  bases/br_ggb_relatorio_lgbtqi/README.md
  bases/br_ggb_relatorio_lgbtqi/brasil/publish.sql
  bases/br_ggb_relatorio_lgbtqi/brasil/schema-prod.json
  bases/br_ggb_relatorio_lgbtqi/brasil/schema-staging.json
  bases/br_ggb_relatorio_lgbtqi/brasil/table_config.yaml
  bases/br_ggb_relatorio_lgbtqi/brasil/table_description.txt
  bases/br_ggb_relatorio_lgbtqi/causa_obito/publish.sql
  bases/br_ggb_relatorio_lgbtqi/causa_obito/schema-prod.json
  bases/br_ggb_relatorio_lgbtqi/causa_obito/schema-staging.json
  bases/br_ggb_relatorio_lgbtqi/causa_obito/table_config.yaml
  bases/br_ggb_relatorio_lgbtqi/causa_obito/table_description.txt
  bases/br_ggb_relatorio_lgbtqi/dataset_config.yaml
  bases/br_ggb_relatorio_lgbtqi/grupo_lgbtqia/publish.sql
  bases/br_ggb_relatorio_lgbtqi/grupo_lgbtqia/schema-prod.json
  bases/br_ggb_relatorio_lgbtqi/grupo_lgbtqia/schema-staging.json
  bases/br_ggb_relatorio_lgbtqi/grupo_lgbtqia/table_config.yaml
  bases/br_ggb_relatorio_lgbtqi/grupo_lgbtqia/table_description.txt
  bases/br_ggb_relatorio_lgbtqi/local/publish.sql
  bases/br_ggb_relatorio_lgbtqi/local/schema-prod.json
  bases/br_ggb_relatorio_lgbtqi/local/schema-staging.json
  bases/br_ggb_relatorio_lgbtqi/local/table_config.yaml
  bases/br_ggb_relatorio_lgbtqi/local/table_description.txt
  bases/br_ggb_relatorio_lgbtqi/raca_cor/publish.sql
  bases/br_ggb_relatorio_lgbtqi/raca_cor/schema-prod.json
  bases/br_ggb_relatorio_lgbtqi/raca_cor/schema-staging.json
  bases/br_ggb_relatorio_lgbtqi/raca_cor/table_config.yaml
  bases/br_ggb_relatorio_lgbtqi/raca_cor/table_description.txt
Labels: data, data-check-trigger

#517 [infra] fix primary key test logic
  .github/workflows/data-check/checks.yaml
  .github/workflows/data-check/test_data.py
Labels: infra

#518 [dados] br_me_pensionistas
  bases/br_me_pensionistas/README.md
  bases/br_me_pensionistas/code/build.do
  bases/br_me_pensionistas/dataset_config.yaml
  bases/br_me_pensionistas/microdados/publish.sql
  bases/br_me_pensionistas/microdados/schema-prod.json
  bases/br_me_pensionistas/microdados/schema-staging.json
  bases/br_me_pensionistas/microdados/table_config.yaml
  bases/br_me_pensionistas/microdados/table_description.txt
Labels: data, data-check-trigger
