Repository basedosdados/sdk, pull requests merged in 2021-02, with the labels that each got.

#227 Add metadata functions to download.py module
  basedosdados/__init__.py
  basedosdados/download.py
  pyproject.toml
  tests/test_download.py
Labels: enhancement

#252 add a tutorial notebook for beginners users
  README.md
  examples/bd_for_beginners.ipynb
Labels: docs

#248 Fix docs.
  README.md
  docs/colab_data.md
  docs/video_script.md
Labels: bug, docs

#263 add new metadata fields to table_config template
  basedosdados/configs/templates/table/table_config.yaml
  basedosdados/table.py
Labels: enhancement

#268 fix tab bug in table create and remove print from copy and delete blobs
  basedosdados/storage.py
  basedosdados/table.py
Labels: bug

#269 [infra] table approve
  .github/workflows/table-approve.yml
  .github/workflows/table-approve/Dockerfile
  .github/workflows/table-approve/action.yml
  .github/workflows/table-approve/main.py
Labels: enhancement

#241 [dados] br_tse_eleicoes.despesas_candidato
  bases/br_tse_eleicoes/despesas_candidato/publish.sql
  bases/br_tse_eleicoes/despesas_candidato/schema-prod.json
  bases/br_tse_eleicoes/despesas_candidato/schema-staging.json
  bases/br_tse_eleicoes/despesas_candidato/table_config.yaml
  bases/br_tse_eleicoes/despesas_candidato/table_description.txt
  bases/br_tse_eleicoes/receita_candidato/schema-prod.json
  bases/br_tse_eleicoes/receita_candidato/schema-staging.json
  bases/br_tse_eleicoes/receitas_candidato/publish.sql
  bases/br_tse_eleicoes/receitas_candidato/schema-prod.json
  bases/br_tse_eleicoes/receitas_candidato/schema-staging.json
  bases/br_tse_eleicoes/receitas_candidato/table_config.yaml
  bases/br_tse_eleicoes/receitas_candidato/table_description.txt
Labels: data

#275 [dados] Atualiza bens_candidato.
  bases/br_tse_eleicoes/bens_candidato/publish.sql
  bases/br_tse_eleicoes/bens_candidato/schema-prod.json
  bases/br_tse_eleicoes/bens_candidato/schema-staging.json
  bases/br_tse_eleicoes/bens_candidato/table_config.yaml
  bases/br_tse_eleicoes/bens_candidato/table_description.txt
  bases/br_tse_eleicoes/code/sub/agregacao.do
  bases/br_tse_eleicoes/code/sub/candidatos.do
  bases/br_tse_eleicoes/code/sub/coligacoes.do
  bases/br_tse_eleicoes/code/sub/cria_id_candidato.do
  bases/br_tse_eleicoes/code/sub/detalhes_votacao_municipio_zona.do
  bases/br_tse_eleicoes/code/sub/detalhes_votacao_secao.do
  bases/br_tse_eleicoes/code/sub/download_arquivos.py
  bases/br_tse_eleicoes/code/sub/filiacao_partidaria.do
  bases/br_tse_eleicoes/code/sub/normalizacao_particao.do
  bases/br_tse_eleicoes/code/sub/perfil_eleitorado.do
  bases/br_tse_eleicoes/code/sub/prestacao_contas.do
  bases/br_tse_eleicoes/code/sub/resultados_municipio_zona.do
  bases/br_tse_eleicoes/code/sub/resultados_secao.do
  bases/br_tse_eleicoes/code/sub/unzip_files.sh
  bases/br_tse_eleicoes/code/sub/vagas.do
Labels: data

#279 Atualiza configs para versao 1.4.
  bases/br_tse_eleicoes/despesas_candidato/table_config.yaml
  bases/br_tse_eleicoes/receitas_candidato/table_config.yaml
Labels: data

#280 [infra]CLI table create fix
  basedosdados/cli.py
Labels: bug

#282 [infra] Corrige issue #267:
  basedosdados/storage.py
  basedosdados/table.py
  pyproject.toml
Labels: bug, infra

#278 [docs] Closes #254 e conserta lista no colab_data.
  docs/colab_data.md
  docs/index.md
Labels: docs

#286 [infra] Table().publish() force encoding
  basedosdados/base.py
  basedosdados/dataset.py
  basedosdados/table.py
  pyproject.toml
Labels: bug, infra

#284 [infra]Minor fix no table init do CLI
  basedosdados/cli.py
Labels: infra

#285 [infra]Table_approve
  .github/TABLE_APPROVE.md
  .github/workflows/add-to-cloudtask.yml
  .github/workflows/table-approve.yml
  .github/workflows/table-approve/main.py
Labels: enhancement, infra

#229 [dados] br_ibge_ppm
  bases/br_ibge_ppm/README.md
  bases/br_ibge_ppm/code/.Rhistory
  bases/br_ibge_ppm/code/pesquisa_pecuaria_municipal.R
  bases/br_ibge_ppm/dataset_config.yaml
  bases/br_ibge_ppm/efetivo_rebanhos/publish.sql
  bases/br_ibge_ppm/efetivo_rebanhos/schema-prod.json
  bases/br_ibge_ppm/efetivo_rebanhos/schema-staging.json
  bases/br_ibge_ppm/efetivo_rebanhos/table_config.yaml
  bases/br_ibge_ppm/efetivo_rebanhos/table_description.txt
  bases/br_ibge_ppm/producao_aquicultura/publish.sql
  bases/br_ibge_ppm/producao_aquicultura/schema-prod.json
  bases/br_ibge_ppm/producao_aquicultura/schema-staging.json
  bases/br_ibge_ppm/producao_aquicultura/table_config.yaml
  bases/br_ibge_ppm/producao_aquicultura/table_description.txt
  bases/br_ibge_ppm/producao_origem_animal/publish.sql
  bases/br_ibge_ppm/producao_origem_animal/schema-prod.json
  bases/br_ibge_ppm/producao_origem_animal/schema-staging.json
  bases/br_ibge_ppm/producao_origem_animal/table_config.yaml
  bases/br_ibge_ppm/producao_origem_animal/table_description.txt
  bases/br_ibge_ppm/producao_pecuaria/publish.sql
  bases/br_ibge_ppm/producao_pecuaria/schema-prod.json
  bases/br_ibge_ppm/producao_pecuaria/schema-staging.json
  bases/br_ibge_ppm/producao_pecuaria/table_config.yaml
  bases/br_ibge_ppm/producao_pecuaria/table_description.txt
Labels: data

#260 [dados] br_anvisa_medicamentos_industrializados
  bases/br_anvisa_medicamentos_industrializados/README.md
  bases/br_anvisa_medicamentos_industrializados/code/build.do
  bases/br_anvisa_medicamentos_industrializados/code/clean_string.do
  bases/br_anvisa_medicamentos_industrializados/code/download_files.py
  bases/br_anvisa_medicamentos_industrializados/dataset_config.yaml
  bases/br_anvisa_medicamentos_industrializados/dictionaries/Documentacao_e_Dicionario_de_Dados_SNGPC_Industrializados.pdf
  bases/br_anvisa_medicamentos_industrializados/microdados/publish.sql
  bases/br_anvisa_medicamentos_industrializados/microdados/schema-prod.json
  bases/br_anvisa_medicamentos_industrializados/microdados/schema-staging.json
  bases/br_anvisa_medicamentos_industrializados/microdados/table_config.yaml
  bases/br_anvisa_medicamentos_industrializados/microdados/table_description.txt
Labels: data

#301 [dados] br_ibge_ppm
  bases/br_ibge_ppm/producao_aquicultura/publish.sql
  bases/br_ibge_ppm/producao_aquicultura/schema-prod.json
  bases/br_ibge_ppm/producao_aquicultura/schema-staging.json
  bases/br_ibge_ppm/producao_aquicultura/table_config.yaml
  bases/br_ibge_ppm/producao_aquicultura/table_description.txt
Labels: data

#303 [dados] br_imprensa_nacional_dou
  bases/br_imprensa_nacional_dou/README.md
  bases/br_imprensa_nacional_dou/dataset_config.yaml
  bases/br_imprensa_nacional_dou/secao_1/publish.sql
  bases/br_imprensa_nacional_dou/secao_1/schema-prod.json
  bases/br_imprensa_nacional_dou/secao_1/table_config.yaml
  bases/br_imprensa_nacional_dou/secao_1/table_description.txt
  bases/br_imprensa_nacional_dou/secao_2/publish.sql
  bases/br_imprensa_nacional_dou/secao_2/schema-prod.json
  bases/br_imprensa_nacional_dou/secao_2/table_config.yaml
  bases/br_imprensa_nacional_dou/secao_2/table_description.txt
  bases/br_imprensa_nacional_dou/secao_3/publish.sql
  bases/br_imprensa_nacional_dou/secao_3/schema-prod.json
  bases/br_imprensa_nacional_dou/secao_3/table_config.yaml
  bases/br_imprensa_nacional_dou/secao_3/table_description.txt
Labels: data

#306 [dados] br_bd_diretorios_brasil
  bases/br_bd_diretorios_brasil/setor_censitario/publish.sql
  bases/br_bd_diretorios_brasil/setor_censitario/schema-prod.json
  bases/br_bd_diretorios_brasil/setor_censitario/schema-staging.json
  bases/br_bd_diretorios_brasil/setor_censitario/table_config.yaml
  bases/br_bd_diretorios_brasil/setor_censitario/table_description.txt
Labels: data
