Repository basedosdados/sdk, pull requests merged in 2021-09, with the labels that each got.

#741 [dados] Revisão br_anp_precos_combustiveis
  .github/workflows/data-check/conftest.py
  bases/br_anp_precos_combustiveis/code/[dados]_br_anp_preco_combustiveis.ipynb
  bases/br_anp_precos_combustiveis/microdados/publish.sql
  bases/br_anp_precos_combustiveis/microdados/schema-staging.json
  bases/br_anp_precos_combustiveis/microdados/table_config.yaml
  bases/br_anp_precos_combustiveis/microdados/table_description.txt
Labels: data, data-check-trigger

#752 [infra] corrige o `data-check` em pull requests
  .github/workflows/data-check.yml
  .github/workflows/data-check/checks.yaml
  .github/workflows/data-check/conftest.py
  .github/workflows/data-check/test_data.py
  .github/workflows/table-approve.yml
  bases/br_sp_alesp/deputado/table_config.yaml
Labels: data-check-trigger

#757 [infra] alteração no nome do projeto
  .github/workflows/data-check/checks.yaml
  .github/workflows/data-check/conftest.py
  bases/br_sp_alesp/deputado/table_config.yaml
Labels: data-check-trigger

#759 [dados-bot] br_ms_vacinacao_covid19 (2021-09-02)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#751 [dados-atualizacao] br_ibge_inflacao
  bases/br_ibge_inflacao/code/ipca15.R
  bases/br_ibge_inflacao/dataset_config.yaml
  bases/br_ibge_inflacao/ipca15/publish.sql
  bases/br_ibge_inflacao/ipca15/table_config.yaml
  bases/br_ibge_inflacao/ipca15/table_description.txt
Labels: data, data-check-trigger

#750 [dados] br_inmet_bdmep
  bases/br_inmet_bdmep/estacao/table_config.yaml
  bases/br_inmet_bdmep/microdados/schema-staging.json
  bases/br_inmet_bdmep/microdados/table_config.yaml
Labels: data, data-check-trigger

#764 [dados-bot] br_ms_vacinacao_covid19 (2021-09-05)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#769 [dados-bot] br_ms_vacinacao_covid19 (2021-09-07)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#770 [dado] br_ibge_inflacao.ipca
  bases/br_ibge_inflacao/code/ipca.R
  bases/br_ibge_inflacao/ipca/publish.sql
  bases/br_ibge_inflacao/ipca/schema-prod.json
  bases/br_ibge_inflacao/ipca/schema-staging.json
  bases/br_ibge_inflacao/ipca/table_config.yaml
  bases/br_ibge_inflacao/ipca/table_description.txt
Labels: data, data-check-trigger

#768 [dados] br_ms_cnes.estabelecimento
  bases/br_ms_cnes/README.md
  bases/br_ms_cnes/code/Captura br_ms_cnes.py
  bases/br_ms_cnes/code/Converte dbc em csv.R
  bases/br_ms_cnes/code/Tratamento br_ms_cnes_estabelecimento.py
  bases/br_ms_cnes/dataset_config.yaml
  bases/br_ms_cnes/dicionario/publish.sql
  bases/br_ms_cnes/dicionario/schema-prod.json
  bases/br_ms_cnes/dicionario/schema-staging.json
  bases/br_ms_cnes/dicionario/table_config.yaml
  bases/br_ms_cnes/dicionario/table_description.txt
  bases/br_ms_cnes/estabelecimento/publish.sql
  bases/br_ms_cnes/estabelecimento/schema-prod.json
  bases/br_ms_cnes/estabelecimento/schema-staging.json
  bases/br_ms_cnes/estabelecimento/table_config.yaml
  bases/br_ms_cnes/estabelecimento/table_description.txt
Labels: data, data-check-trigger

#758 [docs] Documentação melhorada + ID do novo site
  docs/access_data_bq.md
  docs/access_data_packages.md
  docs/analysis.md
  docs/archive/access_data_local.md
  docs/archive/datathon_2021.md
  docs/archive/odd_2021.md
  docs/archive/support.md
  docs/colab.md
  docs/colab_data.md
  docs/colab_infrastructure.md
  docs/css/custom.css
  docs/images/bdmais_logo_pacotes.png
  docs/images/bdmais_minilogo.png
  docs/images/bdmais_minilogo_vertical.png
  docs/images/bq_query_municipios.png
  docs/images/docs_button.png
  docs/index.md
  docs/reference_api_cli.md
  docs/reference_api_py.md
  docs/style_data.md
  docs/tutorial_cross_tables.md
  mkdocs.yml
Labels: docs, enhancement

#763 [dados] br_mme_energia_eletrica
  bases/br_mme_consumo_energia_eletrica/README.md
  bases/br_mme_consumo_energia_eletrica/code/br_epe.R
  bases/br_mme_consumo_energia_eletrica/code/cleanup1.R
  bases/br_mme_consumo_energia_eletrica/code/cleanup2.R
  bases/br_mme_consumo_energia_eletrica/dataset_config.yaml
  bases/br_mme_consumo_energia_eletrica/uf/publish.sql
  bases/br_mme_consumo_energia_eletrica/uf/schema-prod.json
  bases/br_mme_consumo_energia_eletrica/uf/schema-staging.json
  bases/br_mme_consumo_energia_eletrica/uf/table_config.yaml
  bases/br_mme_consumo_energia_eletrica/uf/table_description.txt
Labels: data, data-check-trigger

#790 br_ibge_inflacao_ipca
  bases/br_ibge_inflacao/code/ipca.py
  bases/br_ibge_inflacao/ipca/schema-staging.json
  bases/br_ibge_inflacao/ipca/table_config.yaml
Labels: data, data-check-trigger

#788 [bases] br_inmet_bdmep
  bases/br_inmet_bdmep/estacao/schema-staging.json
  bases/br_inmet_bdmep/estacao/table_config.yaml
  bases/br_inmet_bdmep/estacao/table_description.txt
  bases/br_inmet_bdmep/microdados/schema-prod.json
  bases/br_inmet_bdmep/microdados/schema-staging.json
  bases/br_inmet_bdmep/microdados/table_config.yaml
  bases/br_inmet_bdmep/microdados/table_description.txt
Labels: data, data-check-trigger

#793 [FEATURE] Adiciona upload em pedaços para o Cloud Storage
  python-package/basedosdados/upload/storage.py
  python-package/basedosdados/upload/table.py
Labels: enhancement, infra, python

#736 [infra] r-package - Mudanças pedidas pelo CRAN para a 0.1.0
  r-package/.Rbuildignore
  r-package/DESCRIPTION
  r-package/NAMESPACE
  r-package/R/bdplyr.R
  r-package/R/zzzz.R
  r-package/man/bd_collect.Rd
  r-package/man/bdplyr.Rd
  r-package/man/dot-onLoad.Rd
  r-package/man/read_table.Rd
  r-package/renv.lock
  r-package/tests/testthat/test-bdplyr.R
Labels: enhancement, R

#806 [dados-bot] br_ms_vacinacao_covid19 (2021-09-22)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#805 [dados] br_ms_sinan.microdados_violencia
  bases/br_ms_sinan/code/download_sinan.R
  bases/br_ms_sinan/code/parse_sinan.R
  bases/br_ms_sinan/dataset_config.yaml
  bases/br_ms_sinan/dicionario/publish.sql
  bases/br_ms_sinan/dicionario/schema-prod.json
  bases/br_ms_sinan/dicionario/schema-staging.json
  bases/br_ms_sinan/dicionario/table_config.yaml
  bases/br_ms_sinan/dicionario/table_description.txt
  bases/br_ms_sinan/microdados_violencia/publish.sql
  bases/br_ms_sinan/microdados_violencia/schema-prod.json
  bases/br_ms_sinan/microdados_violencia/schema-staging.json
  bases/br_ms_sinan/microdados_violencia/table_config.yaml
  bases/br_ms_sinan/microdados_violencia/table_description.txt
Labels: data, data-check-trigger

#815 [dados-bot] br_ms_vacinacao_covid19 (2021-09-27)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#818 [dados-atualizacao] br_anatel_banda_larga_fixa
  bases/br_anatel_banda_larga_fixa/microdados/publish.sql
  bases/br_anatel_banda_larga_fixa/microdados/table_config.yaml
  bases/br_anatel_banda_larga_fixa/microdados/table_description.txt
  bases/br_anatel_banda_larga_fixa/municipio/publish.sql
  bases/br_anatel_banda_larga_fixa/municipio/schema-prod.json
  bases/br_anatel_banda_larga_fixa/municipio/schema-staging.json
  bases/br_anatel_banda_larga_fixa/municipio/table_config.yaml
  bases/br_anatel_banda_larga_fixa/municipio/table_description.txt
Labels: data

#817 [dados-atualizacao] br_anatel_telefonia_movel
  bases/br_anatel_telefonia_movel/ddd/publish.sql
  bases/br_anatel_telefonia_movel/ddd/table_config.yaml
  bases/br_anatel_telefonia_movel/ddd/table_description.txt
  bases/br_anatel_telefonia_movel/modalidade/publish.sql
  bases/br_anatel_telefonia_movel/modalidade/table_config.yaml
  bases/br_anatel_telefonia_movel/modalidade/table_description.txt
  bases/br_anatel_telefonia_movel/municipio/publish.sql
  bases/br_anatel_telefonia_movel/municipio/table_config.yaml
  bases/br_anatel_telefonia_movel/municipio/table_description.txt
  bases/br_anatel_telefonia_movel/tecnologia/publish.sql
  bases/br_anatel_telefonia_movel/tecnologia/table_config.yaml
  bases/br_anatel_telefonia_movel/tecnologia/table_description.txt
Labels: data

#821 [dados-bot] br_ms_vacinacao_covid19 (2021-09-28)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#824 [dados-bot] br_ms_vacinacao_covid19 (2021-09-29)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data
