Repository basedosdados/sdk, pull requests merged in 2021-10, with the labels that each got.

#811 [dados] br_ibge_populacao
  bases/br_ibge_populacao/brasil/schema-staging.json
  bases/br_ibge_populacao/brasil/table_config.yaml
  bases/br_ibge_populacao/brasil/table_description.txt
  bases/br_ibge_populacao/code/build.do
  bases/br_ibge_populacao/dataset_config.yaml
  bases/br_ibge_populacao/municipio/publish.sql
  bases/br_ibge_populacao/municipio/schema-prod.json
  bases/br_ibge_populacao/municipio/schema-staging.json
  bases/br_ibge_populacao/municipio/table_config.yaml
  bases/br_ibge_populacao/municipio/table_description.txt
  bases/br_ibge_populacao/uf/publish.sql
  bases/br_ibge_populacao/uf/schema-prod.json
  bases/br_ibge_populacao/uf/schema-staging.json
  bases/br_ibge_populacao/uf/table_config.yaml
  bases/br_ibge_populacao/uf/table_description.txt
Labels: data, data-check-trigger

#828 [dados-bot] br_ms_vacinacao_covid19 (2021-09-30)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#829 fix(infra): corrige a checagem de chaves primárias
  .github/workflows/data-check/checks.yaml
  .github/workflows/data-check/test_data.py
Labels: data-check-trigger

#832 [dados-bot] br_ms_vacinacao_covid19 (2021-10-03)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#816 [dados-atualizacao] br_mc_auxilio_emergencial
  bases/br_mc_auxilio_emergencial/code/[dados] br_mc_auxilio_emergencial.ipynb
  bases/br_mc_auxilio_emergencial/microdados/table_config.yaml
  bases/br_mc_auxilio_emergencial/microdados/table_description.txt
Labels: data, data-check-trigger

#833 [dados] br_ms_vacinacao_covid19
  bases/br_ms_vacinacao_covid19/dicionario/table_config.yaml
Labels: data

#779 [dados] br_ms_sinasc
  bases/br_ms_sinasc/README.md
  bases/br_ms_sinasc/code/[dados] br_ms_sinasc.ipynb
  bases/br_ms_sinasc/dataset_config.yaml
  bases/br_ms_sinasc/dicionario/publish.sql
  bases/br_ms_sinasc/dicionario/schema-prod.json
  bases/br_ms_sinasc/dicionario/schema-staging.json
  bases/br_ms_sinasc/dicionario/table_config.yaml
  bases/br_ms_sinasc/dicionario/table_description.txt
  bases/br_ms_sinasc/microdados/publish.sql
  bases/br_ms_sinasc/microdados/schema-prod.json
  bases/br_ms_sinasc/microdados/schema-staging.json
  bases/br_ms_sinasc/microdados/table_config.yaml
  bases/br_ms_sinasc/microdados/table_description.txt
Labels: data, data-check-trigger

#825 [dados-revisao] br_anatel_telefonia_movel.municipio
  bases/br_anatel_telefonia_movel/municipio/publish.sql
Labels: bug, data, data-check-trigger

#837 fix(infra): corrige o teste de chaves primárias
  .github/workflows/data-check/checks.yaml
  .github/workflows/data-check/conftest.py
  bases/br_anatel_telefonia_movel/municipio/table_config.yaml
Labels: data-check-trigger

#838 [dados-bot] br_ms_vacinacao_covid19 (2021-10-04)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#801 [dados] br_tse_eleicoes
  bases/br_tse_eleicoes/code/fnc/limpa_partido.do
  bases/br_tse_eleicoes/code/fnc/limpa_resultado.do
  bases/br_tse_eleicoes/code/sub/agregacao.do
  bases/br_tse_eleicoes/code/sub/candidatos.do
  bases/br_tse_eleicoes/code/sub/filiacao_partidaria.do
  bases/br_tse_eleicoes/code/sub/normalizacao_particao.do
  bases/br_tse_eleicoes/code/sub/prestacao_contas.do
  bases/br_tse_eleicoes/code/sub/resultados_municipio_zona.do
  bases/br_tse_eleicoes/despesas_candidato/publish.sql
  bases/br_tse_eleicoes/despesas_candidato/schema-prod.json
  bases/br_tse_eleicoes/despesas_candidato/schema-staging.json
  bases/br_tse_eleicoes/despesas_candidato/table_config.yaml
  bases/br_tse_eleicoes/receitas_candidato/publish.sql
  bases/br_tse_eleicoes/receitas_candidato/schema-prod.json
  bases/br_tse_eleicoes/receitas_candidato/schema-staging.json
  bases/br_tse_eleicoes/receitas_candidato/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato/publish.sql
  bases/br_tse_eleicoes/resultados_candidato/schema-prod.json
  bases/br_tse_eleicoes/resultados_candidato/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_municipio/publish.sql
  bases/br_tse_eleicoes/resultados_candidato_municipio/schema-prod.json
  bases/br_tse_eleicoes/resultados_candidato_municipio/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato_municipio/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/publish.sql
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/schema-prod.json
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_secao/publish.sql
  bases/br_tse_eleicoes/resultados_candidato_secao/schema-prod.json
  bases/br_tse_eleicoes/resultados_candidato_secao/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato_secao/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_municipio/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_secao/table_config.yaml
Labels: data

#913 [dados-bot] br_ms_vacinacao_covid19 (2021-10-28)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#914 [dados] Fix/br geobr mapas columns types
  bases/br_geobr_mapas/setor_censitario_2010/publish.sql
Labels: data
