Repository basedosdados/sdk, pull requests merged in 2021-04, with the labels that each got.

#329 [dados] br_me_comex_stat
  bases/br_me_comex_stat/README.md
  bases/br_me_comex_stat/code/build.do
  bases/br_me_comex_stat/dataset_config.yaml
  bases/br_me_comex_stat/municipio_exportacao/publish.sql
  bases/br_me_comex_stat/municipio_exportacao/schema-prod.json
  bases/br_me_comex_stat/municipio_exportacao/schema-staging.json
  bases/br_me_comex_stat/municipio_exportacao/table_config.yaml
  bases/br_me_comex_stat/municipio_exportacao/table_description.txt
  bases/br_me_comex_stat/municipio_importacao/publish.sql
  bases/br_me_comex_stat/municipio_importacao/schema-prod.json
  bases/br_me_comex_stat/municipio_importacao/schema-staging.json
  bases/br_me_comex_stat/municipio_importacao/table_config.yaml
  bases/br_me_comex_stat/municipio_importacao/table_description.txt
  bases/br_me_comex_stat/ncm_exportacao/publish.sql
  bases/br_me_comex_stat/ncm_exportacao/schema-prod.json
  bases/br_me_comex_stat/ncm_exportacao/schema-staging.json
  bases/br_me_comex_stat/ncm_exportacao/table_config.yaml
  bases/br_me_comex_stat/ncm_exportacao/table_description.txt
  bases/br_me_comex_stat/ncm_importacao/publish.sql
  bases/br_me_comex_stat/ncm_importacao/schema-prod.json
  bases/br_me_comex_stat/ncm_importacao/schema-staging.json
  bases/br_me_comex_stat/ncm_importacao/table_config.yaml
  bases/br_me_comex_stat/ncm_importacao/table_description.txt
Labels: data

#378 [dados] br_ibge_pnadc
  bases/br_ibge_pnadc/README.md
  bases/br_ibge_pnadc/code/microdados.R
  bases/br_ibge_pnadc/dataset_config.yaml
  bases/br_ibge_pnadc/microdados/publish.sql
  bases/br_ibge_pnadc/microdados/schema-prod.json
  bases/br_ibge_pnadc/microdados/schema-staging.json
  bases/br_ibge_pnadc/microdados/table_config.yaml
  bases/br_ibge_pnadc/microdados/table_description.txt
Labels: data

#385 [infra] adds another error possibility and restructure some conditionals
  python-package/basedosdados/table.py
Labels: bug

#380 [dados] br_me_caged
  bases/br_me_caged/README.md
  bases/br_me_caged/code/notebooks/caged.ipynb
  bases/br_me_caged/code/notebooks/paths.py
  bases/br_me_caged/code/scpts/__init__.py
  bases/br_me_caged/code/scpts/caged.py
  bases/br_me_caged/code/scpts/manipulation.py
  bases/br_me_caged/dataset_config.yaml
  bases/br_me_caged/microdados_antigos/publish.sql
  bases/br_me_caged/microdados_antigos/schema-prod.json
  bases/br_me_caged/microdados_antigos/schema-staging.json
  bases/br_me_caged/microdados_antigos/table_config.yaml
  bases/br_me_caged/microdados_antigos/table_description.txt
  bases/br_me_caged/microdados_antigos_ajustes/publish.sql
  bases/br_me_caged/microdados_antigos_ajustes/schema-prod.json
  bases/br_me_caged/microdados_antigos_ajustes/schema-staging.json
  bases/br_me_caged/microdados_antigos_ajustes/table_config.yaml
  bases/br_me_caged/microdados_antigos_ajustes/table_description.txt
Labels: data

#390 [dados] br_tse_eleicoes
  bases/br_tse_eleicoes/code/sub/agregacao.do
  bases/br_tse_eleicoes/code/sub/detalhes_votacao_municipio_zona.do
  bases/br_tse_eleicoes/code/sub/normalizacao_particao.do
  bases/br_tse_eleicoes/code/sub/perfil_eleitorado.do
  bases/br_tse_eleicoes/code/sub/resultados_municipio_zona.do
  bases/br_tse_eleicoes/code/sub/unzip_files.sh
  bases/br_tse_eleicoes/code/sub/vagas.do
  bases/br_tse_eleicoes/resultados_candidato/publish.sql
  bases/br_tse_eleicoes/resultados_candidato/schema-prod.json
  bases/br_tse_eleicoes/resultados_candidato/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato/table_description.txt
Labels: data

#399 [infra] fix table_id order in CLI table append
  python-package/basedosdados/cli.py
Labels: bug, infra

#400 [dados] br_sp_seduc_idesp
  bases/br_sp_seduc/README.md
  bases/br_sp_seduc/code/idesp.R
  bases/br_sp_seduc/dataset_config.yaml
  bases/br_sp_seduc/idesp_escolas/publish.sql
  bases/br_sp_seduc/idesp_escolas/schema-prod.json
  bases/br_sp_seduc/idesp_escolas/schema-staging.json
  bases/br_sp_seduc/idesp_escolas/table_config.yaml
  bases/br_sp_seduc/idesp_escolas/table_description.txt
  bases/br_sp_seduc_idesp/code/idesp.R
  bases/br_sp_seduc_idesp/escola/publish.sql
  bases/br_sp_seduc_idesp/escola/schema-prod.json
  bases/br_sp_seduc_idesp/escola/schema-staging.json
  bases/br_sp_seduc_idesp/escola/table_config.yaml
Labels: data

#405 [dados]br_sp_seduc_fluxo_escolar
  bases/br_sp_seduc_fluxo_escolar/code/.Rhistory
  bases/br_sp_seduc_fluxo_escolar/code/fluxo_escola.R
  bases/br_sp_seduc_fluxo_escolar/code/fluxo_municipio.R
  bases/br_sp_seduc_fluxo_escolar/code/fluxoescolar-escolas.R
  bases/br_sp_seduc_fluxo_escolar/escola/table_config.yaml
  bases/br_sp_seduc_fluxo_escolar/municipio/schema-staging.json
  bases/br_sp_seduc_fluxo_escolar/municipio/table_config.yaml
Labels: data

#408 [dados] br_sp_seduc_idesp
  bases/br_sp_seduc_idesp/code/idesp-diretoria.R
  bases/br_sp_seduc_idesp/code/idesp-escola.R
  bases/br_sp_seduc_idesp/code/idesp-estado.R
  bases/br_sp_seduc_idesp/diretoria/table_config.yaml
  bases/br_sp_seduc_idesp/escola/schema-prod.json
  bases/br_sp_seduc_idesp/escola/table_config.yaml
  bases/br_sp_seduc_idesp/uf/table_config.yaml
Labels: data

#407 [infra] Adiciona .Rhistory ao gitignore
  .gitignore
Labels: infra

#403 [infra] restructures folders in python-package
  .github/workflows/setup-env-Linux/main.py
  .github/workflows/setup-env-Windows/main.py
  python-package/basedosdados/__init__.py
  python-package/basedosdados/cli/cli.py
  python-package/basedosdados/download/download.py
  python-package/basedosdados/upload/base.py
  python-package/basedosdados/upload/dataset.py
  python-package/basedosdados/upload/datatypes.py
  python-package/basedosdados/upload/storage.py
  python-package/basedosdados/upload/table.py
  python-package/basedosdados/validation/exceptions.py
  python-package/tests/test_download.py
  python-package/tests/test_table.py
Labels: infra
