Repository basedosdados/sdk, pull requests merged in 2021-07, with the labels that each got.

#529 [dado] Revisão br_ibge_ppm
  bases/br_ibge_ppm/efetivo_rebanhos/publish.sql
  bases/br_ibge_ppm/efetivo_rebanhos/schema-prod.json
  bases/br_ibge_ppm/efetivo_rebanhos/table_description.txt
  bases/br_ibge_ppm/producao_aquicultura/publish.sql
  bases/br_ibge_ppm/producao_aquicultura/schema-prod.json
  bases/br_ibge_ppm/producao_origem_animal/publish.sql
  bases/br_ibge_ppm/producao_origem_animal/schema-prod.json
  bases/br_ibge_ppm/producao_origem_animal/table_description.txt
  bases/br_ibge_ppm/producao_pecuaria/publish.sql
  bases/br_ibge_ppm/producao_pecuaria/schema-prod.json
  bases/br_ibge_ppm/producao_pecuaria/table_description.txt
Labels: data, data-check-trigger

#528 [dados] Revisão br_ibge_pnadc
  bases/br_ibge_pnadc/microdados/publish.sql
  bases/br_ibge_pnadc/microdados/schema-prod.json
  bases/br_ibge_pnadc/microdados/table_description.txt
Labels: data, data-check-trigger

#549 [dados] Revisão br_me_comex_stat
  bases/br_me_comex_stat/municipio_exportacao/publish.sql
  bases/br_me_comex_stat/municipio_exportacao/schema-prod.json
  bases/br_me_comex_stat/municipio_exportacao/table_description.txt
  bases/br_me_comex_stat/municipio_importacao/publish.sql
  bases/br_me_comex_stat/municipio_importacao/schema-prod.json
  bases/br_me_comex_stat/municipio_importacao/table_description.txt
  bases/br_me_comex_stat/ncm_exportacao/publish.sql
  bases/br_me_comex_stat/ncm_exportacao/schema-prod.json
  bases/br_me_comex_stat/ncm_exportacao/table_description.txt
  bases/br_me_comex_stat/ncm_importacao/publish.sql
  bases/br_me_comex_stat/ncm_importacao/schema-prod.json
  bases/br_me_comex_stat/ncm_importacao/table_description.txt
Labels: data, data-check-trigger

#546 [dados] Revisão br_ibge_amc
  bases/br_ibge_amc/municipio_de_para/publish.sql
  bases/br_ibge_amc/municipio_de_para/schema-prod.json
  bases/br_ibge_amc/municipio_de_para/schema-staging.json
  bases/br_ibge_amc/municipio_de_para/table_config.yaml
  bases/br_ibge_amc/municipio_de_para/table_description.txt
Labels: data, data-check-trigger

#545 [dados] Revisão! CAGED
  bases/br_me_caged/microdados_antigos/publish.sql
  bases/br_me_caged/microdados_antigos/schema-prod.json
  bases/br_me_caged/microdados_antigos_ajustes/publish.sql
  bases/br_me_caged/microdados_antigos_ajustes/schema-prod.json
Labels: data, data-check-trigger

#523 [dados] Revisão br_anvisa_medicamentos_industrializados
  bases/br_anvisa_medicamentos_industrializados/microdados/publish.sql
  bases/br_anvisa_medicamentos_industrializados/microdados/schema-prod.json
  bases/br_anvisa_medicamentos_industrializados/microdados/schema-staging.json
  bases/br_anvisa_medicamentos_industrializados/microdados/table_config.yaml
Labels: data, data-check-trigger

#525 [dados] Revisão br_ibge_nomes_brasil
  bases/br_ibge_nomes_brasil/quantidade_municipio_nome_2010/publish.sql
  bases/br_ibge_nomes_brasil/quantidade_municipio_nome_2010/schema-prod.json
  bases/br_ibge_nomes_brasil/quantidade_municipio_nome_2010/schema-staging.json
  bases/br_ibge_nomes_brasil/quantidade_municipio_nome_2010/table_config.yaml
  bases/br_ibge_nomes_brasil/quantidade_municipio_nome_2010/table_description.txt
Labels: data, data-check-trigger

#547 [docs] Muda municipios para municipio em PIB e população.
  README.md
  docs/access_data_bq.md
  docs/access_data_local.md
  docs/support.md
Labels: docs

#541 [dados] Revisão br_seeg_emissoes
  bases/br_seeg_emissoes/brasil/schema-staging.json
  bases/br_seeg_emissoes/municipio/publish.sql
  bases/br_seeg_emissoes/municipio/schema-prod.json
Labels: data, data-check-trigger

#553 [dados] Revisão br_mc_auxilio_emergencial
  bases/br_mc_auxilio_emergencial/microdados/publish.sql
  bases/br_mc_auxilio_emergencial/microdados/schema-prod.json
  bases/br_mc_auxilio_emergencial/microdados/table_config.yaml
  bases/br_mc_auxilio_emergencial/microdados/table_description.txt
Labels: data, data-check-trigger

#562 [dados-bot] br_ms_vacinacao_covid19 (2021-07-07)
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data, data-check-trigger

#569 [dados-bot] br_ms_vacinacao_covid19 (2021-07-08)
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data, data-check-trigger

#540 [dados] Revisão br_mapbiomas_estatisticas
  bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/publish.sql
  bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/schema-prod.json
  bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/schema-staging.json
  bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/table_config.yaml
  bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/table_description.txt
  bases/br_mapbiomas_estatisticas/cobertura_municipio_classe/publish.sql
  bases/br_mapbiomas_estatisticas/cobertura_municipio_classe/schema-prod.json
  bases/br_mapbiomas_estatisticas/cobertura_municipio_classe/schema-staging.json
  bases/br_mapbiomas_estatisticas/cobertura_municipio_classe/table_config.yaml
  bases/br_mapbiomas_estatisticas/cobertura_municipio_classe/table_description.txt
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_anual/publish.sql
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_anual/schema-prod.json
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_anual/schema-staging.json
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_anual/table_config.yaml
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_anual/table_description.txt
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_decenal/publish.sql
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_decenal/schema-prod.json
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_decenal/schema-staging.json
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_decenal/table_config.yaml
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_decenal/table_description.txt
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_quinquenal/publish.sql
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_quinquenal/schema-prod.json
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_quinquenal/schema-staging.json
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_quinquenal/table_config.yaml
  bases/br_mapbiomas_estatisticas/transicao_estado_bioma_de_para_quinquenal/table_description.txt
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_anual/publish.sql
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_anual/schema-prod.json
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_anual/schema-staging.json
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_anual/table_config.yaml
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_anual/table_description.txt
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_decenal/publish.sql
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_decenal/schema-prod.json
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_decenal/schema-staging.json
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_decenal/table_config.yaml
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_decenal/table_description.txt
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_quinquenal/publish.sql
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_quinquenal/schema-prod.json
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_quinquenal/schema-staging.json
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_quinquenal/table_config.yaml
  bases/br_mapbiomas_estatisticas/transicao_municipio_de_para_quinquenal/table_description.txt
Labels: data, data-check-trigger

#533 [dados] Revisão br_inep_ideb
  bases/br_inep_ideb/brasil/publish.sql
  bases/br_inep_ideb/brasil/table_config.yaml
  bases/br_inep_ideb/brasil/table_description.txt
  bases/br_inep_ideb/brasil_ano_escolar/publish.sql
  bases/br_inep_ideb/brasil_ano_escolar/schema-staging.json
  bases/br_inep_ideb/brasil_ano_escolar/table_config.yaml
  bases/br_inep_ideb/brasil_ano_escolar/table_description.txt
  bases/br_inep_ideb/dataset_config.yaml
  bases/br_inep_ideb/escola/publish.sql
  bases/br_inep_ideb/escola/schema-prod.json
  bases/br_inep_ideb/escola/schema-staging.json
  bases/br_inep_ideb/escola/table_config.yaml
  bases/br_inep_ideb/escola/table_description.txt
  bases/br_inep_ideb/escola_ano_escolar/publish.sql
  bases/br_inep_ideb/escola_ano_escolar/schema-prod.json
  bases/br_inep_ideb/escola_ano_escolar/schema-staging.json
  bases/br_inep_ideb/escola_ano_escolar/table_config.yaml
  bases/br_inep_ideb/escola_ano_escolar/table_description.txt
  bases/br_inep_ideb/estado/publish.sql
  bases/br_inep_ideb/estado/schema-prod.json
  bases/br_inep_ideb/estado/schema-staging.json
  bases/br_inep_ideb/estado/table_config.yaml
  bases/br_inep_ideb/estado/table_description.txt
  bases/br_inep_ideb/estado_ano_escolar/publish.sql
  bases/br_inep_ideb/estado_ano_escolar/schema-prod.json
  bases/br_inep_ideb/estado_ano_escolar/schema-staging.json
  bases/br_inep_ideb/estado_ano_escolar/table_config.yaml
  bases/br_inep_ideb/estado_ano_escolar/table_description.txt
  bases/br_inep_ideb/municipio/publish.sql
  bases/br_inep_ideb/municipio/schema-prod.json
  bases/br_inep_ideb/municipio/schema-staging.json
  bases/br_inep_ideb/municipio/table_config.yaml
  bases/br_inep_ideb/municipio/table_description.txt
  bases/br_inep_ideb/municipio_ano_escolar/publish.sql
  bases/br_inep_ideb/municipio_ano_escolar/schema-prod.json
  bases/br_inep_ideb/municipio_ano_escolar/table_config.yaml
  bases/br_inep_ideb/municipio_ano_escolar/table_description.txt
  bases/br_inep_ideb/regiao/publish.sql
  bases/br_inep_ideb/regiao/schema-staging.json
  bases/br_inep_ideb/regiao/table_config.yaml
  bases/br_inep_ideb/regiao/table_description.txt
  bases/br_inep_ideb/regiao_ano_escolar/publish.sql
  bases/br_inep_ideb/regiao_ano_escolar/schema-staging.json
  bases/br_inep_ideb/regiao_ano_escolar/table_config.yaml
  bases/br_inep_ideb/regiao_ano_escolar/table_description.txt
Labels: data, data-check-trigger

#572 [dados-bot] br_ms_vacinacao_covid19 (2021-07-09)
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#573 [dados] br_tse_eleicoes: Conserta tabelas com renomeação nos publish.sql.
  bases/br_tse_eleicoes/bens_candidato/publish.sql
  bases/br_tse_eleicoes/bens_candidato/schema-staging.json
  bases/br_tse_eleicoes/bens_candidato/table_config.yaml
  bases/br_tse_eleicoes/code/sub/normalizacao_particao.do
  bases/br_tse_eleicoes/resultados_candidato_municipio/publish.sql
  bases/br_tse_eleicoes/resultados_candidato_municipio/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato_municipio/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/publish.sql
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/table_description.txt
  bases/br_tse_eleicoes/resultados_candidato_secao/publish.sql
  bases/br_tse_eleicoes/resultados_candidato_secao/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato_secao/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_secao/table_description.txt
  bases/br_tse_eleicoes/resultados_partido_municipio/publish.sql
  bases/br_tse_eleicoes/resultados_partido_municipio/schema-staging.json
  bases/br_tse_eleicoes/resultados_partido_municipio/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_municipio/table_description.txt
  bases/br_tse_eleicoes/resultados_partido_municipio_zona/publish.sql
  bases/br_tse_eleicoes/resultados_partido_municipio_zona/schema-staging.json
  bases/br_tse_eleicoes/resultados_partido_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_municipio_zona/table_description.txt
  bases/br_tse_eleicoes/resultados_partido_secao/publish.sql
  bases/br_tse_eleicoes/resultados_partido_secao/schema-staging.json
  bases/br_tse_eleicoes/resultados_partido_secao/table_config.yaml
Labels: data

#575 [dados] Revisão br_mc_indicadores
  bases/br_mc_indicadores/transferencias_municipio/publish.sql
  bases/br_mc_indicadores/transferencias_municipio/schema-prod.json
  bases/br_mc_indicadores/transferencias_municipio/table_config.yaml
  bases/br_mc_indicadores/transferencias_municipio/table_description.txt
Labels: data, data-check-trigger

#577 [dados] Revisão br_ms_sim
  bases/br_ms_sim/municipio/publish.sql
  bases/br_ms_sim/municipio/schema-prod.json
  bases/br_ms_sim/municipio/schema-staging.json
  bases/br_ms_sim/municipio_causa/publish.sql
  bases/br_ms_sim/municipio_causa/schema-prod.json
  bases/br_ms_sim/municipio_causa/schema-staging.json
Labels: data, data-check-trigger

#576 [dados] Revisão br_me_socios
  bases/br_me_socios/empresa/publish.sql
  bases/br_me_socios/empresa/schema-prod.json
  bases/br_me_socios/empresa/schema-staging.json
  bases/br_me_socios/empresa/table_config.yaml
  bases/br_me_socios/empresa/table_description.txt
  bases/br_me_socios/socio/publish.sql
  bases/br_me_socios/socio/schema-prod.json
  bases/br_me_socios/socio/schema-staging.json
  bases/br_me_socios/socio/table_config.yaml
  bases/br_me_socios/socio/table_description.txt
Labels: data, data-check-trigger

#586 [dados] Revisão br_sp_seduc_inse
  bases/br_sp_seduc_inse/escola/publish.sql
  bases/br_sp_seduc_inse/escola/schema-prod.json
Labels: data, data-check-trigger

#585 [dados] Revisão br_sp_seduc_idesp
  bases/br_sp_seduc_idesp/diretoria/publish.sql
  bases/br_sp_seduc_idesp/diretoria/schema-prod.json
  bases/br_sp_seduc_idesp/escola/publish.sql
  bases/br_sp_seduc_idesp/escola/schema-prod.json
Labels: data, data-check-trigger

#579 [dados-bot] br_ms_vacinacao_covid19_microdados (2021-07-12)
  bases/br_ms_vacinacao_covid19/microdados/publish.sql
  bases/br_ms_vacinacao_covid19/microdados/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados/table_description.txt
Labels: data, data-check-trigger

#588 [dados-bot] br_ms_vacinacao_covid19 (2021-07-14)
  bases/br_ms_vacinacao_covid19/microdados/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data, data-check-trigger

#568 [infra] Melhora output das funções list_* e get_* na API do Python
  python-package/basedosdados/download/download.py
  python-package/tests/test_download.py
  python-package/tests/test_storage.py
Labels: next-patch

#598 [docs] atualiza links do discord
  docs/colab_checks.md
  docs/colab_data.md
  docs/colab_infrastructure.md
  docs/odd_2021.md
  docs/style_data.md
  r-package/R/zzzz.R
Labels: docs

#560 [dados] Revisão br_me_rais
  bases/br_me_rais/microdados_estabelecimentos/publish.sql
  bases/br_me_rais/microdados_estabelecimentos/schema-prod.json
  bases/br_me_rais/microdados_estabelecimentos/schema-staging.json
  bases/br_me_rais/microdados_estabelecimentos/table_config.yaml
  bases/br_me_rais/microdados_estabelecimentos/table_description.txt
  bases/br_me_rais/microdados_vinculos/publish.sql
  bases/br_me_rais/microdados_vinculos/schema-prod.json
  bases/br_me_rais/microdados_vinculos/schema-staging.json
  bases/br_me_rais/microdados_vinculos/table_config.yaml
  bases/br_me_rais/microdados_vinculos/table_description.txt
Labels: data

#583 [dados] Revisão br_sp_gov_ssp
  bases/br_sp_gov_ssp/ocorrencias_registradas/publish.sql
  bases/br_sp_gov_ssp/ocorrencias_registradas/schema-prod.json
  bases/br_sp_gov_ssp/ocorrencias_registradas/table_config.yaml
  bases/br_sp_gov_ssp/produtividade_policial/publish.sql
  bases/br_sp_gov_ssp/produtividade_policial/schema-prod.json
  bases/br_sp_gov_ssp/produtividade_policial/table_config.yaml
Labels: data, data-check-trigger

#601 [dados-revisão] mundo_onu_adh
  bases/mundo_onu_adh/municipio/schema-prod.json
  bases/mundo_onu_adh/municipio/schema-staging.json
  bases/mundo_onu_adh/municipio/table_config.yaml
  bases/mundo_onu_adh/uf/publish.sql
  bases/mundo_onu_adh/uf/schema-prod.json
  bases/mundo_onu_adh/uf/schema-staging.json
  bases/mundo_onu_adh/uf/table_config.yaml
Labels: data, data-check-trigger

#599 [dados-bot] br_ms_vacinacao_covid19 (2021-07-16)
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/publish.sql
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#515 [dados] br_anatel_banda_larga_fixa
  bases/br_anatel_banda_larga_fixa/README.md
  bases/br_anatel_banda_larga_fixa/backhaul/publish.sql
  bases/br_anatel_banda_larga_fixa/backhaul/schema-prod.json
  bases/br_anatel_banda_larga_fixa/backhaul/schema-staging.json
  bases/br_anatel_banda_larga_fixa/backhaul/table_config.yaml
  bases/br_anatel_banda_larga_fixa/backhaul/table_description.txt
  bases/br_anatel_banda_larga_fixa/code/br_anatel_banda_larga_fixa_backhaul.ipynb
  bases/br_anatel_banda_larga_fixa/code/br_anatel_banda_larga_microdados.ipynb
  bases/br_anatel_banda_larga_fixa/code/br_anatel_banda_larga_pble.ipynb
  bases/br_anatel_banda_larga_fixa/dataset_config.yaml
  bases/br_anatel_banda_larga_fixa/microdados/publish.sql
  bases/br_anatel_banda_larga_fixa/microdados/schema-prod.json
  bases/br_anatel_banda_larga_fixa/microdados/schema-staging.json
  bases/br_anatel_banda_larga_fixa/microdados/table_config.yaml
  bases/br_anatel_banda_larga_fixa/microdados/table_description.txt
  bases/br_anatel_banda_larga_fixa/municipio/publish.sql
  bases/br_anatel_banda_larga_fixa/municipio/schema-prod.json
  bases/br_anatel_banda_larga_fixa/municipio/schema-staging.json
  bases/br_anatel_banda_larga_fixa/municipio/table_config.yaml
  bases/br_anatel_banda_larga_fixa/municipio/table_description.txt
  bases/br_anatel_banda_larga_fixa/pble/publish.sql
  bases/br_anatel_banda_larga_fixa/pble/schema-prod.json
  bases/br_anatel_banda_larga_fixa/pble/schema-staging.json
  bases/br_anatel_banda_larga_fixa/pble/table_config.yaml
  bases/br_anatel_banda_larga_fixa/pble/table_description.txt
  bases/br_anatel_telefonia_movel/README.md
  bases/br_anatel_telefonia_movel/code/br_anatel_telefonia_movel_ddd.ipynb
  bases/br_anatel_telefonia_movel/code/br_anatel_telefonia_movel_microdados.ipynb
  bases/br_anatel_telefonia_movel/dataset_config.yaml
  bases/br_anatel_telefonia_movel/ddd/publish.sql
  bases/br_anatel_telefonia_movel/ddd/schema-prod.json
  bases/br_anatel_telefonia_movel/ddd/schema-staging.json
  bases/br_anatel_telefonia_movel/ddd/table_config.yaml
  bases/br_anatel_telefonia_movel/ddd/table_description.txt
  bases/br_anatel_telefonia_movel/modalidade/publish.sql
  bases/br_anatel_telefonia_movel/modalidade/schema-prod.json
  bases/br_anatel_telefonia_movel/modalidade/schema-staging.json
  bases/br_anatel_telefonia_movel/modalidade/table_config.yaml
  bases/br_anatel_telefonia_movel/modalidade/table_description.txt
  bases/br_anatel_telefonia_movel/municipio/publish.sql
  bases/br_anatel_telefonia_movel/municipio/schema-prod.json
  bases/br_anatel_telefonia_movel/municipio/schema-staging.json
  bases/br_anatel_telefonia_movel/municipio/table_config.yaml
  bases/br_anatel_telefonia_movel/municipio/table_description.txt
  bases/br_anatel_telefonia_movel/tecnologia/publish.sql
  bases/br_anatel_telefonia_movel/tecnologia/schema-prod.json
  bases/br_anatel_telefonia_movel/tecnologia/schema-staging.json
  bases/br_anatel_telefonia_movel/tecnologia/table_config.yaml
  bases/br_anatel_telefonia_movel/tecnologia/table_description.txt
Labels: data, data-check-trigger

#592 [dados] Revisão br_geobr_mapas
  bases/br_geobr_mapas/bioma/publish.sql
  bases/br_geobr_mapas/bioma/schema-prod.json
  bases/br_geobr_mapas/bioma/schema-staging.json
  bases/br_geobr_mapas/bioma/table_config.yaml
  bases/br_geobr_mapas/bioma/table_description.txt
  bases/br_geobr_mapas/biomas/schema-staging.json
  bases/br_geobr_mapas/biomas/table_description.txt
  bases/br_geobr_mapas/setor_censitario_2010/publish.sql
  bases/br_geobr_mapas/setor_censitario_2010/schema-prod.json
  bases/br_geobr_mapas/setor_censitario_2010/schema-staging.json
  bases/br_geobr_mapas/setor_censitario_2010/table_config.yaml
Labels: data, data-check-trigger

#593 [dados] Revisão br_ponte_indicadores
  bases/br_ponte_indicadores/censo2010_populacao_idade/publish.sql
  bases/br_ponte_indicadores/censo2010_populacao_idade/schema-prod.json
  bases/br_ponte_indicadores/censo2010_populacao_idade/table_config.yaml
  bases/br_ponte_indicadores/censo2010_populacao_idade/table_description.txt
  bases/br_ponte_indicadores/censo2010_populacao_raca/publish.sql
  bases/br_ponte_indicadores/censo2010_populacao_raca/schema-prod.json
  bases/br_ponte_indicadores/censo2010_populacao_raca/table_config.yaml
  bases/br_ponte_indicadores/censo2010_populacao_raca/table_description.txt
  bases/br_ponte_indicadores/saude/publish.sql
  bases/br_ponte_indicadores/saude/schema-prod.json
  bases/br_ponte_indicadores/saude/table_config.yaml
  bases/br_ponte_indicadores/saude/table_description.txt
Labels: data, data-check-trigger

#557 [infra] Configurar o basedosdados a partir de variáveis de ambiente
  docs/colab_data.md
  python-package/basedosdados/__init__.py
  python-package/basedosdados/constants.py
  python-package/basedosdados/upload/base.py
Labels: next-patch

#582 [dados] Revisão br_sp_alesp
  bases/br_sp_alesp/deputado/publish.sql
  bases/br_sp_alesp/deputado/schema-prod.json
  bases/br_sp_alesp/deputado/schema-staging.json
  bases/br_sp_alesp/deputado/table_config.yaml
  bases/br_sp_alesp/deputado/table_description.txt
  bases/br_sp_alesp/deputados/schema-prod.json
  bases/br_sp_alesp/deputados/schema-staging.json
  bases/br_sp_alesp/despesas_gabinete/publish.sql
  bases/br_sp_alesp/despesas_gabinete/schema-prod.json
  bases/br_sp_alesp/despesas_gabinete/table_config.yaml
  bases/br_sp_alesp/despesas_gabinete/table_description.txt
  bases/br_sp_alesp/despesas_gabinete_atual/publish.sql
  bases/br_sp_alesp/despesas_gabinete_atual/schema-prod.json
  bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
  bases/br_sp_alesp/despesas_gabinete_atual/table_description.txt
Labels: data, data-check-trigger

#608 [dados-revisão] Republica tabelas com coluna id_estado.
  bases/br_sp_gov_ssp/ocorrencias_registradas/publish.sql
  bases/br_sp_gov_ssp/ocorrencias_registradas/schema-prod.json
  bases/br_sp_gov_ssp/ocorrencias_registradas/table_config.yaml
  bases/br_sp_gov_ssp/produtividade_policial/publish.sql
  bases/br_sp_gov_ssp/produtividade_policial/schema-prod.json
  bases/br_sp_gov_ssp/produtividade_policial/table_config.yaml
Labels: data

#610 [dados-revisão] br_sp_gov_ssp
  bases/br_sp_gov_ssp/ocorrencias_registradas/schema-prod.json
  bases/br_sp_gov_ssp/ocorrencias_registradas/table_config.yaml
  bases/br_sp_gov_ssp/produtividade_policial/schema-prod.json
  bases/br_sp_gov_ssp/produtividade_policial/table_config.yaml
Labels: data

#559 [dados] br_cgu_pessoal_executivo_federal
  bases/br_cgu_pessoal_executivo_federal/README.md
  bases/br_cgu_pessoal_executivo_federal/code/tercerizados_cgu.R
  bases/br_cgu_pessoal_executivo_federal/dataset_config.yaml
  bases/br_cgu_pessoal_executivo_federal/terceirizados/publish.sql
  bases/br_cgu_pessoal_executivo_federal/terceirizados/schema-prod.json
  bases/br_cgu_pessoal_executivo_federal/terceirizados/schema-staging.json
  bases/br_cgu_pessoal_executivo_federal/terceirizados/table_config.yaml
  bases/br_cgu_pessoal_executivo_federal/terceirizados/table_description.txt
Labels: data, data-check-trigger

#564 [dados] Revisão ipea_acesso_oportunidades
  bases/br_ipea_acesso_oportunidades/estatisticas_2019/publish.sql
  bases/br_ipea_acesso_oportunidades/estatisticas_2019/schema-prod.json
  bases/br_ipea_acesso_oportunidades/indicadores_2019/publish.sql
  bases/br_ipea_acesso_oportunidades/indicadores_2019/schema-prod.json
Labels: data, data-check-trigger

#574 [dados] Revisão br_ibge_censo_demografico
  bases/br_ibge_censo_demografico/microdados_domicilio_1970/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_1970/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1980/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_1980/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1991/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_1991/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1970/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_1970/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1980/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_1980/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1991/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_1991/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2000/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_2000/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/schema-prod.json
Labels: data, data-check-trigger

#566 [dados]Revisão br_inep_indicadores_educacionais
  bases/br_inep_indicadores_educacionais/brasil/publish.sql
  bases/br_inep_indicadores_educacionais/brasil/table_config.yaml
  bases/br_inep_indicadores_educacionais/escola/publish.sql
  bases/br_inep_indicadores_educacionais/escola/schema-prod.json
  bases/br_inep_indicadores_educacionais/escola/table_config.yaml
  bases/br_inep_indicadores_educacionais/escola/table_description.txt
  bases/br_inep_indicadores_educacionais/escola_nivel_socioeconomico/publish.sql
  bases/br_inep_indicadores_educacionais/escola_nivel_socioeconomico/schema-prod.json
  bases/br_inep_indicadores_educacionais/fluxo_educacao_superior/publish.sql
  bases/br_inep_indicadores_educacionais/fluxo_educacao_superior/schema-prod.json
  bases/br_inep_indicadores_educacionais/municipio/publish.sql
  bases/br_inep_indicadores_educacionais/municipio/schema-prod.json
  bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
  bases/br_inep_indicadores_educacionais/municipio/table_description.txt
  bases/br_inep_indicadores_educacionais/municipio_taxas_transicao/publish.sql
  bases/br_inep_indicadores_educacionais/municipio_taxas_transicao/schema-prod.json
  bases/br_inep_indicadores_educacionais/municipio_taxas_transicao/table_config.yaml
  bases/br_inep_indicadores_educacionais/regiao/publish.sql
  bases/br_inep_indicadores_educacionais/regiao/table_config.yaml
  bases/br_inep_indicadores_educacionais/uf/publish.sql
  bases/br_inep_indicadores_educacionais/uf/table_config.yaml
Labels: data, data-check-trigger

#614 [dados] mundo_kaggle_olimpiadas
  bases/mundo_kaggle_olimpiadas/README.md
  bases/mundo_kaggle_olimpiadas/code/mundo_kaggle_olimpiadas.ipynb
  bases/mundo_kaggle_olimpiadas/dataset_config.yaml
  bases/mundo_kaggle_olimpiadas/microdados/publish.sql
  bases/mundo_kaggle_olimpiadas/microdados/schema-prod.json
  bases/mundo_kaggle_olimpiadas/microdados/schema-staging.json
  bases/mundo_kaggle_olimpiadas/microdados/table_config.yaml
  bases/mundo_kaggle_olimpiadas/microdados/table_description.txt
Labels: data, data-check-trigger

#605 [dados] Revisão br_inep_sinopse_estatistica_educacao_basica
  bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/publish.sql
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/schema-prod.json
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/schema-staging.json
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/table_config.yaml
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/table_description.txt
  bases/br_inep_sinopse_estatistica_educacao_basica/matriculas/publish.sql
  bases/br_inep_sinopse_estatistica_educacao_basica/matriculas/schema-prod.json
  bases/br_inep_sinopse_estatistica_educacao_basica/matriculas/schema-staging.json
  bases/br_inep_sinopse_estatistica_educacao_basica/matriculas/table_description.txt
Labels: data, data-check-trigger

#623 [dados-bot] br_ms_vacinacao_covid19 (2021-07-23)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#617 [docs] Atualiza docs sem os parâmetros faltando de create
  docs/colab_data.md
Labels: docs

#624 [dados] br_senado_cpipandemia
  bases/br_senado_cpipandemia/.gitignore
  bases/br_senado_cpipandemia/README.md
  bases/br_senado_cpipandemia/code/1-baixar_arquivos.R
  bases/br_senado_cpipandemia/code/2-ler_arquivos.R
  bases/br_senado_cpipandemia/code/3-limpar_base.R
  bases/br_senado_cpipandemia/dataset_config.yaml
  bases/br_senado_cpipandemia/discursos/publish.sql
  bases/br_senado_cpipandemia/discursos/schema-prod.json
  bases/br_senado_cpipandemia/discursos/schema-staging.json
  bases/br_senado_cpipandemia/discursos/table_config.yaml
  bases/br_senado_cpipandemia/discursos/table_description.txt
  bases/br_senado_cpipandemia/extra/architecture/discursos/discursos.xlsx
  bases/br_senado_cpipandemia/extra/dicionario.xlsx
Labels: data, data-check-trigger

#618 [dados] Revisão br_inep_indicadores
  bases/br_inep_indicadores_educacionais/brasil/publish.sql
  bases/br_inep_indicadores_educacionais/brasil/schema-prod.json
  bases/br_inep_indicadores_educacionais/brasil/schema-staging.json
  bases/br_inep_indicadores_educacionais/brasil/table_description.txt
  bases/br_inep_indicadores_educacionais/brasil_remuneracao_docentes/schema-prod.json
  bases/br_inep_indicadores_educacionais/brasil_remuneracao_docentes/table_description.txt
  bases/br_inep_indicadores_educacionais/escola/publish.sql
  bases/br_inep_indicadores_educacionais/escola/schema-prod.json
  bases/br_inep_indicadores_educacionais/escola/schema-staging.json
  bases/br_inep_indicadores_educacionais/municipio/publish.sql
  bases/br_inep_indicadores_educacionais/municipio/schema-prod.json
  bases/br_inep_indicadores_educacionais/municipio/schema-staging.json
  bases/br_inep_indicadores_educacionais/municipio_taxas_transicao/schema-prod.json
  bases/br_inep_indicadores_educacionais/regiao/publish.sql
  bases/br_inep_indicadores_educacionais/regiao/schema-prod.json
  bases/br_inep_indicadores_educacionais/regiao/schema-staging.json
  bases/br_inep_indicadores_educacionais/uf/publish.sql
  bases/br_inep_indicadores_educacionais/uf/schema-prod.json
  bases/br_inep_indicadores_educacionais/uf/schema-staging.json
Labels: data, data-check-trigger

#497 [infra] r-package - Antiga versão 0.0.6, pedaço que falta para submeter a 0.1.0
  .gitignore
  r-package/.Rbuildignore
  r-package/.Rprofile
  r-package/DESCRIPTION
  r-package/NAMESPACE
  r-package/R/bdplyr.R
  r-package/R/billing.R
  r-package/R/download.R
  r-package/R/partition.R
  r-package/R/query_table.R
  r-package/R/zzzz.R
  r-package/man/bd_write.Rd
  r-package/man/bdplyr.Rd
  r-package/man/dot-onLoad.Rd
  r-package/man/download.Rd
  r-package/man/partition_table.Rd
  r-package/man/read_sql.Rd
  r-package/man/set_billing_id.Rd
  r-package/renv.lock
  r-package/renv/.gitignore
  r-package/renv/activate.R
  r-package/tests/testthat/test-bdplyr.R
  r-package/tests/testthat/test-download.R
Labels: R, enhancement

#629 [dados] Revisão br_inep_indicadores_educacionais
  bases/br_inep_indicadores_educacionais/escola/publish.sql
  bases/br_inep_indicadores_educacionais/municipio_taxas_transicao/publish.sql
  bases/br_inep_indicadores_educacionais/municipio_taxas_transicao/schema-staging.json
Labels: data, data-check-trigger

#627 [infra] Cria o changelog do pacote de R
  r-package/Changelog.md
  r-package/NAMESPACE
Labels: docs

#635 [dados-bot] br_ms_vacinacao_covid19 (2021-07-26)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#622 [dados] br_inmet_bdmep
  bases/br_inmet_bdmep/README.md
  bases/br_inmet_bdmep/code/create_tables.R
  bases/br_inmet_bdmep/code/func/change_names.R
  bases/br_inmet_bdmep/code/func/download_inmet.R
  bases/br_inmet_bdmep/code/func/get_city.R
  bases/br_inmet_bdmep/code/func/get_clima_info.R
  bases/br_inmet_bdmep/code/func/get_data.R
  bases/br_inmet_bdmep/code/func/get_station_info.R
  bases/br_inmet_bdmep/dataset_config.yaml
  bases/br_inmet_bdmep/estacao/publish.sql
  bases/br_inmet_bdmep/estacao/schema-prod.json
  bases/br_inmet_bdmep/estacao/schema-staging.json
  bases/br_inmet_bdmep/estacao/table_config.yaml
  bases/br_inmet_bdmep/estacao/table_description.txt
  bases/br_inmet_bdmep/microdados/publish.sql
  bases/br_inmet_bdmep/microdados/schema-prod.json
  bases/br_inmet_bdmep/microdados/schema-staging.json
  bases/br_inmet_bdmep/microdados/table_config.yaml
  bases/br_inmet_bdmep/microdados/table_description.txt
Labels: data, data-check-trigger

#632 [dados] Revisão br_ibge_amc
  bases/br_ibge_amc/municipio_de_para/publish.sql
  bases/br_ibge_amc/municipio_de_para/schema-staging.json
Labels: data

#633 [dados] Revisão br_anvisa_medicamentos_industrializados
  bases/br_anvisa_medicamentos_industrializados/microdados/publish.sql
  bases/br_anvisa_medicamentos_industrializados/microdados/schema-staging.json
Labels: data

#631 [dados] Revisão br_sp_alesp
  bases/br_sp_alesp/deputado/publish.sql
  bases/br_sp_alesp/deputado/schema-staging.json
Labels: data

#542 [extra-revisao] add codigo mapeamento erros tipagem
  extras/revisao_bases/mapeando_erros_tipagem_bd.ipynb
Labels: docs

#638 [dados-bot] br_ms_vacinacao_covid19 (2021-07-27)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#625 [dados] corrige br_senado_cpipandemia
  bases/br_senado_cpipandemia/discursos/table_config.yaml
Labels: data, data-check-trigger

#639 [dados-bot] br_ms_vacinacao_covid19 (2021-07-28)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#626 [infra] Adiciona testes e corrige o traceback da função `download`
  python-package/basedosdados/download/download.py
  python-package/basedosdados/exceptions.py
  python-package/basedosdados/upload/table.py
  python-package/basedosdados/validation/exceptions.py
  python-package/tests/test_download.py
  python-package/tests/test_table.py
Labels: next-patch

#651 [dados-bot] br_ms_vacinacao_covid19 (2021-07-29)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#594 [dados] Revisão br_sp_gov_orcamento
  bases/br_sp_gov_orcamento/despesa/publish.sql
  bases/br_sp_gov_orcamento/despesa/schema-prod.json
  bases/br_sp_gov_orcamento/despesa/schema-staging.json
  bases/br_sp_gov_orcamento/despesa/table_config.yaml
  bases/br_sp_gov_orcamento/despesa/table_description.txt
  bases/br_sp_gov_orcamento/despesas/schema-prod.json
  bases/br_sp_gov_orcamento/receita_arrecadada/publish.sql
  bases/br_sp_gov_orcamento/receita_arrecadada/schema-prod.json
  bases/br_sp_gov_orcamento/receita_arrecadada/schema-staging.json
  bases/br_sp_gov_orcamento/receita_arrecadada/table_config.yaml
  bases/br_sp_gov_orcamento/receita_arrecadada/table_description.txt
  bases/br_sp_gov_orcamento/receita_prevista/publish.sql
  bases/br_sp_gov_orcamento/receita_prevista/schema-staging.json
  bases/br_sp_gov_orcamento/receita_prevista/table_config.yaml
  bases/br_sp_gov_orcamento/receita_prevista/table_description.txt
Labels: data, data-check-trigger
