Repository basedosdados/sdk, pull requests merged in 2021-11, with the labels that each got.

#917 [dados-bot] br_ms_vacinacao_covid19 (2021-10-31)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#858 [dados-fix] br_me_rais
  bases/br_bd_diretorios_brasil/cbo_2002/schema-staging.json
  bases/br_bd_diretorios_brasil/code/[dados] br_ibge_cbo2002.ipynb
  bases/br_bd_diretorios_brasil/natureza_juridica/publish.sql
  bases/br_bd_diretorios_brasil/natureza_juridica/schema-prod.json
  bases/br_bd_diretorios_brasil/natureza_juridica/schema-staging.json
  bases/br_bd_diretorios_brasil/natureza_juridica/table_config.yaml
  bases/br_bd_diretorios_brasil/natureza_juridica/table_description.txt
  bases/br_me_rais/dataset_config.yaml
  bases/br_me_rais/dicionario/publish.sql
  bases/br_me_rais/dicionario/schema-prod.json
  bases/br_me_rais/dicionario/schema-staging.json
  bases/br_me_rais/dicionario/table_config.yaml
  bases/br_me_rais/dicionario/table_description.txt
  bases/br_me_rais/dictionaries/estabelecimento/10RAIS_estabelecimento_layout1999e2000.xls
  bases/br_me_rais/dictionaries/estabelecimento/11RAIS_estabelecimento_layout2001.xls
  bases/br_me_rais/dictionaries/estabelecimento/12RAIS_estabelecimento_layout.2002a2013.xls
  bases/br_me_rais/dictionaries/estabelecimento/1RAIS_estabelecimento_layout1985A1989.xls
  bases/br_me_rais/dictionaries/estabelecimento/2RAIS_estabelecimento_layout1990.xls
  bases/br_me_rais/dictionaries/estabelecimento/3RAIS_estabelecimento_layout1991e1992.xls
  bases/br_me_rais/dictionaries/estabelecimento/4RAIS_estabelecimento_layout1993.xls
  bases/br_me_rais/dictionaries/estabelecimento/5RAIS_estabelecimento_layout1994.xls
  bases/br_me_rais/dictionaries/estabelecimento/6RAIS_estabelecimento_layout1995.xls
  bases/br_me_rais/dictionaries/estabelecimento/7RAIS_estabelecimento_layout1996.xls
  bases/br_me_rais/dictionaries/estabelecimento/8RAIS_estabelecimento_layout1997.xls
  bases/br_me_rais/dictionaries/estabelecimento/9RAIS_estabelecimento_layout1998.xls
  bases/br_me_rais/dictionaries/estabelecimento/RAIS_estabelecimento_layout2014a2017.xls
  bases/br_me_rais/dictionaries/estabelecimento/RAIS_estabelecimento_layout2018.xls
  bases/br_me_rais/dictionaries/vinculos/RAIS_vinculos_layout.xls
  bases/br_me_rais/dictionaries/vinculos/RAIS_vinculos_layout1985a1993.xls
  bases/br_me_rais/dictionaries/vinculos/RAIS_vinculos_layout2015.xls
  bases/br_me_rais/dictionaries/vinculos/RAIS_vinculos_layout2016.xls
  bases/br_me_rais/dictionaries/vinculos/RAIS_vinculos_layout2017.xls
  bases/br_me_rais/dictionaries/vinculos/RAIS_vinculos_layout2018.xls
  bases/br_me_rais/microdados_estabelecimentos/publish.sql
  bases/br_me_rais/microdados_estabelecimentos/schema-prod.json
  bases/br_me_rais/microdados_estabelecimentos/schema-staging.json
  bases/br_me_rais/microdados_estabelecimentos/table_config.yaml
  bases/br_me_rais/microdados_estabelecimentos/table_description.txt
  bases/br_me_rais/microdados_vinculos/publish.sql
  bases/br_me_rais/microdados_vinculos/schema-prod.json
  bases/br_me_rais/microdados_vinculos/schema-staging.json
  bases/br_me_rais/microdados_vinculos/table_config.yaml
  bases/br_me_rais/microdados_vinculos/table_description.txt
Labels: data

#920 [dados] br_bd_diretorios_brasil.regiao
  bases/br_bd_diretorios_brasil/regiao/publish.sql
  bases/br_bd_diretorios_brasil/regiao/schema-prod.json
  bases/br_bd_diretorios_brasil/regiao/schema-staging.json
  bases/br_bd_diretorios_brasil/regiao/table_config.yaml
  bases/br_bd_diretorios_brasil/regiao/table_description.txt
Labels: data, data-check-trigger

#922 [dados-bot] br_ms_vacinacao_covid19 (2021-11-02)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#887 [dados] br_bd_diretorios_brasil.subatividade_ibge
  bases/br_bd_diretorios_brasil/subatividade_ibge/publish.sql
  bases/br_bd_diretorios_brasil/subatividade_ibge/schema-prod.json
  bases/br_bd_diretorios_brasil/subatividade_ibge/schema-staging.json
  bases/br_bd_diretorios_brasil/subatividade_ibge/table_config.yaml
  bases/br_bd_diretorios_brasil/subatividade_ibge/table_description.txt
Labels: data, data-check-trigger

#946 [dados-fix] re-publishes cbo_2002.
  bases/br_bd_diretorios_brasil/cbo_2002/table_config.yaml
  bases/br_bd_diretorios_brasil/cbo_2002/table_description.txt
Labels: data

#953 [data-update] Dados Inflação
  bases/br_ibge_inpc/mes_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca/mes_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca15/mes_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_rm/table_config.yaml
Labels: data, data-check-trigger, data-update

#976 debug(infra): testing actions
  bases/test_dataset/test_table/table_config.yaml
Labels: data-check-trigger

#981 [infra] Conserta passo de publicação dos metadados na Action `table-approve`
  .github/workflows/table-approve/table_approve.py
Labels: bug, priority, infra, metadata

#980 [infra] Conserta dependência do `mkdocs` no `requirements-dev.txt`
  python-package/requirements-dev.txt
Labels: bug, docs, infra

#987 [docs] Reverte mudanças em `mkdocs.yml` causadas pelo merge do Python 1.6.0
  README.md
  docs/access_data_packages.md
  mkdocs.yml
  python-package/requirements-dev.txt
Labels: bug, docs

#983 [infra] Conserta passo de publicação dos metadados na action `table-approve` [2]
  .github/workflows/table-approve.yml
  .github/workflows/table-approve/table_approve.py
  bases/test_dataset/dataset_config.yaml
  bases/test_dataset/test_table/table_config.yaml
  python-package/tests/test_metadata.py
Labels: bug, priority, infra, metadata
