Repository basedosdados/sdk, pull requests merged in 2021-08, with the labels that each got.

#654 [dados] br_bd_diretorios_brasil
  bases/br_bd_diretorios_brasil/cid10/schema-staging.json
  bases/br_bd_diretorios_brasil/cid9/schema-staging.json
  bases/br_bd_diretorios_brasil/cid_10/publish.sql
  bases/br_bd_diretorios_brasil/cid_10/schema-prod.json
  bases/br_bd_diretorios_brasil/cid_10/schema-staging.json
  bases/br_bd_diretorios_brasil/cid_10/table_config.yaml
  bases/br_bd_diretorios_brasil/cid_10/table_description.txt
  bases/br_bd_diretorios_brasil/cid_9/publish.sql
  bases/br_bd_diretorios_brasil/cid_9/schema-prod.json
  bases/br_bd_diretorios_brasil/cid_9/schema-staging.json
  bases/br_bd_diretorios_brasil/cid_9/table_config.yaml
  bases/br_bd_diretorios_brasil/cid_9/table_description.txt
  bases/br_bd_diretorios_brasil/distrito/publish.sql
  bases/br_bd_diretorios_brasil/distrito/schema-prod.json
  bases/br_bd_diretorios_brasil/distrito/schema-staging.json
  bases/br_bd_diretorios_brasil/distrito/table_config.yaml
  bases/br_bd_diretorios_brasil/escola/publish.sql
  bases/br_bd_diretorios_brasil/escola/schema-prod.json
  bases/br_bd_diretorios_brasil/escola/schema-staging.json
  bases/br_bd_diretorios_brasil/escola/table_config.yaml
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/schema-prod.json
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/schema-staging.json
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/table_config.yaml
  bases/br_bd_diretorios_brasil/instituicao_ensino_superior/table_description.txt
  bases/br_bd_diretorios_brasil/municipio/publish.sql
  bases/br_bd_diretorios_brasil/municipio/schema-prod.json
  bases/br_bd_diretorios_brasil/municipio/schema-staging.json
  bases/br_bd_diretorios_brasil/municipio/table_config.yaml
  bases/br_bd_diretorios_brasil/pais/publish.sql
  bases/br_bd_diretorios_brasil/pais/schema-prod.json
  bases/br_bd_diretorios_brasil/pais/schema-staging.json
  bases/br_bd_diretorios_brasil/pais/table_config.yaml
  bases/br_bd_diretorios_brasil/uf/publish.sql
  bases/br_bd_diretorios_brasil/uf/schema-prod.json
  bases/br_bd_diretorios_brasil/uf/schema-staging.json
  bases/br_bd_diretorios_brasil/uf/table_config.yaml
Labels: data, data-check-trigger

#661 [dados-bot] br_ms_vacinacao_covid19 (2021-08-01)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#662 [dados-bot] br_ms_vacinacao_covid19 (2021-08-02)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#672 [dados-bot] br_ms_vacinacao_covid19 (2021-08-04)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#674 [infra] corrige impressão do data check
  .github/workflows/data-check.yml
  .github/workflows/data-check/checks.yaml
  .github/workflows/data-check/conftest.py
  .github/workflows/data-check/test_data.py
Labels: data-check-trigger

#676 [dados-bot] br_ms_vacinacao_covid19 (2021-08-05)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#677 [dados-bot] br_ms_vacinacao_covid19 (2021-08-06)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#682 [dados-bot] br_ms_vacinacao_covid19 (2021-08-08)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#684 [dados] `br_sp_gov_ssp` | fix table and update data
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_atividade_policial_MODELO.csv
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_atividade_policial_MODELO_FINAL.csv
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_ocorrencias_registradas_MODELO.csv
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_ocorrencias_registradas_MODELO_FINAL.csv
  bases/br_sp_gov_ssp/code/scripts/ssp_scrapy.py
  bases/br_sp_gov_ssp/ocorrencias_registradas/table_config.yaml
  bases/br_sp_gov_ssp/produtividade_policial/table_config.yaml
Labels: data

#689 [dados-bot] br_ms_vacinacao_covid19 (2021-08-09)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#668 [dados] br_me_cno
  bases/br_me_cno/README.md
  bases/br_me_cno/code/Captura.py
  bases/br_me_cno/code/Limpeza.py
  bases/br_me_cno/dataset_config.yaml
  bases/br_me_cno/microdados/publish.sql
  bases/br_me_cno/microdados/schema-prod.json
  bases/br_me_cno/microdados/schema-staging.json
  bases/br_me_cno/microdados/table_config.yaml
  bases/br_me_cno/microdados/table_description.txt
  bases/br_me_cno/microdados_cnae/publish.sql
  bases/br_me_cno/microdados_cnae/schema-prod.json
  bases/br_me_cno/microdados_cnae/schema-staging.json
  bases/br_me_cno/microdados_cnae/table_config.yaml
  bases/br_me_cno/microdados_cnae/table_description.txt
  bases/br_me_cno/microdados_vinculo/publish.sql
  bases/br_me_cno/microdados_vinculo/schema-prod.json
  bases/br_me_cno/microdados_vinculo/schema-staging.json
  bases/br_me_cno/microdados_vinculo/table_config.yaml
  bases/br_me_cno/microdados_vinculo/table_description.txt
Labels: data, data-check-trigger

#692 [dados] br_me_cno
  bases/br_me_cno/microdados/table_config.yaml
  bases/br_me_cno/microdados_cnae/table_config.yaml
  bases/br_me_cno/microdados_vinculo/table_config.yaml
Labels: data, data-check-trigger

#634 [dados] br_isp_estatisticas_seguranca
  bases/br_isp_estatisticas_seguranca/README.md
  bases/br_isp_estatisticas_seguranca/code/bases_isp.R
  bases/br_isp_estatisticas_seguranca/dataset_config.yaml
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_cisp/publish.sql
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_cisp/schema-prod.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_cisp/schema-staging.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_cisp/table_config.yaml
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_cisp/table_description.txt
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_municipio/publish.sql
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_municipio/schema-prod.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_municipio/schema-staging.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_municipio/table_config.yaml
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_municipio/table_description.txt
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_uf/publish.sql
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_uf/schema-prod.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_uf/schema-staging.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_uf/table_config.yaml
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_uf/table_description.txt
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_upp/publish.sql
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_upp/schema-prod.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_upp/schema-staging.json
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_upp/table_config.yaml
  bases/br_isp_estatisticas_seguranca/evolucao_mensal_upp/table_description.txt
  bases/br_isp_estatisticas_seguranca/feminicidio_mensal_cisp/publish.sql
  bases/br_isp_estatisticas_seguranca/feminicidio_mensal_cisp/schema-prod.json
  bases/br_isp_estatisticas_seguranca/feminicidio_mensal_cisp/schema-staging.json
  bases/br_isp_estatisticas_seguranca/feminicidio_mensal_cisp/table_config.yaml
  bases/br_isp_estatisticas_seguranca/feminicidio_mensal_cisp/table_description.txt
  bases/br_isp_estatisticas_seguranca/policiais_mortos_servico/publish.sql
  bases/br_isp_estatisticas_seguranca/policiais_mortos_servico/schema-prod.json
  bases/br_isp_estatisticas_seguranca/policiais_mortos_servico/schema-staging.json
  bases/br_isp_estatisticas_seguranca/policiais_mortos_servico/table_config.yaml
  bases/br_isp_estatisticas_seguranca/policiais_mortos_servico/table_description.txt
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_municipio/publish.sql
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_municipio/schema-prod.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_municipio/schema-staging.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_municipio/table_config.yaml
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_municipio/table_description.txt
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_uf/publish.sql
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_uf/schema-prod.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_uf/schema-staging.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_uf/table_config.yaml
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_anual_uf/table_description.txt
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/publish.sql
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/schema-prod.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/schema-staging.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/table_config.yaml
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/table_description.txt
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_uf/publish.sql
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_uf/schema-prod.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_uf/schema-staging.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_uf/table_config.yaml
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_uf/table_description.txt
Labels: data, data-check-trigger

#699 [dados-bot] br_ms_vacinacao_covid19 (2021-08-11)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#703 [dados-bot] br_ms_vacinacao_covid19 (2021-08-12)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#705 [dados-bot] br_ms_vacinacao_covid19 (2021-08-13)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#702 [dados] br_ms_populacao
  bases/br_ms_populacao/README.md
  bases/br_ms_populacao/code/br_ms_populacao.ipynb
  bases/br_ms_populacao/dataset_config.yaml
  bases/br_ms_populacao/municipio/publish.sql
  bases/br_ms_populacao/municipio/schema-prod.json
  bases/br_ms_populacao/municipio/schema-staging.json
  bases/br_ms_populacao/municipio/table_config.yaml
  bases/br_ms_populacao/municipio/table_description.txt
Labels: data, data-check-trigger

#451 [dados] br_inep_saeb
  bases/br_inep_saeb/aluno_ef_1995_2005/publish.sql
  bases/br_inep_saeb/aluno_ef_1995_2005/schema-prod.json
  bases/br_inep_saeb/aluno_ef_1995_2005/schema-staging.json
  bases/br_inep_saeb/aluno_ef_1995_2005/table_config.yaml
  bases/br_inep_saeb/aluno_ef_1995_2005/table_description.txt
  bases/br_inep_saeb/aluno_ef_2007_2019/publish.sql
  bases/br_inep_saeb/aluno_ef_2007_2019/schema-prod.json
  bases/br_inep_saeb/aluno_ef_2007_2019/schema-staging.json
  bases/br_inep_saeb/aluno_ef_2007_2019/table_config.yaml
  bases/br_inep_saeb/aluno_ef_2007_2019/table_description.txt
  bases/br_inep_saeb/aluno_em_1995_2005/publish.sql
  bases/br_inep_saeb/aluno_em_1995_2005/schema-prod.json
  bases/br_inep_saeb/aluno_em_1995_2005/schema-staging.json
  bases/br_inep_saeb/aluno_em_1995_2005/table_config.yaml
  bases/br_inep_saeb/aluno_em_1995_2005/table_description.txt
  bases/br_inep_saeb/aluno_em_2011_2019/publish.sql
  bases/br_inep_saeb/aluno_em_2011_2019/schema-prod.json
  bases/br_inep_saeb/aluno_em_2011_2019/schema-staging.json
  bases/br_inep_saeb/aluno_em_2011_2019/table_config.yaml
  bases/br_inep_saeb/aluno_em_2011_2019/table_description.txt
  bases/br_inep_saeb/escola_1995_2005/publish.sql
  bases/br_inep_saeb/escola_1995_2005/schema-prod.json
  bases/br_inep_saeb/escola_1995_2005/schema-staging.json
  bases/br_inep_saeb/escola_1995_2005/table_config.yaml
  bases/br_inep_saeb/escola_1995_2005/table_description.txt
  bases/br_inep_saeb/escola_2007_2019/publish.sql
  bases/br_inep_saeb/escola_2007_2019/schema-prod.json
  bases/br_inep_saeb/escola_2007_2019/schema-staging.json
  bases/br_inep_saeb/escola_2007_2019/table_config.yaml
  bases/br_inep_saeb/escola_2007_2019/table_description.txt
Labels: data, data-check-trigger

#709 [dados] br_inep_saeb
  bases/br_inep_saeb/aluno_ef_1995_2005/schema-prod.json
  bases/br_inep_saeb/aluno_ef_1995_2005/table_config.yaml
  bases/br_inep_saeb/aluno_ef_1995_2005/table_description.txt
  bases/br_inep_saeb/aluno_ef_2007_2019/table_config.yaml
  bases/br_inep_saeb/aluno_em_1995_2005/schema-prod.json
  bases/br_inep_saeb/aluno_em_1995_2005/table_config.yaml
  bases/br_inep_saeb/aluno_em_1995_2005/table_description.txt
  bases/br_inep_saeb/aluno_em_2011_2019/table_config.yaml
  bases/br_inep_saeb/aluno_em_2011_2019/table_description.txt
  bases/br_inep_saeb/escola_1995_2005/table_config.yaml
  bases/br_inep_saeb/escola_2007_2019/table_config.yaml
Labels: data, data-check-trigger

#548 [dados] Revisão! br_mobilidados_indicadores
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/publish.sql
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/schema-prod.json
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
  bases/br_mobilidados_indicadores/divisao_modal/publish.sql
  bases/br_mobilidados_indicadores/divisao_modal/schema-prod.json
  bases/br_mobilidados_indicadores/divisao_modal/schema-staging.json
  bases/br_mobilidados_indicadores/divisao_modal/table_config.yaml
  bases/br_mobilidados_indicadores/divisao_modal/table_description.txt
  bases/br_mobilidados_indicadores/emissao_co2_material_particulado/publish.sql
  bases/br_mobilidados_indicadores/emissao_co2_material_particulado/schema-prod.json
  bases/br_mobilidados_indicadores/proporcao_domicilios_infra_urbana/publish.sql
  bases/br_mobilidados_indicadores/proporcao_domicilios_infra_urbana/schema-prod.json
  bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/publish.sql
  bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/schema-prod.json
  bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/schema-staging.json
  bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/table_config.yaml
  bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/table_description.txt
  bases/br_mobilidados_indicadores/proporcao_pessoas_prox_infra_cicloviaria/publish.sql
  bases/br_mobilidados_indicadores/proporcao_pessoas_prox_infra_cicloviaria/schema-prod.json
  bases/br_mobilidados_indicadores/proporcao_pessoas_prox_infra_cicloviaria/schema-staging.json
  bases/br_mobilidados_indicadores/proporcao_pessoas_prox_infra_cicloviaria/table_config.yaml
  bases/br_mobilidados_indicadores/proporcao_pessoas_prox_infra_cicloviaria/table_description.txt
  bases/br_mobilidados_indicadores/proporcao_pessoas_proximas_pnt/publish.sql
  bases/br_mobilidados_indicadores/proporcao_pessoas_proximas_pnt/schema-prod.json
  bases/br_mobilidados_indicadores/proporcao_pessoas_proximas_pnt/schema-staging.json
  bases/br_mobilidados_indicadores/proporcao_pessoas_proximas_pnt/table_config.yaml
  bases/br_mobilidados_indicadores/proporcao_pessoas_proximas_pnt/table_description.txt
  bases/br_mobilidados_indicadores/taxa_motorizacao/publish.sql
  bases/br_mobilidados_indicadores/taxa_motorizacao/schema-prod.json
  bases/br_mobilidados_indicadores/taxa_motorizacao/table_description.txt
  bases/br_mobilidados_indicadores/tempo_deslocamento_casa_trabalho/publish.sql
  bases/br_mobilidados_indicadores/tempo_deslocamento_casa_trabalho/schema-prod.json
  bases/br_mobilidados_indicadores/transporte_media_alta_capacidade/publish.sql
  bases/br_mobilidados_indicadores/transporte_media_alta_capacidade/schema-prod.json
  bases/br_mobilidados_indicadores/transporte_media_alta_capacidade/schema-staging.json
  bases/br_mobilidados_indicadores/transporte_media_alta_capacidade/table_config.yaml
  bases/br_mobilidados_indicadores/transporte_media_alta_capacidade/table_description.txt
Labels: data, data-check-trigger

#719 [dados-bot] br_ms_vacinacao_covid19 (2021-08-17)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#720 [dados-bot] br_ms_vacinacao_covid19 (2021-08-18)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#721 [infra] adiciona a opção de ignorar datasets ao `data-check`
  .github/DATA_CHECK_SKIP.csv
  .github/workflows/data-check/conftest.py
  .github/workflows/table-approve.yml
  .gitignore
Labels: infra

#711 [dados] br_me_cno adiciona dicionário
  bases/br_me_cno/dicionario/publish.sql
  bases/br_me_cno/dicionario/schema-prod.json
  bases/br_me_cno/dicionario/schema-staging.json
  bases/br_me_cno/dicionario/table_config.yaml
  bases/br_me_cno/dicionario/table_description.txt
Labels: data, data-check-trigger

#737 [dados] br_anp_precos_combustiveis
  bases/br_anp_precos_combustiveis/README.md
  bases/br_anp_precos_combustiveis/code/[dados]_br_anp_preco_combustiveis.ipynb
  bases/br_anp_precos_combustiveis/dataset_config.yaml
  bases/br_anp_precos_combustiveis/microdados/publish.sql
  bases/br_anp_precos_combustiveis/microdados/schema-prod.json
  bases/br_anp_precos_combustiveis/microdados/schema-staging.json
  bases/br_anp_precos_combustiveis/microdados/table_config.yaml
  bases/br_anp_precos_combustiveis/microdados/table_description.txt
Labels: data, data-check-trigger

#725 [dados] br_inep_ana
  bases/br_inep_ana/README.md
  bases/br_inep_ana/aluno/publish.sql
  bases/br_inep_ana/aluno/schema-prod.json
  bases/br_inep_ana/aluno/schema-staging.json
  bases/br_inep_ana/aluno/table_config.yaml
  bases/br_inep_ana/aluno/table_description.txt
  bases/br_inep_ana/code/[dados] br_inep_ana.ipynb
  bases/br_inep_ana/code/[dados]_br_inep_ana.ipynb
  bases/br_inep_ana/dataset_config.yaml
  bases/br_inep_ana/dicionario/publish.sql
  bases/br_inep_ana/dicionario/schema-prod.json
  bases/br_inep_ana/dicionario/schema-staging.json
  bases/br_inep_ana/dicionario/table_config.yaml
  bases/br_inep_ana/dicionario/table_description.txt
  bases/br_inep_ana/escola/publish.sql
  bases/br_inep_ana/escola/schema-prod.json
  bases/br_inep_ana/escola/schema-staging.json
  bases/br_inep_ana/escola/table_config.yaml
  bases/br_inep_ana/escola/table_description.txt
  bases/br_inep_ana/prova/publish.sql
  bases/br_inep_ana/prova/schema-prod.json
  bases/br_inep_ana/prova/schema-staging.json
  bases/br_inep_ana/prova/table_config.yaml
  bases/br_inep_ana/prova/table_description.txt
Labels: data, data-check-trigger
