Repository basedosdados/sdk, pull requests merged in 2021-12, with the labels that each got.

#925 [dados] br_bd_diretorios_brasil.escola
  bases/br_bd_diretorios_brasil/code/escola.do
  bases/br_bd_diretorios_brasil/code/escolas.R
  bases/br_bd_diretorios_brasil/escola/table_config.yaml
Labels: data, data-check-trigger

#1001 [dados-fix] br_me_rais
  bases/br_me_rais/code/build.do
  bases/br_me_rais/code/sub/estabelecimentos.do
  bases/br_me_rais/code/sub/vinculos.do
  bases/br_me_rais/microdados_estabelecimentos/publish.sql
  bases/br_me_rais/microdados_estabelecimentos/schema-prod.json
  bases/br_me_rais/microdados_estabelecimentos/schema-staging.json
  bases/br_me_rais/microdados_estabelecimentos/table_config.yaml
  bases/br_me_rais/microdados_estabelecimentos/table_description.txt
  bases/br_me_rais/microdados_vinculos/publish.sql
  bases/br_me_rais/microdados_vinculos/schema-prod.json
  bases/br_me_rais/microdados_vinculos/schema-staging.json
  bases/br_me_rais/microdados_vinculos/table_config.yaml
  bases/br_me_rais/microdados_vinculos/table_description.txt
Labels: data

#956 [dados-atualizacao] br_me_rais
  bases/br_me_rais/dicionario/table_config.yaml
Labels: data-check-trigger, data-update

#958 [dados-atualizacao] br_me_comex_stat
  bases/br_me_comex_stat/code/[dados] br_me_comex_stat.ipynb
  bases/br_me_comex_stat/municipio_exportacao/schema-prod.json
  bases/br_me_comex_stat/municipio_exportacao/schema-staging.json
  bases/br_me_comex_stat/municipio_exportacao/table_config.yaml
  bases/br_me_comex_stat/municipio_exportacao/table_description.txt
  bases/br_me_comex_stat/municipio_importacao/schema-prod.json
  bases/br_me_comex_stat/municipio_importacao/schema-staging.json
  bases/br_me_comex_stat/municipio_importacao/table_config.yaml
  bases/br_me_comex_stat/municipio_importacao/table_description.txt
  bases/br_me_comex_stat/ncm_exportacao/schema-prod.json
  bases/br_me_comex_stat/ncm_exportacao/schema-staging.json
  bases/br_me_comex_stat/ncm_exportacao/table_config.yaml
  bases/br_me_comex_stat/ncm_exportacao/table_description.txt
  bases/br_me_comex_stat/ncm_importacao/schema-prod.json
  bases/br_me_comex_stat/ncm_importacao/schema-staging.json
  bases/br_me_comex_stat/ncm_importacao/table_config.yaml
  bases/br_me_comex_stat/ncm_importacao/table_description.txt
Labels: data-check-trigger, data-update

#929 [dados] br_bd_vizinhanca
  bases/br_bd_vizinhanca/README.md
  bases/br_bd_vizinhanca/code/municipio.R
  bases/br_bd_vizinhanca/code/setor_censitario.R
  bases/br_bd_vizinhanca/code/uf.R
  bases/br_bd_vizinhanca/dataset_config.yaml
  bases/br_bd_vizinhanca/municipio/publish.sql
  bases/br_bd_vizinhanca/municipio/schema-prod.json
  bases/br_bd_vizinhanca/municipio/schema-staging.json
  bases/br_bd_vizinhanca/municipio/table_config.yaml
  bases/br_bd_vizinhanca/municipio/table_description.txt
  bases/br_bd_vizinhanca/uf/publish.sql
  bases/br_bd_vizinhanca/uf/schema-prod.json
  bases/br_bd_vizinhanca/uf/schema-staging.json
  bases/br_bd_vizinhanca/uf/table_config.yaml
  bases/br_bd_vizinhanca/uf/table_description.txt
Labels: data, data-check-trigger

#1003 [dados-fix] `br_me_rais`: Update table_config.yaml
  bases/br_me_rais/microdados_vinculos/table_config.yaml
Labels: data

#1014 [dados-atualização] br_ms_vacinacao_covid19
  bases/br_ms_vacinacao_covid19/dicionario/schema-prod.json
  bases/br_ms_vacinacao_covid19/dicionario/schema-staging.json
  bases/br_ms_vacinacao_covid19/dicionario/table_config.yaml
  bases/br_ms_vacinacao_covid19/dicionario/table_description.txt
  bases/br_ms_vacinacao_covid19/microdados/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados/table_description.txt
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_description.txt
  bases/br_ms_vacinacao_covid19/microdados_paciente/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_paciente/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_description.txt
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_description.txt
Labels: data, data-check-trigger

#1023 [dados] `br_tse_eleicoes.despesas_candidato`
  bases/br_tse_eleicoes/code/build.do
  bases/br_tse_eleicoes/code/sub/normalizacao_particao.do
  bases/br_tse_eleicoes/code/sub/prestacao_contas.do
  bases/br_tse_eleicoes/despesas_candidato/publish.sql
  bases/br_tse_eleicoes/despesas_candidato/schema-prod.json
  bases/br_tse_eleicoes/despesas_candidato/schema-staging.json
  bases/br_tse_eleicoes/despesas_candidato/table_config.yaml
  bases/br_tse_eleicoes/despesas_candidato/table_description.txt
Labels: data, data-check-trigger

#1021 [dados] br_inep_saeb.proficiencia
  bases/br_inep_saeb/dicionario/publish.sql
  bases/br_inep_saeb/dicionario/schema-prod.json
  bases/br_inep_saeb/dicionario/schema-staging.json
  bases/br_inep_saeb/dicionario/table_config.yaml
  bases/br_inep_saeb/dicionario/table_description.txt
  bases/br_inep_saeb/proficiencia/publish.sql
  bases/br_inep_saeb/proficiencia/schema-prod.json
  bases/br_inep_saeb/proficiencia/schema-staging.json
  bases/br_inep_saeb/proficiencia/table_config.yaml
  bases/br_inep_saeb/proficiencia/table_description.txt
Labels: data, data-check-trigger

#1019 [dados] br_inep_formacao_docente
  bases/br_inep_formacao_docente/README.md
  bases/br_inep_formacao_docente/brasil/publish.sql
  bases/br_inep_formacao_docente/brasil/schema-prod.json
  bases/br_inep_formacao_docente/brasil/schema-staging.json
  bases/br_inep_formacao_docente/brasil/table_config.yaml
  bases/br_inep_formacao_docente/brasil/table_description.txt
  bases/br_inep_formacao_docente/code/[dados] br_inep_afd.ipynb
  bases/br_inep_formacao_docente/dataset_config.yaml
  bases/br_inep_formacao_docente/dicionario/publish.sql
  bases/br_inep_formacao_docente/dicionario/schema-prod.json
  bases/br_inep_formacao_docente/dicionario/schema-staging.json
  bases/br_inep_formacao_docente/dicionario/table_config.yaml
  bases/br_inep_formacao_docente/dicionario/table_description.txt
  bases/br_inep_formacao_docente/escola/publish.sql
  bases/br_inep_formacao_docente/escola/schema-prod.json
  bases/br_inep_formacao_docente/escola/schema-staging.json
  bases/br_inep_formacao_docente/escola/table_config.yaml
  bases/br_inep_formacao_docente/escola/table_description.txt
  bases/br_inep_formacao_docente/municipio/publish.sql
  bases/br_inep_formacao_docente/municipio/schema-prod.json
  bases/br_inep_formacao_docente/municipio/schema-staging.json
  bases/br_inep_formacao_docente/municipio/table_config.yaml
  bases/br_inep_formacao_docente/municipio/table_description.txt
  bases/br_inep_formacao_docente/regiao/publish.sql
  bases/br_inep_formacao_docente/regiao/schema-prod.json
  bases/br_inep_formacao_docente/regiao/schema-staging.json
  bases/br_inep_formacao_docente/regiao/table_config.yaml
  bases/br_inep_formacao_docente/regiao/table_description.txt
  bases/br_inep_formacao_docente/uf/publish.sql
  bases/br_inep_formacao_docente/uf/schema-prod.json
  bases/br_inep_formacao_docente/uf/schema-staging.json
  bases/br_inep_formacao_docente/uf/table_config.yaml
  bases/br_inep_formacao_docente/uf/table_description.txt
Labels: data, data-check-trigger

#1018 [dados] br_inep_indicador_nivel_socioeconomico
  bases/br_inep_indicador_nivel_socioeconomico/README.md
  bases/br_inep_indicador_nivel_socioeconomico/dataset_config.yaml
  bases/br_inep_indicador_nivel_socioeconomico/dicionario/publish.sql
  bases/br_inep_indicador_nivel_socioeconomico/dicionario/schema-prod.json
  bases/br_inep_indicador_nivel_socioeconomico/dicionario/schema-staging.json
  bases/br_inep_indicador_nivel_socioeconomico/dicionario/table_config.yaml
  bases/br_inep_indicador_nivel_socioeconomico/dicionario/table_description.txt
  bases/br_inep_indicador_nivel_socioeconomico/escola/publish.sql
  bases/br_inep_indicador_nivel_socioeconomico/escola/schema-prod.json
  bases/br_inep_indicador_nivel_socioeconomico/escola/schema-staging.json
  bases/br_inep_indicador_nivel_socioeconomico/escola/table_config.yaml
  bases/br_inep_indicador_nivel_socioeconomico/escola/table_description.txt
  bases/br_inep_indicador_nivel_socioeconomico/municipio/publish.sql
  bases/br_inep_indicador_nivel_socioeconomico/municipio/schema-prod.json
  bases/br_inep_indicador_nivel_socioeconomico/municipio/schema-staging.json
  bases/br_inep_indicador_nivel_socioeconomico/municipio/table_config.yaml
  bases/br_inep_indicador_nivel_socioeconomico/municipio/table_description.txt
  bases/br_inep_indicador_nivel_socioeconomico/uf/publish.sql
  bases/br_inep_indicador_nivel_socioeconomico/uf/schema-prod.json
  bases/br_inep_indicador_nivel_socioeconomico/uf/schema-staging.json
  bases/br_inep_indicador_nivel_socioeconomico/uf/table_config.yaml
  bases/br_inep_indicador_nivel_socioeconomico/uf/table_description.txt
Labels: data, data-check-trigger

#1031 [dados] mundo_bm_learning_poverty
  bases/mundo_bm_learning_poverty/README.md
  bases/mundo_bm_learning_poverty/dataset_config.yaml
  bases/mundo_bm_learning_poverty/pais/publish.sql
  bases/mundo_bm_learning_poverty/pais/schema-prod.json
  bases/mundo_bm_learning_poverty/pais/schema-staging.json
  bases/mundo_bm_learning_poverty/pais/table_config.yaml
  bases/mundo_bm_learning_poverty/pais/table_description.txt
Labels: data, data-check-trigger

#1032 [dados] br_bd_diretorios_mundo.pais
  bases/br_bd_diretorios_mundo/README.md
  bases/br_bd_diretorios_mundo/dataset_config.yaml
  bases/br_bd_diretorios_mundo/pais/publish.sql
  bases/br_bd_diretorios_mundo/pais/schema-prod.json
  bases/br_bd_diretorios_mundo/pais/schema-staging.json
  bases/br_bd_diretorios_mundo/pais/table_config.yaml
  bases/br_bd_diretorios_mundo/pais/table_description.txt
Labels: data

#1034 [dados-atualizacao] add 2020 to RAIS
  bases/br_me_rais/code/sub/estabelecimentos.do
  bases/br_me_rais/code/sub/vinculos.do
Labels: data

#1037 [dados] br_bd_indicadores.contabilidade
  bases/br_bd_indicadores/README.md
  bases/br_bd_indicadores/contabilidade/publish.sql
  bases/br_bd_indicadores/contabilidade/schema-prod.json
  bases/br_bd_indicadores/contabilidade/schema-staging.json
  bases/br_bd_indicadores/contabilidade/table_config.yaml
  bases/br_bd_indicadores/contabilidade/table_config3.yaml
  bases/br_bd_indicadores/contabilidade/table_description.txt
  bases/br_bd_indicadores/dataset_config.yaml
Labels: data, data-check-trigger

#1027 [dados-atualizacao] br_ibge_inflacao
  bases/br_ibge_inpc/mes_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca/mes_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca15/mes_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_rm/table_config.yaml
Labels: data-check-trigger, data-update

#1013 [dados] pnad_populacao
  bases/br_ibge_pnadc/ano_brasil_grupo_idade/publish.sql
  bases/br_ibge_pnadc/ano_brasil_grupo_idade/schema-prod.json
  bases/br_ibge_pnadc/ano_brasil_grupo_idade/schema-staging.json
  bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_description.txt
  bases/br_ibge_pnadc/ano_brasil_raca_cor/publish.sql
  bases/br_ibge_pnadc/ano_brasil_raca_cor/schema-prod.json
  bases/br_ibge_pnadc/ano_brasil_raca_cor/schema-staging.json
  bases/br_ibge_pnadc/ano_brasil_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_brasil_raca_cor/table_description.txt
  bases/br_ibge_pnadc/ano_municipio_grupo_idade/publish.sql
  bases/br_ibge_pnadc/ano_municipio_grupo_idade/schema-prod.json
  bases/br_ibge_pnadc/ano_municipio_grupo_idade/schema-staging.json
  bases/br_ibge_pnadc/ano_municipio_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_municipio_grupo_idade/table_description.txt
  bases/br_ibge_pnadc/ano_municipio_raca_cor/publish.sql
  bases/br_ibge_pnadc/ano_municipio_raca_cor/schema-prod.json
  bases/br_ibge_pnadc/ano_municipio_raca_cor/schema-staging.json
  bases/br_ibge_pnadc/ano_municipio_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_municipio_raca_cor/table_description.txt
  bases/br_ibge_pnadc/ano_regiao_grupo_idade/publish.sql
  bases/br_ibge_pnadc/ano_regiao_grupo_idade/schema-prod.json
  bases/br_ibge_pnadc/ano_regiao_grupo_idade/schema-staging.json
  bases/br_ibge_pnadc/ano_regiao_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_grupo_idade/table_description.txt
  bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/publish.sql
  bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/schema-prod.json
  bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/schema-staging.json
  bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/table_description.txt
  bases/br_ibge_pnadc/ano_regiao_metropolitana_raca_cor/publish.sql
  bases/br_ibge_pnadc/ano_regiao_metropolitana_raca_cor/schema-prod.json
  bases/br_ibge_pnadc/ano_regiao_metropolitana_raca_cor/schema-staging.json
  bases/br_ibge_pnadc/ano_regiao_metropolitana_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_metropolitana_raca_cor/table_description.txt
  bases/br_ibge_pnadc/ano_regiao_raca_cor/publish.sql
  bases/br_ibge_pnadc/ano_regiao_raca_cor/schema-prod.json
  bases/br_ibge_pnadc/ano_regiao_raca_cor/schema-staging.json
  bases/br_ibge_pnadc/ano_regiao_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_raca_cor/table_description.txt
  bases/br_ibge_pnadc/ano_uf_grupo_idade/publish.sql
  bases/br_ibge_pnadc/ano_uf_grupo_idade/schema-prod.json
  bases/br_ibge_pnadc/ano_uf_grupo_idade/schema-staging.json
  bases/br_ibge_pnadc/ano_uf_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_uf_grupo_idade/table_description.txt
  bases/br_ibge_pnadc/ano_uf_raca_cor/publish.sql
  bases/br_ibge_pnadc/ano_uf_raca_cor/schema-prod.json
  bases/br_ibge_pnadc/ano_uf_raca_cor/schema-staging.json
  bases/br_ibge_pnadc/ano_uf_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_uf_raca_cor/table_description.txt
Labels: data, data-check-trigger
