Repository basedosdados/sdk, pull requests merged in 2021-05, with the labels that each got.

#414 [docs] Atualiza documentação com o pacote em R
  .github/workflows/build-docs.yml
  .github/workflows/deploy-docs.yml
  Makefile
  docs/access_data_local.md
  docs/cli_reference_api.md
  docs/reference_api_cli.md
  docs/reference_api_py.md
  docs/reference_api_r.md
  mkdocs.yml
  python-package/basedosdados/__init__.py
  python-package/basedosdados/cli/cli.py
  python-package/basedosdados/download/download.py
  python-package/basedosdados/upload/storage.py
  python-package/basedosdados/upload/table.py
Labels: docs

#412 [dados] Update diretórios de municipio e UF.
  bases/br_bd_diretorios_brasil/municipio/publish.sql
  bases/br_bd_diretorios_brasil/municipio/schema-prod.json
  bases/br_bd_diretorios_brasil/municipio/schema-staging.json
  bases/br_bd_diretorios_brasil/municipio/table_config.yaml
  bases/br_bd_diretorios_brasil/municipio/table_description.txt
  bases/br_bd_diretorios_brasil/uf/publish.sql
  bases/br_bd_diretorios_brasil/uf/schema-prod.json
  bases/br_bd_diretorios_brasil/uf/table_config.yaml
  bases/br_bd_diretorios_brasil/uf/table_description.txt
Labels: data

#421 [dados] Conserta dataset_id de br_ibge_cbo_2002.
  bases/br_ibge_cbo_2002/perfil_ocupacional/schema-prod.json
  bases/br_ibge_cbo_2002/perfil_ocupacional/table_config.yaml
  bases/br_ibge_cbo_2002/sinonimo/table_config.yaml
Labels: data

#423 [dados] Adiciona tabela br_bd_diretorios_data_tempo.data.
  .gitignore
  bases/br_bd_diretorios_data_tempo/data/publish.sql
  bases/br_bd_diretorios_data_tempo/data/schema-prod.json
  bases/br_bd_diretorios_data_tempo/data/schema-staging.json
  bases/br_bd_diretorios_data_tempo/data/table_config.yaml
  bases/br_bd_diretorios_data_tempo/data/table_description.txt
Labels: data

#425 [dados] br_ibge_pam
  bases/br_ibge_pam/code/lavouras_permanentes.R
  bases/br_ibge_pam/code/lavouras_temporarias.R
  bases/br_ibge_pam/code/nova_lavouras_temporarias.R
  bases/br_ibge_pam/code/permanentes_usando_api.R
  bases/br_ibge_pam/code/temporarias_usando_api.ipynb
  bases/br_ibge_pam/dataset_config.yaml
  bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
  bases/br_ibge_pam/municipio_lavouras_permanentes/schema-prod.json
  bases/br_ibge_pam/municipio_lavouras_permanentes/schema-staging.json
  bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
  bases/br_ibge_pam/municipio_lavouras_permanentes/table_description.txt
  bases/br_ibge_pam/municipio_lavouras_temporarias/.Rhistory
  bases/br_ibge_pam/municipio_lavouras_temporarias/publish.sql
  bases/br_ibge_pam/municipio_lavouras_temporarias/schema-prod.json
  bases/br_ibge_pam/municipio_lavouras_temporarias/schema-staging.json
  bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
  bases/br_ibge_pam/municipio_lavouras_temporarias/table_description.txt
Labels: data

#415 [infra] R package 0.1.0
  .gitignore
  r-package/DESCRIPTION
  r-package/NAMESPACE
  r-package/R/billing.R
  r-package/R/partition.R
  r-package/R/zzzz.R
  r-package/man/partition_table.Rd
  r-package/man/set_billing_id.Rd
  r-package/tests/testthat/test-download.R
  r-package/tests/testthat/test-partition.R
Labels: R, enhancement

#402 [infra] adds dataset update in the pipeline
  .github/workflows/table-approve/Dockerfile
  .github/workflows/table-approve/main.py
  bases/br_ibge_censo_demografico/setor_censitario_registro_civil_2010/table_config.yaml
Labels: enhancement, infra

#432 [dados] br_ms_vacinacao_covid19
  bases/br_ms_vacinacao_covid19/README.md
  bases/br_ms_vacinacao_covid19/code/build.do
  bases/br_ms_vacinacao_covid19/dataset_config.yaml
  bases/br_ms_vacinacao_covid19/dicionario/publish.sql
  bases/br_ms_vacinacao_covid19/dicionario/schema-prod.json
  bases/br_ms_vacinacao_covid19/dicionario/schema-staging.json
  bases/br_ms_vacinacao_covid19/dicionario/table_config.yaml
  bases/br_ms_vacinacao_covid19/dicionario/table_description.txt
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/publish.sql
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_description.txt
  bases/br_ms_vacinacao_covid19/microdados_paciente/publish.sql
  bases/br_ms_vacinacao_covid19/microdados_paciente/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_paciente/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_description.txt
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/publish.sql
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/schema-staging.json
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_description.txt
Labels: data

#436 [infra] fix path to first time configuration
  python-package/basedosdados/upload/base.py
Labels: bug

#435 [docs] Move exemplos para o repo `analises`
  README.md
  examples/bd_for_beginners.ipynb
  examples/bd_odd_2021.ipynb
Labels: R, docs

#440 [dados] Muda tipo de `dose` para `INT64`.
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/publish.sql
Labels: data

#442 [dados] br_ms_vacinacao_covid19
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/schema-prod.json
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
Labels: data

#453 [infra] fix cli path
  python-package/pyproject.toml
  python-package/setup.py
Labels: bug

#409 [dados] br_denatran_frota
  bases/br_denatran_frota/README.md
  bases/br_denatran_frota/code/download_frota.R
  bases/br_denatran_frota/code/download_frota_old.R
  bases/br_denatran_frota/code/frota_municipio_tipo.R
  bases/br_denatran_frota/code/frota_uf_tipo.R
  bases/br_denatran_frota/code/utils.R
  bases/br_denatran_frota/dataset_config.yaml
  bases/br_denatran_frota/municipio_tipo/publish.sql
  bases/br_denatran_frota/municipio_tipo/schema-prod.json
  bases/br_denatran_frota/municipio_tipo/schema-staging.json
  bases/br_denatran_frota/municipio_tipo/table_config.yaml
  bases/br_denatran_frota/municipio_tipo/table_description.txt
  bases/br_denatran_frota/uf_tipo/publish.sql
  bases/br_denatran_frota/uf_tipo/schema-prod.json
  bases/br_denatran_frota/uf_tipo/table_config.yaml
  bases/br_denatran_frota/uf_tipo/table_description.txt
Labels: data

#467 [docs] Adiciona chave ano no exemplo de R.
  docs/access_data_local.md
Labels: docs

#358 [dados] br_inep_censo_escolar
  bases/br_inep_censo_escolar/README.md
  bases/br_inep_censo_escolar/code/ajuda-arq.R
  bases/br_inep_censo_escolar/code/codigo_docente/docente-2015a17.do
  bases/br_inep_censo_escolar/code/codigo_docente/docentes-2009-2014.do
  bases/br_inep_censo_escolar/code/codigo_matricula/anos_recentes.do
  bases/br_inep_censo_escolar/code/codigo_matricula/antigas_matriculas.do
  bases/br_inep_censo_escolar/code/codigo_matricula/caso_2018.do
  bases/br_inep_censo_escolar/code/codigo_matricula/corrigindo_ultimosanos.do
  bases/br_inep_censo_escolar/code/codigo_turma/turmas-antigo.do
  bases/br_inep_censo_escolar/code/codigo_turma/turmas-finais.do
  bases/br_inep_censo_escolar/code/codigo_turma/turmas-intermediario.do
  bases/br_inep_censo_escolar/dataset_config.yaml
  bases/br_inep_censo_escolar/docente/publish.sql
  bases/br_inep_censo_escolar/docente/schema-prod.json
  bases/br_inep_censo_escolar/docente/schema-staging.json
  bases/br_inep_censo_escolar/docente/table_config.yaml
  bases/br_inep_censo_escolar/docente/table_description.txt
  bases/br_inep_censo_escolar/escola/publish.sql
  bases/br_inep_censo_escolar/escola/schema-prod.json
  bases/br_inep_censo_escolar/escola/schema-staging.json
  bases/br_inep_censo_escolar/escola/table_config.yaml
  bases/br_inep_censo_escolar/escola/table_description.txt
  bases/br_inep_censo_escolar/matricula/publish.sql
  bases/br_inep_censo_escolar/matricula/schema-prod.json
  bases/br_inep_censo_escolar/matricula/schema-staging.json
  bases/br_inep_censo_escolar/matricula/table_config.yaml
  bases/br_inep_censo_escolar/matricula/table_description.txt
  bases/br_inep_censo_escolar/turma/publish.sql
  bases/br_inep_censo_escolar/turma/schema-prod.json
  bases/br_inep_censo_escolar/turma/schema-staging.json
  bases/br_inep_censo_escolar/turma/table_config.yaml
  bases/br_inep_censo_escolar/turma/table_description.txt
Labels: data

#473 [dados] br_inep_censo_escolar | corrigindo nomes no dev staging de escola e docente
  bases/br_inep_censo_escolar/docente/publish.sql
  bases/br_inep_censo_escolar/docente/schema-staging.json
  bases/br_inep_censo_escolar/escola/publish.sql
  bases/br_inep_censo_escolar/escola/schema-staging.json
Labels: data
