Repository basedosdados/sdk, pull requests merged in 2021-03, with the labels that each got.

#308 [dados] br_ibge_ppm
  bases/br_ibge_ppm/producao_aquicultura/publish.sql
  bases/br_ibge_ppm/producao_aquicultura/table_config.yaml
Labels: data

#206 [dados] br_cgu_servidores_executivo_federal
  bases/br_cgu_servidores_executivo_federal/code/README.md
  bases/br_cgu_servidores_executivo_federal/code/requirements.txt
  bases/br_cgu_servidores_executivo_federal/code/servidores.py
Labels: ETL code

#316 [dados] br_inep_indicadores_educacionais
  bases/br_inep_indicadores_educacionais/municipio/schema-prod.json
  bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
Labels: data

#293 [dados] br_sp_seduc
  bases/br_sp_seduc/README.md
  bases/br_sp_seduc/code/idesp.R
  bases/br_sp_seduc/dataset_config.yaml
  bases/br_sp_seduc/idesp_escolas/publish.sql
  bases/br_sp_seduc/idesp_escolas/schema-prod.json
  bases/br_sp_seduc/idesp_escolas/schema-staging.json
  bases/br_sp_seduc/idesp_escolas/table_config.yaml
  bases/br_sp_seduc/idesp_escolas/table_description.txt
Labels: data

#291 [infra] Add metadata functions to CLI
  basedosdados/cli.py
  docs/cli_reference_api.md
Labels: enhancement, infra

#319 [dados] br_ms_sim
  bases/br_ms_sim/code/build.do
  bases/br_ms_sim/code/sub/agregacao.do
  bases/br_ms_sim/code/sub/dbc2csv.R
  bases/br_ms_sim/code/sub/microdados.do
  bases/br_ms_sim/code/sub/normalizacao_particao.do
  bases/br_ms_sim/microdados/publish.sql
  bases/br_ms_sim/microdados/schema-prod.json
  bases/br_ms_sim/microdados/table_config.yaml
  bases/br_ms_sim/microdados/table_description.txt
  bases/br_ms_sim/municipio/publish.sql
  bases/br_ms_sim/municipio/schema-prod.json
  bases/br_ms_sim/municipio/table_config.yaml
  bases/br_ms_sim/municipio/table_description.txt
  bases/br_ms_sim/municipio_causa/publish.sql
  bases/br_ms_sim/municipio_causa/schema-prod.json
  bases/br_ms_sim/municipio_causa/schema-staging.json
  bases/br_ms_sim/municipio_causa/table_config.yaml
  bases/br_ms_sim/municipio_causa/table_description.txt
  bases/br_ms_sim/municipio_causa_idade/publish.sql
  bases/br_ms_sim/municipio_causa_idade/schema-prod.json
  bases/br_ms_sim/municipio_causa_idade/schema-staging.json
  bases/br_ms_sim/municipio_causa_idade/table_config.yaml
  bases/br_ms_sim/municipio_causa_idade/table_description.txt
  bases/br_ms_sim/municipio_causa_idade_genero_raca/publish.sql
  bases/br_ms_sim/municipio_causa_idade_genero_raca/schema-prod.json
  bases/br_ms_sim/municipio_causa_idade_genero_raca/table_config.yaml
  bases/br_ms_sim/municipio_causa_idade_genero_raca/table_description.txt
Labels: data

#305 [infra] In function publish, forced query to complete before updating table
  basedosdados/table.py
Labels: bug, infra

#317 [dados] br_seeg_emissoes
  bases/br_seeg_emissoes/README.md
  bases/br_seeg_emissoes/brasil/publish.sql
  bases/br_seeg_emissoes/brasil/schema-prod.json
  bases/br_seeg_emissoes/brasil/schema-staging.json
  bases/br_seeg_emissoes/brasil/table_config.yaml
  bases/br_seeg_emissoes/brasil/table_description.txt
  bases/br_seeg_emissoes/code/build.do
  bases/br_seeg_emissoes/dataset_config.yaml
  bases/br_seeg_emissoes/municipio/publish.sql
  bases/br_seeg_emissoes/municipio/schema-prod.json
  bases/br_seeg_emissoes/municipio/schema-staging.json
  bases/br_seeg_emissoes/municipio/table_config.yaml
  bases/br_seeg_emissoes/municipio/table_description.txt
  bases/br_seeg_emissoes/uf/publish.sql
  bases/br_seeg_emissoes/uf/schema-prod.json
  bases/br_seeg_emissoes/uf/schema-staging.json
  bases/br_seeg_emissoes/uf/table_config.yaml
  bases/br_seeg_emissoes/uf/table_description.txt
Labels: data

#321 [dados] br_sp_gov_ssp | padronização colunas
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_atividade_policial_MODELO.csv
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_atividade_policial_MODELO_FINAL.csv
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_ocorrecencias_registradas_MODELO.csv
  bases/br_sp_gov_ssp/code/dados/model_data/ssp_ocorrecencias_registradas_MODELO_FINAL.csv
  bases/br_sp_gov_ssp/code/dados/ssp_atividade_policial/ano=2020/deleted.txt
  bases/br_sp_gov_ssp/code/dados/ssp_ocorrecencias_registradas/ano=2020/deleted.txt
  bases/br_sp_gov_ssp/code/dados/utils/ssp_codigo_ibge.csv
  bases/br_sp_gov_ssp/code/scripts/ssp_scrapy.py
  bases/br_sp_gov_ssp/ocorrecencias_registradas/publish.sql
  bases/br_sp_gov_ssp/ocorrecencias_registradas/schema-prod.json
  bases/br_sp_gov_ssp/ocorrecencias_registradas/schema-staging.json
  bases/br_sp_gov_ssp/ocorrecencias_registradas/table_config.yaml
  bases/br_sp_gov_ssp/ocorrecencias_registradas/table_description.txt
  bases/br_sp_gov_ssp/produtividade_policial/publish.sql
  bases/br_sp_gov_ssp/produtividade_policial/schema-prod.json
  bases/br_sp_gov_ssp/produtividade_policial/schema-staging.json
  bases/br_sp_gov_ssp/produtividade_policial/table_config.yaml
  bases/br_sp_gov_ssp/produtividade_policial/table_description.txt
Labels: data

#290 [infra] Testes
  basedosdados/base.py
  basedosdados/dataset.py
  basedosdados/storage.py
  basedosdados/table.py
  tests/sample_data/table/publish.sql
  tests/sample_data/table/publish_part.sql
  tests/sample_data/table/table_config.yaml
  tests/sample_data/table/table_config_part.yaml
  tests/test_download.py
  tests/test_storage.py
  tests/test_table.py
Labels: infra

#336 [docs] Add analises vencedoras Datathon
  docs/datathon_2021.md
  mkdocs.yml
Labels: docs

#332 [dados] br_ba_feiradesantana_camara_leis
  bases/br_ba_feiradesantana_camara_leis/README.md
  bases/br_ba_feiradesantana_camara_leis/code/prepare.py
  bases/br_ba_feiradesantana_camara_leis/dataset_config.yaml
  bases/br_ba_feiradesantana_camara_leis/microdados/publish.sql
  bases/br_ba_feiradesantana_camara_leis/microdados/schema-prod.json
  bases/br_ba_feiradesantana_camara_leis/microdados/schema-staging.json
  bases/br_ba_feiradesantana_camara_leis/microdados/table_config.yaml
  bases/br_ba_feiradesantana_camara_leis/microdados/table_description.txt
Labels: data

#289 [infra] Cliente de R, primeira versão
  .gitignore
  basedosdados_0.0.3.tar.gz
  r-package/.Rbuildignore
  r-package/.Rhistory
  r-package/.gitignore
  r-package/DESCRIPTION
  r-package/LICENSE
  r-package/LICENSE.md
  r-package/NAMESPACE
  r-package/R/billing.R
  r-package/R/download.R
  r-package/R/query_table.R
  r-package/R/zzzz.R
  r-package/basedosdados.Rproj
  r-package/basedosdados_0.0.3.tar.gz
  r-package/man/download.Rd
  r-package/man/get_billing_id.Rd
  r-package/man/query_table.Rd
  r-package/man/read_sql.Rd
  r-package/man/set_billing_id.Rd
  r-package/tests/testthat/test-download.R
Labels: enhancement

#353 [dados] Atualiza tabela candidatos.
  bases/br_tse_eleicoes/candidatos/table_config.yaml
  bases/br_tse_eleicoes/code/sub/candidatos.do
  bases/br_tse_eleicoes/code/sub/normalizacao_particao.do
Labels: data

#342 [dados] br_sp_seduc_inse
  bases/br_sp_seduc_inse/README.md
  bases/br_sp_seduc_inse/code/inse.R
  bases/br_sp_seduc_inse/dataset_config.yaml
  bases/br_sp_seduc_inse/escola/publish.sql
  bases/br_sp_seduc_inse/escola/schema-prod.json
  bases/br_sp_seduc_inse/escola/schema-staging.json
  bases/br_sp_seduc_inse/escola/table_config.yaml
  bases/br_sp_seduc_inse/escola/table_description.txt
Labels: data

#354 [dados] br_inep_indicadores_educacionais
  bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
Labels: data

#335 [dados] br_ibge_pam
  bases/br_ibge_pam/README.md
  bases/br_ibge_pam/code/nova_lavouras_temporarias.R
  bases/br_ibge_pam/dataset_config.yaml
  bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
  bases/br_ibge_pam/municipio_lavouras_permanentes/schema-prod.json
  bases/br_ibge_pam/municipio_lavouras_permanentes/schema-staging.json
  bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
  bases/br_ibge_pam/municipio_lavouras_permanentes/table_description.txt
  bases/br_ibge_pam/municipio_lavouras_temporarias/.Rhistory
  bases/br_ibge_pam/municipio_lavouras_temporarias/publish.sql
  bases/br_ibge_pam/municipio_lavouras_temporarias/schema-prod.json
  bases/br_ibge_pam/municipio_lavouras_temporarias/schema-staging.json
  bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
  bases/br_ibge_pam/municipio_lavouras_temporarias/table_description.txt
Labels: data

#357 [dados] br_ibge_pam
  bases/br_ibge_pam/code/lavouras_permanentes.R
  bases/br_ibge_pam/code/lavouras_temporarias.R
  bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
  bases/br_ibge_pam/municipio_lavouras_permanentes/schema-staging.json
  bases/br_ibge_pam/municipio_lavouras_temporarias/publish.sql
  bases/br_ibge_pam/municipio_lavouras_temporarias/schema-staging.json
  bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
Labels: data

#338 [dados] br_sp_seduc_fluxo_escolar
  bases/br_sp_seduc_fluxo_escolar/README.md
  bases/br_sp_seduc_fluxo_escolar/code/fluxoescolar-escolas.R
  bases/br_sp_seduc_fluxo_escolar/code/fluxoescolar.R
  bases/br_sp_seduc_fluxo_escolar/dataset_config.yaml
  bases/br_sp_seduc_fluxo_escolar/escola/publish.sql
  bases/br_sp_seduc_fluxo_escolar/escola/schema-prod.json
  bases/br_sp_seduc_fluxo_escolar/escola/schema-staging.json
  bases/br_sp_seduc_fluxo_escolar/escola/table_config.yaml
  bases/br_sp_seduc_fluxo_escolar/escola/table_description.txt
  bases/br_sp_seduc_fluxo_escolar/municipio/publish.sql
  bases/br_sp_seduc_fluxo_escolar/municipio/schema-prod.json
  bases/br_sp_seduc_fluxo_escolar/municipio/schema-staging.json
  bases/br_sp_seduc_fluxo_escolar/municipio/table_config.yaml
  bases/br_sp_seduc_fluxo_escolar/municipio/table_description.txt
Labels: data

#341 [dados] br_sp_seduc_idesp
  bases/br_sp_seduc_idesp/README.md
  bases/br_sp_seduc_idesp/code/idesp-diretoria.R
  bases/br_sp_seduc_idesp/code/idesp-estado.R
  bases/br_sp_seduc_idesp/code/idesp.R
  bases/br_sp_seduc_idesp/dataset_config.yaml
  bases/br_sp_seduc_idesp/diretoria/publish.sql
  bases/br_sp_seduc_idesp/diretoria/schema-prod.json
  bases/br_sp_seduc_idesp/diretoria/schema-staging.json
  bases/br_sp_seduc_idesp/diretoria/table_config.yaml
  bases/br_sp_seduc_idesp/diretoria/table_description.txt
  bases/br_sp_seduc_idesp/escola/publish.sql
  bases/br_sp_seduc_idesp/escola/schema-prod.json
  bases/br_sp_seduc_idesp/escola/schema-staging.json
  bases/br_sp_seduc_idesp/escola/table_config.yaml
  bases/br_sp_seduc_idesp/escola/table_description.txt
  bases/br_sp_seduc_idesp/uf/publish.sql
  bases/br_sp_seduc_idesp/uf/schema-prod.json
  bases/br_sp_seduc_idesp/uf/schema-staging.json
  bases/br_sp_seduc_idesp/uf/table_config.yaml
  bases/br_sp_seduc_idesp/uf/table_description.txt
Labels: data

#277 [dados] br_ibge_censo_demografico
  bases/br_ibge_censo_demografico/README.md
  bases/br_ibge_censo_demografico/code/build.do
  bases/br_ibge_censo_demografico/dataset_config.yaml
  bases/br_ibge_censo_demografico/microdados_domicilio_1970/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_1970/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1970/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1970/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_domicilio_1970/table_description.txt
  bases/br_ibge_censo_demografico/microdados_domicilio_1980/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_1980/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1980/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1980/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_domicilio_1980/table_description.txt
  bases/br_ibge_censo_demografico/microdados_domicilio_1991/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_1991/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1991/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_domicilio_1991/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_domicilio_1991/table_description.txt
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/table_description.txt
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/table_description.txt
  bases/br_ibge_censo_demografico/microdados_pessoa_1970/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_1970/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1970/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1970/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_pessoa_1970/table_description.txt
  bases/br_ibge_censo_demografico/microdados_pessoa_1980/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_1980/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1980/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1980/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_pessoa_1980/table_description.txt
  bases/br_ibge_censo_demografico/microdados_pessoa_1991/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_1991/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1991/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_pessoa_1991/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_pessoa_1991/table_description.txt
  bases/br_ibge_censo_demografico/microdados_pessoa_2000/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_2000/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2000/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_description.txt
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/schema-staging.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/table_description.txt
  docs/images/bd_logo.png
Labels: data

#369 Conserta microdados censo demográfico.
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2000/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/table_config.yaml
Labels: data

#370 [dados] Conserta tabelas Censo microdados 2010.
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_domicilio_2010/table_config.yaml
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/publish.sql
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/schema-prod.json
  bases/br_ibge_censo_demografico/microdados_pessoa_2010/table_config.yaml
Labels: data

#367 [infra] fix issues for v1.5
  python-package/basedosdados/datatypes.py
  python-package/basedosdados/download.py
  python-package/basedosdados/table.py
  python-package/tests/sample_data/table/table_config_part_wrong.yaml
  python-package/tests/test_table.py
  python-package/tests/tmp_bases/pytest/README.md
  python-package/tests/tmp_bases/pytest/dataset_config.yaml
  python-package/tests/tmp_bases/pytest/pytest/publish.sql
  python-package/tests/tmp_bases/pytest/pytest/schema-prod.json
  python-package/tests/tmp_bases/pytest/pytest/schema-staging.json
  python-package/tests/tmp_bases/pytest/pytest/table_config.yaml
  python-package/tests/tmp_bases/pytest/pytest/table_description.txt
  python-package/tests/tmp_bases/pytest/pytest_partitioned/publish.sql
  python-package/tests/tmp_bases/pytest/pytest_partitioned/schema-prod.json
  python-package/tests/tmp_bases/pytest/pytest_partitioned/schema-staging.json
  python-package/tests/tmp_bases/pytest/pytest_partitioned/table_description.txt
Labels: infra

#372 [dados] Brasileirão Série A
  bases/mundo_transfermarkt_competicoes/README.md
  bases/mundo_transfermarkt_competicoes/brasileirao_serie_a/publish.sql
  bases/mundo_transfermarkt_competicoes/brasileirao_serie_a/schema-prod.json
  bases/mundo_transfermarkt_competicoes/brasileirao_serie_a/schema-staging.json
  bases/mundo_transfermarkt_competicoes/brasileirao_serie_a/table_config.yaml
  bases/mundo_transfermarkt_competicoes/brasileirao_serie_a/table_description.txt
  bases/mundo_transfermarkt_competicoes/code/build.do
  bases/mundo_transfermarkt_competicoes/code/scraping_transfermarkt_brasileirao_serie_a_2003-2006.py
  bases/mundo_transfermarkt_competicoes/code/scraping_transfermarkt_brasileirao_serie_a_2007-2020.py
  bases/mundo_transfermarkt_competicoes/dataset_config.yaml
Labels: data
