Repository basedosdados/sdk, pull requests merged in 2022-01, with the labels that each got.

#1039 [dados-atualizacao] br_ms_populacao
  bases/br_ms_populacao/municipio/publish.sql
  bases/br_ms_populacao/municipio/schema-staging.json
  bases/br_ms_populacao/municipio/table_config.yaml
Labels: data-check-trigger, data-update

#1036 [docs] Revisão da documentação
  README.md
  docs/access_data_bq.md
  docs/access_data_packages.md
  docs/api_reference_cli.md
  docs/api_reference_python.md
  docs/api_reference_r.md
  docs/archive/colab.md
  docs/colab_data.md
  docs/colab_infrastructure.md
  docs/index.md
  docs/reference_api_cli.md
  docs/style_data.md
  mkdocs.yml
Labels: docs

#1026 [infra] Cria bypass de memória como comportamento padrão para download (#902)
  python-package/basedosdados/__init__.py
  python-package/basedosdados/cli/cli.py
  python-package/basedosdados/download/base.py
  python-package/basedosdados/download/download.py
  python-package/basedosdados/download/metadata.py
  python-package/pyproject.toml
  python-package/tests/test_download/test_download.py
  python-package/tests/test_download/test_metadata.py
Labels: python

#1041 [dados-atualizacao] br_inep_saeb
  bases/br_inep_saeb/README.md
  bases/br_inep_saeb/dataset_config.yml
  bases/br_inep_saeb/dicionario/table_config.yaml
  bases/br_inep_saeb/dicionario/table_description.txt
Labels: data-check-trigger, data-update

#1048 [dados] br_ibge_pnad.populacao
  bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_brasil_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_municipio_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_municipio_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_metropolitana_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_regiao_raca_cor/table_config.yaml
  bases/br_ibge_pnadc/ano_uf_grupo_idade/table_config.yaml
  bases/br_ibge_pnadc/ano_uf_raca_cor/table_config.yaml
Labels: data

#1053 [dados] br_ibge_pib.municipio
  bases/br_ibge_pib/code/build.do
  bases/br_ibge_pib/municipio/publish.sql
  bases/br_ibge_pib/municipio/schema-prod.json
  bases/br_ibge_pib/municipio/schema-staging.json
  bases/br_ibge_pib/municipio/table_config.yaml
  bases/br_ibge_pib/municipio/table_description.txt
Labels: data, data-check-trigger

#959 [dados] br_ibge_pnad
  bases/br_ibge_pnad/README.md
  bases/br_ibge_pnad/code/br_ibge_pnad.py
  bases/br_ibge_pnad/dataset_config.yaml
  bases/br_ibge_pnad/dicionario/publish.sql
  bases/br_ibge_pnad/dicionario/schema-prod.json
  bases/br_ibge_pnad/dicionario/schema-staging.json
  bases/br_ibge_pnad/dicionario/table_config.yaml
  bases/br_ibge_pnad/dicionario/table_description.txt
  bases/br_ibge_pnad/microdados_compatibilizado_datazoom/publish.sql
  bases/br_ibge_pnad/microdados_compatibilizado_datazoom/schema-prod.json
  bases/br_ibge_pnad/microdados_compatibilizado_datazoom/schema-staging.json
  bases/br_ibge_pnad/microdados_compatibilizado_datazoom/table_config.yaml
  bases/br_ibge_pnad/microdados_compatibilizado_datazoom/table_description.txt
Labels: data

#1056 [dados] atualizacao br_ibge_inflação
  bases/br_ibge_inpc/mes_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca/mes_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca15/mes_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_rm/table_config.yaml
Labels: data, data-check-trigger

#1065 [dados-bot] br_ms_vacinacao_covid19 (2022-01-15)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data-update

#1068 fix(data): updates and re-publishes metadata
  bases/br_ms_sinan/dataset_config.yaml
  bases/br_ms_sinan/dicionario/table_config.yaml
  bases/br_ms_sinan/microdados_violencia/table_config.yaml
Labels: data

#1073 [atualiza-dados] br_ibge_ipca
  bases/br_ibge_ipca/mes_brasil/schema-prod.json
  bases/br_ibge_ipca/mes_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_brasil/table_description.txt
  bases/br_ibge_ipca/mes_categoria_brasil/schema-prod.json
  bases/br_ibge_ipca/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_brasil/table_description.txt
  bases/br_ibge_ipca/mes_categoria_municipio/schema-prod.json
  bases/br_ibge_ipca/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_municipio/table_description.txt
  bases/br_ibge_ipca/mes_categoria_rm/schema-prod.json
  bases/br_ibge_ipca/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_rm/table_description.txt
Labels: data, data-check-trigger

#1076 [atualiza-dados] br_ibge_inpc
  bases/br_ibge_inpc/mes_brasil/schema-prod.json
  bases/br_ibge_inpc/mes_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_brasil/table_description.txt
  bases/br_ibge_inpc/mes_categoria_brasil/schema-prod.json
  bases/br_ibge_inpc/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_brasil/table_description.txt
  bases/br_ibge_inpc/mes_categoria_municipio/schema-prod.json
  bases/br_ibge_inpc/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_municipio/table_description.txt
  bases/br_ibge_inpc/mes_categoria_rm/schema-prod.json
  bases/br_ibge_inpc/mes_categoria_rm/table_config.yaml
  bases/br_ibge_inpc/mes_categoria_rm/table_description.txt
Labels: data, data-check-trigger

#1077 [atualiza-dados] br_ibge_ipca15
  bases/br_ibge_ipca15/mes_brasil/schema-prod.json
  bases/br_ibge_ipca15/mes_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_brasil/table_description.txt
  bases/br_ibge_ipca15/mes_categoria_brasil/schema-prod.json
  bases/br_ibge_ipca15/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_brasil/table_description.txt
  bases/br_ibge_ipca15/mes_categoria_municipio/schema-prod.json
  bases/br_ibge_ipca15/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_municipio/table_description.txt
  bases/br_ibge_ipca15/mes_categoria_rm/schema-prod.json
  bases/br_ibge_ipca15/mes_categoria_rm/table_config.yaml
  bases/br_ibge_ipca15/mes_categoria_rm/table_description.txt
Labels: data, data-check-trigger

#1052 [dados] br_ana_reservatorios
  bases/br_ana_reservatorios/README.md
  bases/br_ana_reservatorios/code/br_ana_reservatorio.R
  bases/br_ana_reservatorios/dataset_config.yaml
  bases/br_ana_reservatorios/sin/publish.sql
  bases/br_ana_reservatorios/sin/schema-prod.json
  bases/br_ana_reservatorios/sin/schema-staging.json
  bases/br_ana_reservatorios/sin/table_config.yaml
  bases/br_ana_reservatorios/sin/table_description.txt
Labels: data, data-check-trigger

#1086 [dados-bot] br_ms_vacinacao_covid19 (2022-01-23)
  bases/br_ms_vacinacao_covid19/microdados/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml
  bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Labels: data

#1087 [dados] br_bd_diretorios_brasil.etnia_indigena
  bases/br_bd_diretorios_brasil/dataset_config.yaml
  bases/br_bd_diretorios_brasil/etnia_indigena/publish.sql
  bases/br_bd_diretorios_brasil/etnia_indigena/schema-prod.json
  bases/br_bd_diretorios_brasil/etnia_indigena/schema-staging.json
  bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
  bases/br_bd_diretorios_brasil/etnia_indigena/table_description.txt
Labels: data, data-check-trigger
