Repository basedosdados/sdk, pull requests merged in 2022-07, with the labels that each got.

#1188 [infra] Python 1.6.4
  .github/workflows/data-check.yml
  .github/workflows/metadata-validate.yml
  .github/workflows/table-approve.yml
  python-package/basedosdados/cli/cli.py
  python-package/basedosdados/upload/dataset.py
  python-package/basedosdados/upload/metadata.py
  python-package/basedosdados/upload/storage.py
  python-package/basedosdados/upload/table.py
  python-package/pyproject.toml
Labels: infra

#1266 [dados-atualizacao] `br_bd_diretorios_brasil.natureza_juridica`
  bases/br_bd_diretorios_brasil/natureza_juridica/publish.sql
  bases/br_bd_diretorios_brasil/natureza_juridica/schema-prod.json
  bases/br_bd_diretorios_brasil/natureza_juridica/schema-staging.json
  bases/br_bd_diretorios_brasil/natureza_juridica/table_config.yaml
  bases/br_bd_diretorios_brasil/natureza_juridica/table_description.txt
Labels: data-update

#1262 [dados-atualizacao] `br_me_caged`
  bases/br_me_caged/microdados_movimentacao/table_config.yaml
  bases/br_me_caged/microdados_movimentacao_excluida/table_config.yaml
  bases/br_me_caged/microdados_movimentacao_fora_prazo/table_config.yaml
Labels: data, data-update, data-quality

#1264 [dados] `br_geobr_mapas.saude`
  bases/br_geobr_mapas/code/saude.ipynb
  bases/br_geobr_mapas/saude/publish.sql
  bases/br_geobr_mapas/saude/schema-prod.json
  bases/br_geobr_mapas/saude/schema-staging.json
  bases/br_geobr_mapas/saude/table_config.yaml
  bases/br_geobr_mapas/saude/table_description.txt
Labels: data
