Repository basedosdados/sdk, pull requests merged in 2022-10, with the labels that each got.

#1342 [doc] access_data_md update
  docs/access_data_bq.md
  docs/images/bq_access_project_new.gif
Labels: docs

#1281 [dados-atualizacao] br_ibge_ipca
  bases/br_ibge_ipca/dataset_config.yaml
  bases/br_ibge_ipca/mes_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_brasil/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_municipio/table_config.yaml
  bases/br_ibge_ipca/mes_categoria_rm/table_config.yaml
Labels: data, data-quality

#1349 [dados] [correcao] br_geobr_mapas.mesorregiao
  bases/br_geobr_mapas/mesorregiao/schema-prod.json
  bases/br_geobr_mapas/mesorregiao/schema-staging.json
  bases/br_geobr_mapas/mesorregiao/table_config.yaml
Labels: data-update

#1310 [dados-atualizacao] `br_ibge_nomes_brasil`
  bases/br_ibge_nomes_brasil/dataset_config.yaml
  bases/br_ibge_nomes_brasil/quantidade_municipio_nome_2010/table_config.yaml
Labels: data, data-quality

#1309 [dados-atualizacao] `br_me_rais`
  bases/br_me_rais/dataset_config.yaml
  bases/br_me_rais/microdados_estabelecimentos/table_config.yaml
  bases/br_me_rais/microdados_vinculos/table_config.yaml
Labels: data, data-quality

#1326 [doc] update style_data.md
  docs/style_data.md
Labels: docs

#1361 [dados-atualizacao] br_inep_saeb.uf
  bases/br_inep_saeb/uf/table_config.yaml
Labels: data-update

#1352 [dados-correcao] br_geobr_mapas.regiao_intermediaria
  bases/br_geobr_mapas/regiao_intermediaria/table_config.yaml
Labels: data-update

#1351 [dados-correcao] br_geobr_mapas.regiao_imediata
  bases/br_geobr_mapas/regiao_imediata/table_config.yaml
Labels: data-update

#1360 Update style_data.md
  docs/style_data.md
Labels: data

#1364 [dados] fix: fixes types and publishes all metadata
  bases/br_tse_eleicoes/bens_candidato/table_config.yaml
  bases/br_tse_eleicoes/candidatos/table_config.yaml
  bases/br_tse_eleicoes/despesas_candidato/table_config.yaml
  bases/br_tse_eleicoes/detalhes_votacao_municipio/table_config.yaml
  bases/br_tse_eleicoes/detalhes_votacao_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/detalhes_votacao_secao/table_config.yaml
  bases/br_tse_eleicoes/partidos/table_config.yaml
  bases/br_tse_eleicoes/perfil_eleitorado_local_votacao/table_config.yaml
  bases/br_tse_eleicoes/perfil_eleitorado_municipio_zona/publish.sql
  bases/br_tse_eleicoes/perfil_eleitorado_municipio_zona/schema-prod.json
  bases/br_tse_eleicoes/perfil_eleitorado_municipio_zona/schema-staging.json
  bases/br_tse_eleicoes/perfil_eleitorado_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/perfil_eleitorado_secao/table_config.yaml
  bases/br_tse_eleicoes/receitas_candidato/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato/publish.sql
  bases/br_tse_eleicoes/resultados_candidato/schema-prod.json
  bases/br_tse_eleicoes/resultados_candidato/schema-staging.json
  bases/br_tse_eleicoes/resultados_candidato/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_municipio/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/resultados_candidato_secao/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_municipio/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_municipio_zona/table_config.yaml
  bases/br_tse_eleicoes/resultados_partido_secao/table_config.yaml
  bases/br_tse_eleicoes/vagas/table_config.yaml
Labels: data

#1366 [dados] world_fifa_womens_world_cup
  bases/world_fifa_women_world_cup/README.md
  bases/world_fifa_women_world_cup/code/coleta_dados_matches.ipynb
  bases/world_fifa_women_world_cup/code/desktop.ini
  bases/world_fifa_women_world_cup/code/tratamento_dados_matches-checkpoint.ipynb
  bases/world_fifa_women_world_cup/dataset_config.yaml
  bases/world_fifa_women_world_cup/matches/publish.sql
  bases/world_fifa_women_world_cup/matches/schema-prod.json
  bases/world_fifa_women_world_cup/matches/schema-staging.json
  bases/world_fifa_women_world_cup/matches/table_config.yaml
  bases/world_fifa_women_world_cup/matches/table_description.txt
Labels: data

#1330 [dados] br_bcb_sicor
  bases/br_bcb_sicor/README.md
  bases/br_bcb_sicor/dataset_config.yaml
  bases/br_bcb_sicor/dicionario/publish.sql
  bases/br_bcb_sicor/dicionario/schema-prod.json
  bases/br_bcb_sicor/dicionario/schema-staging.json
  bases/br_bcb_sicor/dicionario/table_config.yaml
  bases/br_bcb_sicor/dicionario/table_description.txt
  bases/br_bcb_sicor/empreendimento/publish.sql
  bases/br_bcb_sicor/empreendimento/schema-prod.json
  bases/br_bcb_sicor/empreendimento/schema-staging.json
  bases/br_bcb_sicor/empreendimento/table_config.yaml
  bases/br_bcb_sicor/empreendimento/table_description.txt
  bases/br_bcb_sicor/microdados_liberacao/publish.sql
  bases/br_bcb_sicor/microdados_liberacao/schema-prod.json
  bases/br_bcb_sicor/microdados_liberacao/schema-staging.json
  bases/br_bcb_sicor/microdados_liberacao/table_config.yaml
  bases/br_bcb_sicor/microdados_liberacao/table_description.txt
  bases/br_bcb_sicor/microdados_operacao/publish.sql
  bases/br_bcb_sicor/microdados_operacao/schema-prod.json
  bases/br_bcb_sicor/microdados_operacao/schema-staging.json
  bases/br_bcb_sicor/microdados_operacao/table_config.yaml
  bases/br_bcb_sicor/microdados_operacao/table_description.txt
  bases/br_bcb_sicor/microdados_saldo/publish.sql
  bases/br_bcb_sicor/microdados_saldo/schema-prod.json
  bases/br_bcb_sicor/microdados_saldo/schema-staging.json
  bases/br_bcb_sicor/microdados_saldo/table_config.yaml
  bases/br_bcb_sicor/microdados_saldo/table_description.txt
Labels: data

#1350 [dados] br_cgu_ebt
  bases/br_cgu_ebt/README.md
  bases/br_cgu_ebt/dataset_config.yaml
  bases/br_cgu_ebt/municipio/publish.sql
  bases/br_cgu_ebt/municipio/schema-prod.json
  bases/br_cgu_ebt/municipio/schema-staging.json
  bases/br_cgu_ebt/municipio/table_config.yaml
  bases/br_cgu_ebt/municipio/table_description.txt
  bases/br_cgu_ebt/uf/publish.sql
  bases/br_cgu_ebt/uf/schema-prod.json
  bases/br_cgu_ebt/uf/schema-staging.json
  bases/br_cgu_ebt/uf/table_config.yaml
  bases/br_cgu_ebt/uf/table_description.txt
Labels: data

#1355 [dados] Receitas Esperadas
  bases/br_bd_indicadores/receitas_planejadas/publish.sql
  bases/br_bd_indicadores/receitas_planejadas/schema-prod.json
  bases/br_bd_indicadores/receitas_planejadas/schema-staging.json
  bases/br_bd_indicadores/receitas_planejadas/table_config.yaml
  bases/br_bd_indicadores/receitas_planejadas/table_description.txt
Labels: data

#1348 [dados] `br_me_cnpj`
  bases/br_me_cnpj/code/build.do
  bases/br_me_cnpj/dataset_config.yaml
  bases/br_me_cnpj/dicionario/publish.sql
  bases/br_me_cnpj/dicionario/schema-prod.json
  bases/br_me_cnpj/dicionario/schema-staging.json
  bases/br_me_cnpj/dicionario/table_config.yaml
  bases/br_me_cnpj/dicionario/table_description.txt
  bases/br_me_cnpj/empresas/publish.sql
  bases/br_me_cnpj/empresas/schema-prod.json
  bases/br_me_cnpj/empresas/schema-staging.json
  bases/br_me_cnpj/empresas/table_config.yaml
  bases/br_me_cnpj/empresas/table_description.txt
  bases/br_me_cnpj/estabelecimentos/publish.sql
  bases/br_me_cnpj/estabelecimentos/schema-prod.json
  bases/br_me_cnpj/estabelecimentos/schema-staging.json
  bases/br_me_cnpj/estabelecimentos/table_config.yaml
  bases/br_me_cnpj/estabelecimentos/table_description.txt
  bases/br_me_cnpj/simples/publish.sql
  bases/br_me_cnpj/simples/schema-prod.json
  bases/br_me_cnpj/simples/schema-staging.json
  bases/br_me_cnpj/simples/table_config.yaml
  bases/br_me_cnpj/simples/table_description.txt
  bases/br_me_cnpj/socios/publish.sql
  bases/br_me_cnpj/socios/schema-prod.json
  bases/br_me_cnpj/socios/schema-staging.json
  bases/br_me_cnpj/socios/table_config.yaml
  bases/br_me_cnpj/socios/table_description.txt
Labels: data

#1365 [dados] br_camara_atividade_legislativa.evento
  bases/br_camara_atividade_legislativa/code/clean_data.py
  bases/br_camara_atividade_legislativa/code/download_data.py
  bases/br_camara_atividade_legislativa/dicionario/publish.sql
  bases/br_camara_atividade_legislativa/dicionario/schema-prod.json
  bases/br_camara_atividade_legislativa/dicionario/schema-staging.json
  bases/br_camara_atividade_legislativa/dicionario/table_config.yaml
  bases/br_camara_atividade_legislativa/dicionario/table_description.txt
  bases/br_camara_atividade_legislativa/evento/publish.sql
  bases/br_camara_atividade_legislativa/evento/schema-prod.json
  bases/br_camara_atividade_legislativa/evento/schema-staging.json
  bases/br_camara_atividade_legislativa/evento/table_config.yaml
  bases/br_camara_atividade_legislativa/evento/table_description.txt
Labels: data

#1328 [doc] doc_r_update
  docs/api_reference_r.md
Labels: docs, R

#1380 br_inep_sinopse_estatistica_educacao_basica
  bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
  bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
Labels: data

#1382 [docs] README.md adapted for the use of multiple accounts
  README.md
Labels: docs

#1387 [dados-update] br_inpe_prodes
  bases/br_inpe_prodes/desmatamento_municipio/publish.sql
Labels: data-update

#1383 [docs] docs_dev_r_package
  r-package/README.md
Labels: docs, R

#1388 update style data
  docs/style_data.md
Labels: docs

#1391 [dados - atualização] br_camara_atividade_legislativa.evento
  bases/br_camara_atividade_legislativa/evento/table_config.yaml
Labels: data, data-update, volunteer

#1392 Update table_config.yaml
  bases/br_camara_atividade_legislativa/evento/table_config.yaml
Labels: data, data-update

#1393 [dados-atualizacao] br_camara_atividade_legislativa
  bases/br_camara_atividade_legislativa/dicionario/table_config.yaml
Labels: data, data-update

#1390 br_inep_sinopse_estatistica_educacao_basica.dicionario
  bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
Labels: data

#1376 [dados]br_siorg_cargos.remuneracao
  bases/br_siorg_cargos/README.md
  bases/br_siorg_cargos/dataset_config.yaml
  bases/br_siorg_cargos/remuneracao/publish.sql
  bases/br_siorg_cargos/remuneracao/schema-prod.json
  bases/br_siorg_cargos/remuneracao/schema-staging.json
  bases/br_siorg_cargos/remuneracao/table_config.yaml
  bases/br_siorg_cargos/remuneracao/table_description.txt
Labels: data

#1378 [dados]br_ibge_populacao.brasil
  bases/br_ibge_populacao/brasil/publish.sql
  bases/br_ibge_populacao/brasil/schema-prod.json
  bases/br_ibge_populacao/brasil/schema-staging.json
  bases/br_ibge_populacao/brasil/table_config.yaml
  bases/br_ibge_populacao/brasil/table_description.txt
  bases/br_ibge_populacao/uf/publish.sql
  bases/br_ibge_populacao/uf/schema-prod.json
  bases/br_ibge_populacao/uf/schema-staging.json
  bases/br_ibge_populacao/uf/table_config.yaml
  bases/br_ibge_populacao/uf/table_description.txt
Labels: data
