Repository basedosdados/sdk, pull requests merged in 2022-02, with the labels that each got.

#1097 [dados] `br_inep_censo_escolar.matricula`
  bases/br_inep_censo_escolar/code/antigo/ajuda-arq.R
  bases/br_inep_censo_escolar/code/antigo/codigo_docente/docente-2015a17.do
  bases/br_inep_censo_escolar/code/antigo/codigo_docente/docentes-2009-2014.do
  bases/br_inep_censo_escolar/code/antigo/codigo_matricula/anos_recentes.do
  bases/br_inep_censo_escolar/code/antigo/codigo_matricula/antigas_matriculas.do
  bases/br_inep_censo_escolar/code/antigo/codigo_matricula/caso_2018.do
  bases/br_inep_censo_escolar/code/antigo/codigo_matricula/corrigindo_ultimosanos.do
  bases/br_inep_censo_escolar/code/antigo/codigo_turma/turmas-antigo.do
  bases/br_inep_censo_escolar/code/antigo/codigo_turma/turmas-finais.do
  bases/br_inep_censo_escolar/code/antigo/codigo_turma/turmas-intermediario.do
  bases/br_inep_censo_escolar/code/build.do
  bases/br_inep_censo_escolar/dataset_config.yaml
  bases/br_inep_censo_escolar/matricula/publish.sql
  bases/br_inep_censo_escolar/matricula/schema-prod.json
  bases/br_inep_censo_escolar/matricula/schema-staging.json
  bases/br_inep_censo_escolar/matricula/table_config.yaml
  bases/br_inep_censo_escolar/matricula/table_description.txt
Labels: data

#1102 [dados-qualidade] br_bd_diretorios_brasil.municipio
  bases/br_bd_diretorios_brasil/municipio/publish.sql
  bases/br_bd_diretorios_brasil/municipio/schema-prod.json
  bases/br_bd_diretorios_brasil/municipio/schema-staging.json
  bases/br_bd_diretorios_brasil/municipio/table_config.yaml
  bases/br_bd_diretorios_brasil/municipio/table_description.txt
Labels: data, data-quality

#1020 [infra] option to make dataset public
  python-package/basedosdados/configs/templates/table/table_description.txt
  python-package/basedosdados/upload/dataset.py
  python-package/basedosdados/upload/storage.py
  python-package/pyproject.toml
Labels: bug, enhancement, infra

#1114 [infra] Testa table-approve com os novos metadados
  .github/workflows/data-check.yml
  .github/workflows/metadata-validate.yml
  .github/workflows/table-approve.yml
  bases/test_dataset/dataset_config.yaml
  bases/test_dataset/test_table/publish.sql
  bases/test_dataset/test_table/schema-prod.json
  bases/test_dataset/test_table/schema-staging.json
  bases/test_dataset/test_table/table_config.yaml
  bases/test_dataset/test_table/table_description.txt
Labels: data-check-trigger, meta-check

#1120 `br_bd_diretorios_mundo.continente`
  bases/br_bd_diretorios_mundo/continente/publish.sql
  bases/br_bd_diretorios_mundo/continente/schema-prod.json
  bases/br_bd_diretorios_mundo/continente/schema-staging.json
  bases/br_bd_diretorios_mundo/continente/table_config.yaml
  bases/br_bd_diretorios_mundo/continente/table_description.txt
Labels: data, data-check-trigger

#1123 feat: update br_bd_diretorios_mundo.pais
  bases/br_bd_diretorios_mundo/pais/publish.sql
  bases/br_bd_diretorios_mundo/pais/schema-prod.json
  bases/br_bd_diretorios_mundo/pais/schema-staging.json
  bases/br_bd_diretorios_mundo/pais/table_config.yaml
  bases/br_bd_diretorios_mundo/pais/table_description.txt
Labels: data, data-check-trigger

#1127 [dados-qualidade] br_sp_saopaulo_dieese_icv
  bases/br_sp_saopaulo_dieese_icv/ano/publish.sql
  bases/br_sp_saopaulo_dieese_icv/ano/schema-prod.json
  bases/br_sp_saopaulo_dieese_icv/ano/schema-staging.json
  bases/br_sp_saopaulo_dieese_icv/ano/table_config.yaml
  bases/br_sp_saopaulo_dieese_icv/ano/table_description.txt
  bases/br_sp_saopaulo_dieese_icv/code/br_sp_saopaulo_dieese_icv.py
  bases/br_sp_saopaulo_dieese_icv/dataset_config.yaml
  bases/br_sp_saopaulo_dieese_icv/mes/publish.sql
  bases/br_sp_saopaulo_dieese_icv/mes/schema-prod.json
  bases/br_sp_saopaulo_dieese_icv/mes/schema-staging.json
  bases/br_sp_saopaulo_dieese_icv/mes/table_config.yaml
  bases/br_sp_saopaulo_dieese_icv/mes/table_description.txt
Labels: data, data-quality

#1132 [dados-qualidade] br_ibge_pnad
  bases/br_ibge_pnad/code/br_ibge_pnad.py
  bases/br_ibge_pnad/dataset_config.yaml
  bases/br_ibge_pnad/dicionario/schema-prod.json
  bases/br_ibge_pnad/dicionario/schema-staging.json
  bases/br_ibge_pnad/dicionario/table_config.yaml
  bases/br_ibge_pnad/dicionario/table_description.txt
  bases/br_ibge_pnad/microdados_compatibilizado_datazoom/schema-prod.json
  bases/br_ibge_pnad/microdados_compatibilizado_datazoom/schema-staging.json
  bases/br_ibge_pnad/microdados_compatibilizados_datazoom/publish.sql
  bases/br_ibge_pnad/microdados_compatibilizados_datazoom/schema-prod.json
  bases/br_ibge_pnad/microdados_compatibilizados_datazoom/schema-staging.json
  bases/br_ibge_pnad/microdados_compatibilizados_datazoom/table_config.yaml
  bases/br_ibge_pnad/microdados_compatibilizados_datazoom/table_description.txt
Labels: data, data-quality

#1128 [dados-qualidade] br_inep_censo_escolar.dicionario
  bases/br_inep_censo_escolar/dicionario/publish.sql
  bases/br_inep_censo_escolar/dicionario/schema-prod.json
  bases/br_inep_censo_escolar/dicionario/schema-staging.json
  bases/br_inep_censo_escolar/dicionario/table_config.yaml
  bases/br_inep_censo_escolar/dicionario/table_description.txt
Labels: data, data-quality
