Repository basedosdados/sdk, pull requests merged in 2022-11, with the labels that each got.

#1397 [dados] br_me_siape.servidores_executivo_federal
  bases/br_me_siape/README.md
  bases/br_me_siape/code/siape.ipynb
  bases/br_me_siape/dataset_config.yaml
  bases/br_me_siape/servidores_executivo_federal/publish.sql
  bases/br_me_siape/servidores_executivo_federal/schema-prod.json
  bases/br_me_siape/servidores_executivo_federal/schema-staging.json
  bases/br_me_siape/servidores_executivo_federal/table_config.yaml
  bases/br_me_siape/servidores_executivo_federal/table_description.txt
Labels: data

#1369 [dados] Feat/br cgu servidores remuneracao
  bases/br_cgu_servidores_executivo_federal/code_/__init__.py
  bases/br_cgu_servidores_executivo_federal/code_/functions.py
  bases/br_cgu_servidores_executivo_federal/code_/main.py
  bases/br_cgu_servidores_executivo_federal/code_/processing_functions.py
  bases/br_cgu_servidores_executivo_federal/code_/requirements.txt
  bases/br_cgu_servidores_executivo_federal/code_/settings.py
  bases/br_cgu_servidores_executivo_federal/code_/test_cgu.py
  bases/br_cgu_servidores_executivo_federal/dataset_config.yaml
  bases/br_cgu_servidores_executivo_federal/extra/architecture/remuneracao_ativo.csv
  bases/br_cgu_servidores_executivo_federal/extra/architecture/remuneracao_inativo.csv
  bases/br_cgu_servidores_executivo_federal/extra/architecture/servidor_civil_aposentado_remuneracao.csv
  bases/br_cgu_servidores_executivo_federal/extra/architecture/servidor_civil_ativo_remuneracao.csv
  bases/br_cgu_servidores_executivo_federal/extra/architecture/servidor_militar_ativo_remuneracao.csv
  bases/br_cgu_servidores_executivo_federal/extra/architecture/servidor_militar_reservista_remuneracao.csv
  bases/br_cgu_servidores_executivo_federal/remuneracao_ativo/publish.sql
  bases/br_cgu_servidores_executivo_federal/remuneracao_ativo/schema-prod.json
  bases/br_cgu_servidores_executivo_federal/remuneracao_ativo/schema-staging.json
  bases/br_cgu_servidores_executivo_federal/remuneracao_ativo/table_config.yaml
  bases/br_cgu_servidores_executivo_federal/remuneracao_ativo/table_description.txt
  bases/br_cgu_servidores_executivo_federal/remuneracao_inativo/publish.sql
  bases/br_cgu_servidores_executivo_federal/remuneracao_inativo/schema-prod.json
  bases/br_cgu_servidores_executivo_federal/remuneracao_inativo/schema-staging.json
  bases/br_cgu_servidores_executivo_federal/remuneracao_inativo/table_config.yaml
  bases/br_cgu_servidores_executivo_federal/remuneracao_inativo/table_description.txt
Labels: data

#1407 [dados] fix: changes source of 2006 party-municipality data
  bases/br_me_cnpj/code/build.do
  bases/br_tse_eleicoes/code/sub/agregacao.do
  bases/br_tse_eleicoes/code/sub/resultados_municipio_zona.do
  bases/br_tse_eleicoes/resultados_partido_municipio_zona/table_config.yaml
Labels: data

#1410 [infra] changing minimal pandas to ^1.3.5, returning loguru as dependency and…
  python-package/poetry.lock
  python-package/pyproject.toml
  python-package/requirements-dev.txt
Labels: bug

#1377 [dados] world_fifa_worldcup
  bases/world_fifa_worldcup/award_winners/publish.sql
  bases/world_fifa_worldcup/award_winners/schema-prod.json
  bases/world_fifa_worldcup/award_winners/schema-staging.json
  bases/world_fifa_worldcup/award_winners/table_config.yaml
  bases/world_fifa_worldcup/award_winners/table_description.txt
  bases/world_fifa_worldcup/dataset_config.yaml
  bases/world_fifa_worldcup/matches/publish.sql
  bases/world_fifa_worldcup/matches/schema-prod.json
  bases/world_fifa_worldcup/matches/schema-staging.json
  bases/world_fifa_worldcup/matches/table_config.yaml
  bases/world_fifa_worldcup/matches/table_description.txt
  bases/world_fifa_worldcup/players/publish.sql
  bases/world_fifa_worldcup/players/schema-prod.json
  bases/world_fifa_worldcup/players/schema-staging.json
  bases/world_fifa_worldcup/players/table_config.yaml
  bases/world_fifa_worldcup/players/table_description.txt
  bases/world_fifa_worldcup/teams/publish.sql
  bases/world_fifa_worldcup/teams/schema-prod.json
  bases/world_fifa_worldcup/teams/schema-staging.json
  bases/world_fifa_worldcup/teams/table_config.yaml
  bases/world_fifa_worldcup/teams/table_description.txt
  bases/world_fifa_worldcup/tournaments/publish.sql
  bases/world_fifa_worldcup/tournaments/schema-prod.json
  bases/world_fifa_worldcup/tournaments/schema-staging.json
  bases/world_fifa_worldcup/tournaments/table_config.yaml
  bases/world_fifa_worldcup/tournaments/table_description.txt
Labels: data

#1416 [dados-atualização] eu_fra_lgbt
  bases/eu_fra_lgbt/consciencia_direitos/table_config.yaml
  bases/eu_fra_lgbt/cotidiano/table_config.yaml
  bases/eu_fra_lgbt/dataset_config.yaml
  bases/eu_fra_lgbt/discriminacao/table_config.yaml
  bases/eu_fra_lgbt/especifico_transgenero/table_config.yaml
  bases/eu_fra_lgbt/violencia_abuso/table_config.yaml
Labels: data, metadata

#1414 [dados] Eleições - prestação de contas
  bases/br_tse_eleicoes/bens_candidato/schema-prod.json
  bases/br_tse_eleicoes/bens_candidato/schema-staging.json
  bases/br_tse_eleicoes/bens_candidato/table_config.yaml
  bases/br_tse_eleicoes/bens_candidato/table_description.txt
  bases/br_tse_eleicoes/code/sub/normalizacao_particao.do
  bases/br_tse_eleicoes/code/sub/prestacao_contas.do
  bases/br_tse_eleicoes/despesas_candidato/schema-prod.json
  bases/br_tse_eleicoes/despesas_candidato/schema-staging.json
  bases/br_tse_eleicoes/despesas_candidato/table_config.yaml
  bases/br_tse_eleicoes/despesas_candidato/table_description.txt
  bases/br_tse_eleicoes/receitas_candidato/schema-prod.json
  bases/br_tse_eleicoes/receitas_candidato/schema-staging.json
  bases/br_tse_eleicoes/receitas_candidato/table_config.yaml
  bases/br_tse_eleicoes/receitas_candidato/table_description.txt
Labels: data

#1423 Fix elections president
  bases/br_tse_eleicoes/code/sub/prestacao_contas.do
Labels: data

#1420 [dados-atualização] eu_fra_lgbt
  bases/eu_fra_lgbt/README.md
  bases/eu_fra_lgbt/consciencia_direitos/publish.sql
  bases/eu_fra_lgbt/consciencia_direitos/schema-prod.json
  bases/eu_fra_lgbt/consciencia_direitos/schema-staging.json
  bases/eu_fra_lgbt/consciencia_direitos/table_description.txt
  bases/eu_fra_lgbt/cotidiano/publish.sql
  bases/eu_fra_lgbt/cotidiano/schema-prod.json
  bases/eu_fra_lgbt/cotidiano/schema-staging.json
  bases/eu_fra_lgbt/cotidiano/table_description.txt
  bases/eu_fra_lgbt/discriminacao/publish.sql
  bases/eu_fra_lgbt/discriminacao/schema-prod.json
  bases/eu_fra_lgbt/discriminacao/schema-staging.json
  bases/eu_fra_lgbt/discriminacao/table_description.txt
  bases/eu_fra_lgbt/especifico_transgenero/publish.sql
  bases/eu_fra_lgbt/especifico_transgenero/schema-prod.json
  bases/eu_fra_lgbt/especifico_transgenero/schema-staging.json
  bases/eu_fra_lgbt/especifico_transgenero/table_description.txt
  bases/eu_fra_lgbt/violencia_abuso/publish.sql
  bases/eu_fra_lgbt/violencia_abuso/schema-prod.json
  bases/eu_fra_lgbt/violencia_abuso/schema-staging.json
  bases/eu_fra_lgbt/violencia_abuso/table_description.txt
Labels: data, metadata

#1431 [dados-atualizacao] update table_config `br_me_pensionistas.microdados`
  bases/br_me_pensionistas/microdados/table_config.yaml
Labels: data

#1448 Update table-approve.yml
  .github/workflows/table-approve.yml
Labels: table-approve

#1454 Atualizar documentação: Metadados de dicionário e diretórios
  docs/style_data.md
Labels: docs

#1455 [dados-atualziacao ] fix metadata`br_isp_estatisticas_seguranca.taxa_evolucao_mensal_municipio`
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/table_config.yaml
Labels: metadata

#1456 [dados] br_me_siorg
  bases/br_me_siorg/README.md
  bases/br_me_siorg/dataset_config.yaml
  bases/br_me_siorg/remuneracao/publish.sql
  bases/br_me_siorg/remuneracao/schema-prod.json
  bases/br_me_siorg/remuneracao/schema-staging.json
  bases/br_me_siorg/remuneracao/table_config.yaml
  bases/br_me_siorg/remuneracao/table_description.txt
Labels: data

#1458 [dados-atualizacao] fix metadata `br_mobilidados_indicadores.comprometimento_renda_tarifa_transp_publico`
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
Labels: metadata, data-quality

#1459 [dados-atualizacao] fix metadata br_mobilidados_indicadores.comprometimento_renda_tarifa_transp_publico
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/publish.sql
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/schema-prod.json
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/schema-staging.json
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_description.txt
Labels: metadata, data-quality

#1427 [dados] `br-cgu-fef`
  bases/br_cgu_fef/README.md
  bases/br_cgu_fef/code/build.do
  bases/br_cgu_fef/dataset_config.yaml
  bases/br_cgu_fef/microdados/publish.sql
  bases/br_cgu_fef/microdados/schema-prod.json
  bases/br_cgu_fef/microdados/schema-staging.json
  bases/br_cgu_fef/microdados/table_config.yaml
  bases/br_cgu_fef/microdados/table_description.txt
Labels: data
