Repository basedosdados/sdk, pull requests merged in 2022-08, with the labels that each got.

#1208 [dados-atualizacao] br_ms_sinasc
  bases/br_ms_sinasc/code/[dados]br_ms_sinasc_2020.ipynb
  bases/br_ms_sinasc/dataset_config.yaml
  bases/br_ms_sinasc/dicionario/publish.sql
  bases/br_ms_sinasc/dicionario/schema-prod.json
  bases/br_ms_sinasc/dicionario/schema-staging.json
  bases/br_ms_sinasc/dicionario/table_config.yaml
  bases/br_ms_sinasc/dicionario/table_description.txt
  bases/br_ms_sinasc/microdados/publish.sql
  bases/br_ms_sinasc/microdados/schema-prod.json
  bases/br_ms_sinasc/microdados/schema-staging.json
  bases/br_ms_sinasc/microdados/table_config.yaml
  bases/br_ms_sinasc/microdados/table_description.txt
Labels: data, data-update

#1273 [dados] `br_mma_extincao`
  bases/br_mma_extincao/README.md
  bases/br_mma_extincao/dataset_config.yaml
  bases/br_mma_extincao/fauna_ameacada/publish.sql
  bases/br_mma_extincao/fauna_ameacada/schema-prod.json
  bases/br_mma_extincao/fauna_ameacada/schema-staging.json
  bases/br_mma_extincao/fauna_ameacada/table_config.yaml
  bases/br_mma_extincao/fauna_ameacada/table_description.txt
  bases/br_mma_extincao/flora_ameacada/publish.sql
  bases/br_mma_extincao/flora_ameacada/schema-prod.json
  bases/br_mma_extincao/flora_ameacada/schema-staging.json
  bases/br_mma_extincao/flora_ameacada/table_config.yaml
  bases/br_mma_extincao/flora_ameacada/table_description.txt
Labels: data

#1278 [dados] br_geobr_mapas.microrregiao
  bases/br_geobr_mapas/code/microrregioes.py
  bases/br_geobr_mapas/microrregiao/publish.sql
  bases/br_geobr_mapas/microrregiao/schema-prod.json
  bases/br_geobr_mapas/microrregiao/schema-staging.json
  bases/br_geobr_mapas/microrregiao/table_config.yaml
  bases/br_geobr_mapas/microrregiao/table_description.txt
Labels: data

#1280 [dados] br_geobr_mapas.uf
  bases/br_geobr_mapas/code/uf.ipynb
  bases/br_geobr_mapas/uf/publish.sql
  bases/br_geobr_mapas/uf/schema-prod.json
  bases/br_geobr_mapas/uf/schema-staging.json
  bases/br_geobr_mapas/uf/table_config.yaml
  bases/br_geobr_mapas/uf/table_description.txt
Labels: data

#1286 Colab authentication
  python-package/basedosdados/download/base.py
  python-package/pyproject.toml
Labels: conflict

#1288 authentication with colab or PyData
  python-package/basedosdados/download/base.py
  python-package/pyproject.toml
Labels: conflict

#1289 Colab authentication
  python-package/basedosdados/download/base.py
Labels: conflict

#1300 [dados atualizacao] br_bd_indicadores
  bases/br_bd_indicadores/equipes/publish.sql
  bases/br_bd_indicadores/equipes/schema-prod.json
  bases/br_bd_indicadores/equipes/schema-staging.json
  bases/br_bd_indicadores/equipes/table_config.yaml
Labels: data-update

#1285 [dados] br_geobr_mapas.regiao
  bases/br_geobr_mapas/code/microrregioes.py
  bases/br_geobr_mapas/code/regiao.ipynb
  bases/br_geobr_mapas/regiao/publish.sql
  bases/br_geobr_mapas/regiao/schema-prod.json
  bases/br_geobr_mapas/regiao/schema-staging.json
  bases/br_geobr_mapas/regiao/table_config.yaml
  bases/br_geobr_mapas/regiao/table_description.txt
Labels: data

#1304 [dados] br_bd_diretorios_brasil.area_conhecimento
  bases/br_bd_diretorios_brasil/area_conhecimento/publish.sql
  bases/br_bd_diretorios_brasil/area_conhecimento/schema-prod.json
  bases/br_bd_diretorios_brasil/area_conhecimento/schema-staging.json
  bases/br_bd_diretorios_brasil/area_conhecimento/table_config.yaml
  bases/br_bd_diretorios_brasil/area_conhecimento/table_description.txt
  bases/br_bd_diretorios_brasil/code/[dados] br_bd_diretorios_brasil_area_conhecimento.py
Labels: data
