Repository basedosdados/sdk, pull requests merged in 2022-09, with the labels that each got.

#1290 [dados] br_inep_sinopse_estatistica_educacao_basica.municipio_matricula_localizacao_rede
  bases/br_inep_sinopse_estatistica_educacao_basica/README.md
  bases/br_inep_sinopse_estatistica_educacao_basica/code/br_inep_sinopse_educacao_basica.py
  bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
  bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/publish.sql
  bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/schema-prod.json
  bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/schema-staging.json
  bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
  bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_description.txt
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/publish.sql
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/schema-prod.json
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/schema-staging.json
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/table_config.yaml
  bases/br_inep_sinopse_estatistica_educacao_basica/matricula/table_description.txt
  bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/publish.sql
  bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/schema-prod.json
  bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/schema-staging.json
  bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
  bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_description.txt
Labels: data

#1293 [dados-atualizacao] `br_bd_diretorios_brasil.etnia_indigena`
  bases/br_bd_diretorios_brasil/etnia_indigena/publish.sql
  bases/br_bd_diretorios_brasil/etnia_indigena/schema-prod.json
  bases/br_bd_diretorios_brasil/etnia_indigena/schema-staging.json
  bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
  bases/br_bd_diretorios_brasil/etnia_indigena/table_description.txt
Labels: data

#1325 [dados] update_doc_r
  docs/api_reference_r.md
Labels: docs

#1322 [dados] br_fgv_igp
  bases/br_fgv_igp/dataset_config.yaml
  bases/br_fgv_igp/igp_10_mes/publish.sql
  bases/br_fgv_igp/igp_10_mes/schema-prod.json
  bases/br_fgv_igp/igp_10_mes/schema-staging.json
  bases/br_fgv_igp/igp_10_mes/table_config.yaml
  bases/br_fgv_igp/igp_10_mes/table_description.txt
  bases/br_fgv_igp/igp_di_ano/publish.sql
  bases/br_fgv_igp/igp_di_ano/schema-prod.json
  bases/br_fgv_igp/igp_di_ano/schema-staging.json
  bases/br_fgv_igp/igp_di_ano/table_config.yaml
  bases/br_fgv_igp/igp_di_ano/table_description.txt
  bases/br_fgv_igp/igp_di_mes/publish.sql
  bases/br_fgv_igp/igp_di_mes/schema-prod.json
  bases/br_fgv_igp/igp_di_mes/schema-staging.json
  bases/br_fgv_igp/igp_di_mes/table_config.yaml
  bases/br_fgv_igp/igp_di_mes/table_description.txt
  bases/br_fgv_igp/igp_m_ano/publish.sql
  bases/br_fgv_igp/igp_m_ano/schema-prod.json
  bases/br_fgv_igp/igp_m_ano/schema-staging.json
  bases/br_fgv_igp/igp_m_ano/table_config.yaml
  bases/br_fgv_igp/igp_m_ano/table_description.txt
  bases/br_fgv_igp/igp_m_mes/publish.sql
  bases/br_fgv_igp/igp_m_mes/schema-prod.json
  bases/br_fgv_igp/igp_m_mes/schema-staging.json
  bases/br_fgv_igp/igp_m_mes/table_config.yaml
  bases/br_fgv_igp/igp_m_mes/table_description.txt
  bases/br_fgv_igp/igp_og_ano/publish.sql
  bases/br_fgv_igp/igp_og_ano/schema-prod.json
  bases/br_fgv_igp/igp_og_ano/schema-staging.json
  bases/br_fgv_igp/igp_og_ano/table_config.yaml
  bases/br_fgv_igp/igp_og_ano/table_description.txt
  bases/br_fgv_igp/igp_og_mes/publish.sql
  bases/br_fgv_igp/igp_og_mes/schema-prod.json
  bases/br_fgv_igp/igp_og_mes/schema-staging.json
  bases/br_fgv_igp/igp_og_mes/table_config.yaml
  bases/br_fgv_igp/igp_og_mes/table_description.txt
Labels: data

#1312 [dados] br_mec_prouni.microdados
  bases/br_mec_prouni/README.md
  bases/br_mec_prouni/code/2020fix.ipynb
  bases/br_mec_prouni/code/br_mec_prouni.bolsas.ipynb
  bases/br_mec_prouni/dataset_config.yaml
  bases/br_mec_prouni/dicionario/publish.sql
  bases/br_mec_prouni/dicionario/schema-prod.json
  bases/br_mec_prouni/dicionario/schema-staging.json
  bases/br_mec_prouni/dicionario/table_config.yaml
  bases/br_mec_prouni/dicionario/table_description.txt
  bases/br_mec_prouni/microdados/publish.sql
  bases/br_mec_prouni/microdados/schema-prod.json
  bases/br_mec_prouni/microdados/schema-staging.json
  bases/br_mec_prouni/microdados/table_config.yaml
  bases/br_mec_prouni/microdados/table_description.txt
Labels: data, volunteer

#1303 [dados] br_geobr_mapas.regiao_imediata
  bases/br_geobr_mapas/code/regiao_imediata.py
  bases/br_geobr_mapas/regiao_imediata/publish.sql
  bases/br_geobr_mapas/regiao_imediata/schema-prod.json
  bases/br_geobr_mapas/regiao_imediata/schema-staging.json
  bases/br_geobr_mapas/regiao_imediata/table_config.yaml
  bases/br_geobr_mapas/regiao_imediata/table_description.txt
Labels: data

#1306 [dados] br_geobr_mapas.regiao_intermediaria
  bases/br_geobr_mapas/code/regiao_intermediaria.py
  bases/br_geobr_mapas/regiao_intermediaria/publish.sql
  bases/br_geobr_mapas/regiao_intermediaria/schema-prod.json
  bases/br_geobr_mapas/regiao_intermediaria/schema-staging.json
  bases/br_geobr_mapas/regiao_intermediaria/table_config.yaml
  bases/br_geobr_mapas/regiao_intermediaria/table_description.txt
Labels: data

#1335 [dados] br_geobr_mapas.estabelecimentos_saude
  bases/br_geobr_mapas/code/estabelecimentos_saude.ipynb
  bases/br_geobr_mapas/estabelecimentos_saude/publish.sql
  bases/br_geobr_mapas/estabelecimentos_saude/schema-prod.json
  bases/br_geobr_mapas/estabelecimentos_saude/schema-staging.json
  bases/br_geobr_mapas/estabelecimentos_saude/table_config.yaml
  bases/br_geobr_mapas/estabelecimentos_saude/table_description.txt
Labels: data

#1336 [dados-atualizacao] br_geobr_mapas.estabelecimentos_saude
  bases/br_geobr_mapas/code/estabelecimentos_saude.ipynb
  bases/br_geobr_mapas/estabelecimentos_saude/schema-prod.json
  bases/br_geobr_mapas/estabelecimentos_saude/schema-staging.json
  bases/br_geobr_mapas/estabelecimentos_saude/table_config.yaml
Labels: data, data-update

#1339 [infra] removing parameter job_config_params from cli
  python-package/basedosdados/cli/cli.py
Labels: bug
