Repository basedosdados/sdk, pull requests merged in 2023-02, with the labels that each got.

#1536 [dados] world_fao_production
  bases/world_fao_production/README.md
  bases/world_fao_production/code/world_fao.R
  bases/world_fao_production/country_group/publish.sql
  bases/world_fao_production/country_group/schema-prod.json
  bases/world_fao_production/country_group/schema-staging.json
  bases/world_fao_production/country_group/table_config.yaml
  bases/world_fao_production/country_group/table_description.txt
  bases/world_fao_production/crop_livestock/publish.sql
  bases/world_fao_production/crop_livestock/schema-prod.json
  bases/world_fao_production/crop_livestock/schema-staging.json
  bases/world_fao_production/crop_livestock/table_config.yaml
  bases/world_fao_production/crop_livestock/table_description.txt
  bases/world_fao_production/dataset_config.yaml
  bases/world_fao_production/dictionary/publish.sql
  bases/world_fao_production/dictionary/schema-prod.json
  bases/world_fao_production/dictionary/schema-staging.json
  bases/world_fao_production/dictionary/table_config.yaml
  bases/world_fao_production/dictionary/table_description.txt
  bases/world_fao_production/element/publish.sql
  bases/world_fao_production/element/schema-prod.json
  bases/world_fao_production/element/schema-staging.json
  bases/world_fao_production/element/table_config.yaml
  bases/world_fao_production/element/table_description.txt
  bases/world_fao_production/item/publish.sql
  bases/world_fao_production/item/schema-prod.json
  bases/world_fao_production/item/schema-staging.json
  bases/world_fao_production/item/table_config.yaml
  bases/world_fao_production/item/table_description.txt
  bases/world_fao_production/item_group/publish.sql
  bases/world_fao_production/item_group/schema-prod.json
  bases/world_fao_production/item_group/schema-staging.json
  bases/world_fao_production/item_group/table_config.yaml
  bases/world_fao_production/item_group/table_description.txt
  bases/world_fao_production/production_indices/publish.sql
  bases/world_fao_production/production_indices/schema-prod.json
  bases/world_fao_production/production_indices/schema-staging.json
  bases/world_fao_production/production_indices/table_config.yaml
  bases/world_fao_production/production_indices/table_description.txt
  bases/world_fao_production/value_agricultural_production/publish.sql
  bases/world_fao_production/value_agricultural_production/schema-prod.json
  bases/world_fao_production/value_agricultural_production/schema-staging.json
  bases/world_fao_production/value_agricultural_production/table_config.yaml
  bases/world_fao_production/value_agricultural_production/table_description.txt
Labels: data

#1538 [dados] world_wb_wwbi.country_finance
  bases/world_wb_wwbi/code/country_finance.ipynb
  bases/world_wb_wwbi/code/data.ipynb
  bases/world_wb_wwbi/country_finance/publish.sql
  bases/world_wb_wwbi/country_finance/schema-prod.json
  bases/world_wb_wwbi/country_finance/schema-staging.json
  bases/world_wb_wwbi/country_finance/table_config.yaml
  bases/world_wb_wwbi/country_finance/table_description.txt
Labels: data

#1559 [dados-atualizacao] update pib municipio
  bases/br_ibge_pib/municipio/publish.sql
  bases/br_ibge_pib/municipio/schema-prod.json
  bases/br_ibge_pib/municipio/schema-staging.json
  bases/br_ibge_pib/municipio/table_config.yaml
  bases/br_ibge_pib/municipio/table_description.txt
Labels: data-update

#1560 [dados] br_ibge_estadic
  bases/br_ibge_estadic/comunicacao_informatica/schema-prod.json
  bases/br_ibge_estadic/comunicacao_informatica/schema-staging.json
  bases/br_ibge_estadic/comunicacao_informatica/table_config.yaml
  bases/br_ibge_estadic/comunicacao_informatica/table_description.txt
  bases/br_ibge_estadic/politica_mulher/publish.sql
  bases/br_ibge_estadic/politica_mulher/schema-prod.json
  bases/br_ibge_estadic/politica_mulher/schema-staging.json
  bases/br_ibge_estadic/politica_mulher/table_config.yaml
  bases/br_ibge_estadic/politica_mulher/table_description.txt
Labels: data-quality

#1534 [dados] br_ibge_munic
  bases/br_ibge_munic/README.md
  bases/br_ibge_munic/code/perfil_gestor/perfil.ipynb
  bases/br_ibge_munic/code/quantidade_vinculo/quantidade_vinculo.ipynb
  bases/br_ibge_munic/dataset_config.yaml
  bases/br_ibge_munic/indicadores_perfil_gestor/publish.sql
  bases/br_ibge_munic/indicadores_perfil_gestor/schema-prod.json
  bases/br_ibge_munic/indicadores_perfil_gestor/schema-staging.json
  bases/br_ibge_munic/indicadores_perfil_gestor/table_config.yaml
  bases/br_ibge_munic/indicadores_perfil_gestor/table_description.txt
  bases/br_ibge_munic/indicadores_quantidade_vinculo/publish.sql
  bases/br_ibge_munic/indicadores_quantidade_vinculo/schema-prod.json
  bases/br_ibge_munic/indicadores_quantidade_vinculo/schema-staging.json
  bases/br_ibge_munic/indicadores_quantidade_vinculo/table_config.yaml
  bases/br_ibge_munic/indicadores_quantidade_vinculo/table_description.txt
Labels: data

#1546 [dados] br_me_siconfi.uf
  bases/br_me_siconfi/uf_despesas_funcao/publish.sql
  bases/br_me_siconfi/uf_despesas_funcao/schema-prod.json
  bases/br_me_siconfi/uf_despesas_funcao/schema-staging.json
  bases/br_me_siconfi/uf_despesas_funcao/table_config.yaml
  bases/br_me_siconfi/uf_despesas_funcao/table_description.txt
  bases/br_me_siconfi/uf_despesas_orcamentarias/publish.sql
  bases/br_me_siconfi/uf_despesas_orcamentarias/schema-prod.json
  bases/br_me_siconfi/uf_despesas_orcamentarias/schema-staging.json
  bases/br_me_siconfi/uf_despesas_orcamentarias/table_config.yaml
  bases/br_me_siconfi/uf_despesas_orcamentarias/table_description.txt
  bases/br_me_siconfi/uf_receitas_orcamentarias/publish.sql
  bases/br_me_siconfi/uf_receitas_orcamentarias/schema-prod.json
  bases/br_me_siconfi/uf_receitas_orcamentarias/schema-staging.json
  bases/br_me_siconfi/uf_receitas_orcamentarias/table_config.yaml
  bases/br_me_siconfi/uf_receitas_orcamentarias/table_description.txt
Labels: data

#1561 [dados] br_bcb_estban
  bases/br_bcb_estban/README.md
  bases/br_bcb_estban/agencia/publish.sql
  bases/br_bcb_estban/agencia/schema-prod.json
  bases/br_bcb_estban/agencia/schema-staging.json
  bases/br_bcb_estban/agencia/table_config.yaml
  bases/br_bcb_estban/agencia/table_description.txt
  bases/br_bcb_estban/code/br_bcb_estban_agencia.ipynb
  bases/br_bcb_estban/code/br_bcb_estban_dicionario.ipynb
  bases/br_bcb_estban/code/br_bcb_estban_municipio.ipynb
  bases/br_bcb_estban/dicionario/publish.sql
  bases/br_bcb_estban/dicionario/schema-prod.json
  bases/br_bcb_estban/dicionario/schema-staging.json
  bases/br_bcb_estban/dicionario/table_config.yaml
  bases/br_bcb_estban/dicionario/table_description.txt
  bases/br_bcb_estban/municipio/publish.sql
  bases/br_bcb_estban/municipio/schema-prod.json
  bases/br_bcb_estban/municipio/schema-staging.json
  bases/br_bcb_estban/municipio/table_config.yaml
  bases/br_bcb_estban/municipio/table_description.txt
Labels: data

#1567 [dados-atualizacao] br_me_rais.dicionario
  bases/br_me_rais/dicionario/schema-prod.json
  bases/br_me_rais/dicionario/schema-staging.json
  bases/br_me_rais/dicionario/table_config.yaml
  bases/br_me_rais/dicionario/table_description.txt
Labels: data-update

#1570 [dados-atualizacao] update `br_sgp_informacao.despesas_cartao_corporativo`
  bases/br_sgp_informacao/despesas_cartao_corporativo/publish.sql
  bases/br_sgp_informacao/despesas_cartao_corporativo/schema-prod.json
  bases/br_sgp_informacao/despesas_cartao_corporativo/schema-staging.json
  bases/br_sgp_informacao/despesas_cartao_corporativo/table_config.yaml
  bases/br_sgp_informacao/despesas_cartao_corporativo/table_description.txt
Labels: data-update

#1555 [dados] world_spi
  bases/world_spi/README.md
  bases/world_spi/code/word_spi.ipynb
  bases/world_spi/dataset_config.yaml
  bases/world_spi/global_indicators/publish.sql
  bases/world_spi/global_indicators/schema-prod.json
  bases/world_spi/global_indicators/schema-staging.json
  bases/world_spi/global_indicators/table_config.yaml
  bases/world_spi/global_indicators/table_description.txt
Labels: data

#1566 [dados-atualizacao] br_inep_indicadores_educacionais
  bases/br_inep_indicadores_educacionais/brasil/publish.sql
  bases/br_inep_indicadores_educacionais/brasil/schema-prod.json
  bases/br_inep_indicadores_educacionais/brasil/schema-staging.json
  bases/br_inep_indicadores_educacionais/brasil/table_config.yaml
  bases/br_inep_indicadores_educacionais/brasil/table_description.txt
  bases/br_inep_indicadores_educacionais/code/[dados_atualizacao]_br_inep_indicadores_educacionais.ipynb
  bases/br_inep_indicadores_educacionais/escola/publish.sql
  bases/br_inep_indicadores_educacionais/escola/schema-prod.json
  bases/br_inep_indicadores_educacionais/escola/schema-staging.json
  bases/br_inep_indicadores_educacionais/escola/table_config.yaml
  bases/br_inep_indicadores_educacionais/escola/table_description.txt
  bases/br_inep_indicadores_educacionais/municipio/publish.sql
  bases/br_inep_indicadores_educacionais/municipio/schema-prod.json
  bases/br_inep_indicadores_educacionais/municipio/schema-staging.json
  bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
  bases/br_inep_indicadores_educacionais/municipio/table_description.txt
  bases/br_inep_indicadores_educacionais/regiao/publish.sql
  bases/br_inep_indicadores_educacionais/regiao/schema-prod.json
  bases/br_inep_indicadores_educacionais/regiao/schema-staging.json
  bases/br_inep_indicadores_educacionais/regiao/table_config.yaml
  bases/br_inep_indicadores_educacionais/regiao/table_description.txt
  bases/br_inep_indicadores_educacionais/uf/publish.sql
  bases/br_inep_indicadores_educacionais/uf/schema-prod.json
  bases/br_inep_indicadores_educacionais/uf/schema-staging.json
  bases/br_inep_indicadores_educacionais/uf/table_config.yaml
  bases/br_inep_indicadores_educacionais/uf/table_description.txt
Labels: data, data-update

#1579 Corrige erros de valores nulos no dataset microdados_movimentacao do …
  bases/br_me_caged/microdados_movimentacao/publish.sql
  bases/br_me_caged/microdados_movimentacao/schema-prod.json
  bases/br_me_caged/microdados_movimentacao/table_config.yaml
Labels: data

#1580 [dados-fix]br_inep_indicadores_educacionais.uf
  bases/br_inep_indicadores_educacionais/uf/table_config.yaml
Labels: data
