Repository basedosdados/sdk, pull requests merged in 2023-03, with the labels that each got.

#1367 [dados-atualizacao] br_inep_ideb
  bases/br_inep_ideb/brasil/publish.sql
  bases/br_inep_ideb/brasil/schema-prod.json
  bases/br_inep_ideb/brasil/schema-staging.json
  bases/br_inep_ideb/brasil/table_config.yaml
  bases/br_inep_ideb/brasil/table_description.txt
  bases/br_inep_ideb/escola/publish.sql
  bases/br_inep_ideb/escola/schema-prod.json
  bases/br_inep_ideb/escola/schema-staging.json
  bases/br_inep_ideb/escola/table_config.yaml
  bases/br_inep_ideb/escola/table_description.txt
  bases/br_inep_ideb/municipio/publish.sql
  bases/br_inep_ideb/municipio/schema-prod.json
  bases/br_inep_ideb/municipio/schema-staging.json
  bases/br_inep_ideb/municipio/table_config.yaml
  bases/br_inep_ideb/municipio/table_description.txt
  bases/br_inep_ideb/regiao/publish.sql
  bases/br_inep_ideb/regiao/schema-prod.json
  bases/br_inep_ideb/regiao/schema-staging.json
  bases/br_inep_ideb/regiao/table_config.yaml
  bases/br_inep_ideb/regiao/table_description.txt
  bases/br_inep_ideb/uf/publish.sql
  bases/br_inep_ideb/uf/schema-prod.json
  bases/br_inep_ideb/uf/schema-staging.json
  bases/br_inep_ideb/uf/table_config.yaml
  bases/br_inep_ideb/uf/table_description.txt
Labels: data, data-update

#1587 [dados-atualizacao] update censo escolar 2022
  bases/br_inep_censo_escolar/escola/publish.sql
  bases/br_inep_censo_escolar/escola/schema-prod.json
  bases/br_inep_censo_escolar/escola/schema-staging.json
  bases/br_inep_censo_escolar/escola/table_config.yaml
  bases/br_inep_censo_escolar/escola/table_description.txt
Labels: data-update

#1577 [dados] world_slave_voyage_slave_trade
  bases/world_slave_voyages_consortium_slave_trade/README.md
  bases/world_slave_voyages_consortium_slave_trade/code/world_slave_voyage_slave_trade.ipynb
  bases/world_slave_voyages_consortium_slave_trade/transatlantic/publish.sql
  bases/world_slave_voyages_consortium_slave_trade/transatlantic/schema-prod.json
  bases/world_slave_voyages_consortium_slave_trade/transatlantic/schema-staging.json
  bases/world_slave_voyages_consortium_slave_trade/transatlantic/table_config.yaml
  bases/world_slave_voyages_consortium_slave_trade/transatlantic/table_description.txt
Labels: data

#1462 [dados] br_fbsp_absp
  bases/br_fbsp_absp/municipio/code/br_fbsp_absp.ipynb
  bases/br_fbsp_absp/municipio/publish.sql
  bases/br_fbsp_absp/municipio/schema-prod.json
  bases/br_fbsp_absp/municipio/schema-staging.json
  bases/br_fbsp_absp/municipio/table_config.yaml
  bases/br_fbsp_absp/municipio/table_description.txt
Labels: data

#1586 [dados] br_ieps_saude
  bases/br_ieps_saude/brasil/publish.sql
  bases/br_ieps_saude/brasil/schema-prod.json
  bases/br_ieps_saude/brasil/schema-staging.json
  bases/br_ieps_saude/brasil/table_config.yaml
  bases/br_ieps_saude/brasil/table_description.txt
  bases/br_ieps_saude/code/code.py
  bases/br_ieps_saude/dataset_config.yaml
  bases/br_ieps_saude/macrorregiao/publish.sql
  bases/br_ieps_saude/macrorregiao/schema-prod.json
  bases/br_ieps_saude/macrorregiao/schema-staging.json
  bases/br_ieps_saude/macrorregiao/table_config.yaml
  bases/br_ieps_saude/macrorregiao/table_description.txt
  bases/br_ieps_saude/municipio/publish.sql
  bases/br_ieps_saude/municipio/schema-prod.json
  bases/br_ieps_saude/municipio/schema-staging.json
  bases/br_ieps_saude/municipio/table_config.yaml
  bases/br_ieps_saude/municipio/table_description.txt
  bases/br_ieps_saude/regiao_saude/publish.sql
  bases/br_ieps_saude/regiao_saude/schema-prod.json
  bases/br_ieps_saude/regiao_saude/schema-staging.json
  bases/br_ieps_saude/regiao_saude/table_config.yaml
  bases/br_ieps_saude/regiao_saude/table_description.txt
  bases/br_ieps_saude/uf/publish.sql
  bases/br_ieps_saude/uf/schema-prod.json
  bases/br_ieps_saude/uf/schema-staging.json
  bases/br_ieps_saude/uf/table_config.yaml
  bases/br_ieps_saude/uf/table_description.txt
Labels: data

#1589 [dados-atualizacao] br_inep.saeb
  bases/br_inep_saeb/brasil/publish.sql
  bases/br_inep_saeb/brasil/table_config.yaml
  bases/br_inep_saeb/brasil/table_description.txt
  bases/br_inep_saeb/dataset_config.yml
  bases/br_inep_saeb/municipio/table_config.yaml
  bases/br_inep_saeb/municipio/table_description.txt
  bases/br_inep_saeb/uf/publish.sql
  bases/br_inep_saeb/uf/table_config.yaml
  bases/br_inep_saeb/uf/table_description.txt
Labels: data-update

#1340 [dados] metadata
  bases/br_bd_metadados/columns/publish.sql
  bases/br_bd_metadados/columns/schema-prod.json
  bases/br_bd_metadados/columns/schema-staging.json
  bases/br_bd_metadados/columns/table_config.yaml
  bases/br_bd_metadados/columns/table_description.txt
  bases/br_bd_metadados/dataset_config.yaml
  bases/br_bd_metadados/datasets/publish.sql
  bases/br_bd_metadados/datasets/schema-prod.json
  bases/br_bd_metadados/datasets/schema-staging.json
  bases/br_bd_metadados/datasets/table_config.yaml
  bases/br_bd_metadados/datasets/table_description.txt
  bases/br_bd_metadados/external_links/publish.sql
  bases/br_bd_metadados/external_links/schema-prod.json
  bases/br_bd_metadados/external_links/schema-staging.json
  bases/br_bd_metadados/external_links/table_config.yaml
  bases/br_bd_metadados/external_links/table_description.txt
  bases/br_bd_metadados/information_requests/publish.sql
  bases/br_bd_metadados/information_requests/schema-prod.json
  bases/br_bd_metadados/information_requests/schema-staging.json
  bases/br_bd_metadados/information_requests/table_config.yaml
  bases/br_bd_metadados/information_requests/table_description.txt
  bases/br_bd_metadados/organizations/publish.sql
  bases/br_bd_metadados/organizations/schema-prod.json
  bases/br_bd_metadados/organizations/schema-staging.json
  bases/br_bd_metadados/organizations/table_config.yaml
  bases/br_bd_metadados/organizations/table_description.txt
  bases/br_bd_metadados/resources/publish.sql
  bases/br_bd_metadados/resources/schema-prod.json
  bases/br_bd_metadados/resources/schema-staging.json
  bases/br_bd_metadados/resources/table_config.yaml
  bases/br_bd_metadados/resources/table_description.txt
  bases/br_bd_metadados/tables/publish.sql
  bases/br_bd_metadados/tables/schema-prod.json
  bases/br_bd_metadados/tables/schema-staging.json
  bases/br_bd_metadados/tables/table_config.yaml
  bases/br_bd_metadados/tables/table_description.txt
Labels: data

#1594 [dados-atualizacao]br_inep_saeb
  bases/br_inep_saeb/brasil/table_config.yaml
  bases/br_inep_saeb/code/br_inep_saeb_brasil.ipynb
  bases/br_inep_saeb/code/br_inep_saeb_municipios.ipynb
  bases/br_inep_saeb/code/br_inep_uf.ipynb
  bases/br_inep_saeb/municipio/table_config.yaml
  bases/br_inep_saeb/uf/table_config.yaml
Labels: data-update
