Repository basedosdados/sdk, pull requests merged in 2023-04, with the labels that each got.

#1606 fix: corrige id_municipio_bcb em br_bd_diretorios_brasil.municipio
  bases/br_bd_diretorios_brasil/code/fix_municipio.py
  bases/br_bd_diretorios_brasil/municipio/publish.sql
  bases/br_bd_diretorios_brasil/municipio/schema-prod.json
  bases/br_bd_diretorios_brasil/municipio/schema-staging.json
  bases/br_bd_diretorios_brasil/municipio/table_config.yaml
  bases/br_bd_diretorios_brasil/municipio/table_description.txt
Labels: data-update

#1588 [dados-atualizacao] br_ms_cnes.estabelecimentos
  bases/br_ms_cnes/code/br_ms_cnes_estabelecimento.py
  bases/br_ms_cnes/dicionario/publish.sql
  bases/br_ms_cnes/dicionario/schema-prod.json
  bases/br_ms_cnes/dicionario/schema-staging.json
  bases/br_ms_cnes/dicionario/table_config.yaml
  bases/br_ms_cnes/dicionario/table_description.txt
  bases/br_ms_cnes/estabelecimento/publish.sql
  bases/br_ms_cnes/estabelecimento/schema-prod.json
  bases/br_ms_cnes/estabelecimento/schema-staging.json
  bases/br_ms_cnes/estabelecimento/table_config.yaml
  bases/br_ms_cnes/estabelecimento/table_description.txt
Labels: data-update

#1613 [dados] br_bd_diretorios_brasil.cep
  bases/br_bd_diretorios_brasil/cep/publish.sql
  bases/br_bd_diretorios_brasil/cep/schema-prod.json
  bases/br_bd_diretorios_brasil/cep/schema-staging.json
  bases/br_bd_diretorios_brasil/cep/table_config.yaml
  bases/br_bd_diretorios_brasil/cep/table_description.txt
  bases/br_bd_diretorios_brasil/code/cep.ipynb
Labels: data

#1624 [dados] `br_cgu_fef`
  bases/br_cgu_fef/municipios_sorteados/publish.sql
  bases/br_cgu_fef/municipios_sorteados/schema-prod.json
  bases/br_cgu_fef/municipios_sorteados/schema-staging.json
  bases/br_cgu_fef/municipios_sorteados/table_config.yaml
  bases/br_cgu_fef/municipios_sorteados/table_description.txt
  bases/br_cgu_fef/sorteio/publish.sql
  bases/br_cgu_fef/sorteio/schema-prod.json
  bases/br_cgu_fef/sorteio/schema-staging.json
  bases/br_cgu_fef/sorteio/table_config.yaml
  bases/br_cgu_fef/sorteio/table_description.txt
Labels: data

#1625 [dados] fix for 2022 2nd round
  bases/br_tse_eleicoes/code/sub/agregacao.do
  bases/br_tse_eleicoes/code/sub/detalhes_votacao_municipio_zona.do
  bases/br_tse_eleicoes/code/sub/detalhes_votacao_secao.do
Labels: data

#1634 [metadata]: fixing `br_me_caged` metadata
  bases/br_me_caged/microdados_movimentacao/publish.sql
  bases/br_me_caged/microdados_movimentacao/table_config.yaml
  bases/br_me_caged/microdados_movimentacao_excluida/publish.sql
  bases/br_me_caged/microdados_movimentacao_excluida/table_config.yaml
  bases/br_me_caged/microdados_movimentacao_fora_prazo/publish.sql
  bases/br_me_caged/microdados_movimentacao_fora_prazo/table_config.yaml
Labels: metadata

#1641 [dados] br_mdr_snis
  bases/br_mdr_snis/code/snis.ipynb
  bases/br_mdr_snis/code/upload_snis.ipynb
  bases/br_mdr_snis/code/utils.py
  bases/br_mdr_snis/dataset_config.yaml
  bases/br_mdr_snis/municipio_agua_esgoto/publish.sql
  bases/br_mdr_snis/municipio_agua_esgoto/schema-prod.json
  bases/br_mdr_snis/municipio_agua_esgoto/schema-staging.json
  bases/br_mdr_snis/municipio_agua_esgoto/table_config.yaml
  bases/br_mdr_snis/municipio_agua_esgoto/table_description.txt
  bases/br_mdr_snis/prestador_agua_esgoto/publish.sql
  bases/br_mdr_snis/prestador_agua_esgoto/schema-prod.json
  bases/br_mdr_snis/prestador_agua_esgoto/schema-staging.json
  bases/br_mdr_snis/prestador_agua_esgoto/table_config.yaml
  bases/br_mdr_snis/prestador_agua_esgoto/table_description.txt
Labels: data

#1258 [dados] `world_oecd_pisa.student`
  bases/world_oecd_pisa/README.md
  bases/world_oecd_pisa/code/student.ipynb
  bases/world_oecd_pisa/code/summary.R
  bases/world_oecd_pisa/dictionary/publish.sql
  bases/world_oecd_pisa/dictionary/schema-prod.json
  bases/world_oecd_pisa/dictionary/schema-staging.json
  bases/world_oecd_pisa/dictionary/table_config.yaml
  bases/world_oecd_pisa/dictionary/table_description.txt
  bases/world_oecd_pisa/school_summary/publish.sql
  bases/world_oecd_pisa/school_summary/schema-prod.json
  bases/world_oecd_pisa/school_summary/schema-staging.json
  bases/world_oecd_pisa/school_summary/table_config.yaml
  bases/world_oecd_pisa/school_summary/table_description.txt
  bases/world_oecd_pisa/student/publish.sql
  bases/world_oecd_pisa/student/schema-prod.json
  bases/world_oecd_pisa/student/schema-staging.json
  bases/world_oecd_pisa/student/table_config.yaml
  bases/world_oecd_pisa/student/table_description.txt
  bases/world_oecd_pisa/student_summary/publish.sql
  bases/world_oecd_pisa/student_summary/schema-prod.json
  bases/world_oecd_pisa/student_summary/schema-staging.json
  bases/world_oecd_pisa/student_summary/table_config.yaml
  bases/world_oecd_pisa/student_summary/table_description.txt
Labels: data
