Repository basedosdados/sdk, pull requests merged in 2023-01, with the labels that each got.

#1499 [dados] `br_me_cnpj`
  bases/br_me_cnpj/code/build.do
  bases/br_me_cnpj/empresas/publish.sql
  bases/br_me_cnpj/empresas/schema-prod.json
  bases/br_me_cnpj/empresas/table_config.yaml
  bases/br_me_cnpj/empresas/table_description.txt
  bases/br_me_cnpj/estabelecimentos/publish.sql
  bases/br_me_cnpj/estabelecimentos/schema-prod.json
  bases/br_me_cnpj/estabelecimentos/schema-staging.json
  bases/br_me_cnpj/estabelecimentos/table_config.yaml
  bases/br_me_cnpj/estabelecimentos/table_description.txt
  bases/br_me_cnpj/simples/table_config.yaml
  bases/br_me_cnpj/simples/table_description.txt
  bases/br_me_cnpj/socios/publish.sql
  bases/br_me_cnpj/socios/schema-prod.json
  bases/br_me_cnpj/socios/schema-staging.json
  bases/br_me_cnpj/socios/table_config.yaml
  bases/br_me_cnpj/socios/table_description.txt
Labels: data

#1460 [dados] world_ti_corruption_perception
  bases/world_ti_corruption_perception/README.md
  bases/world_ti_corruption_perception/code/code.py
  bases/world_ti_corruption_perception/country/publish.sql
  bases/world_ti_corruption_perception/country/schema-staging.json
  bases/world_ti_corruption_perception/country/table_config.yaml
Labels: data

#1468 [dados] br_ibge_estadic
  bases/br_ibge_estadic/README.md
  bases/br_ibge_estadic/comunicacao_informatica/publish.sql
  bases/br_ibge_estadic/comunicacao_informatica/schema-prod.json
  bases/br_ibge_estadic/comunicacao_informatica/schema-staging.json
  bases/br_ibge_estadic/comunicacao_informatica/table_config.yaml
  bases/br_ibge_estadic/comunicacao_informatica/table_description.txt
  bases/br_ibge_estadic/dataset_config.yaml
  bases/br_ibge_estadic/dicionario/publish.sql
  bases/br_ibge_estadic/dicionario/schema-prod.json
  bases/br_ibge_estadic/dicionario/schema-staging.json
  bases/br_ibge_estadic/dicionario/table_config.yaml
  bases/br_ibge_estadic/dicionario/table_description.txt
  bases/br_ibge_estadic/governanca/publish.sql
  bases/br_ibge_estadic/governanca/schema-prod.json
  bases/br_ibge_estadic/governanca/schema-staging.json
  bases/br_ibge_estadic/governanca/table_config.yaml
  bases/br_ibge_estadic/governanca/table_description.txt
  bases/br_ibge_estadic/politica_mulher/publish.sql
  bases/br_ibge_estadic/politica_mulher/schema-prod.json
  bases/br_ibge_estadic/politica_mulher/schema-staging.json
  bases/br_ibge_estadic/politica_mulher/table_config.yaml
  bases/br_ibge_estadic/politica_mulher/table_description.txt
  bases/br_ibge_estadic/recursos_humanos/publish.sql
  bases/br_ibge_estadic/recursos_humanos/schema-prod.json
  bases/br_ibge_estadic/recursos_humanos/schema-staging.json
  bases/br_ibge_estadic/recursos_humanos/table_config.yaml
  bases/br_ibge_estadic/recursos_humanos/table_description.txt
Labels: data

#1500 [dados] br_me_siconfi
  bases/br_me_siconfi/capital_ranking_qualidade/publish.sql
  bases/br_me_siconfi/capital_ranking_qualidade/schema-prod.json
  bases/br_me_siconfi/capital_ranking_qualidade/schema-staging.json
  bases/br_me_siconfi/capital_ranking_qualidade/table_config.yaml
  bases/br_me_siconfi/capital_ranking_qualidade/table_description.txt
  bases/br_me_siconfi/code/me_siconfi_ranking.R
  bases/br_me_siconfi/municipio_ranking_qualidade/publish.sql
  bases/br_me_siconfi/municipio_ranking_qualidade/schema-prod.json
  bases/br_me_siconfi/municipio_ranking_qualidade/schema-staging.json
  bases/br_me_siconfi/municipio_ranking_qualidade/table_config.yaml
  bases/br_me_siconfi/municipio_ranking_qualidade/table_description.txt
  bases/br_me_siconfi/uf_ranking_qualidade/publish.sql
  bases/br_me_siconfi/uf_ranking_qualidade/schema-prod.json
  bases/br_me_siconfi/uf_ranking_qualidade/schema-staging.json
  bases/br_me_siconfi/uf_ranking_qualidade/table_config.yaml
  bases/br_me_siconfi/uf_ranking_qualidade/table_description.txt
Labels: data

#1502 [dados] br_clp_ranking_competitividade
  bases/br_clp_ranking_competitividade/README.md
  bases/br_clp_ranking_competitividade/code/geral_municipios.ipynb
  bases/br_clp_ranking_competitividade/code/geral_uf.ipynb
  bases/br_clp_ranking_competitividade/dataset_config.yaml
  bases/br_clp_ranking_competitividade/nota_geral_municipio/publish.sql
  bases/br_clp_ranking_competitividade/nota_geral_municipio/schema-prod.json
  bases/br_clp_ranking_competitividade/nota_geral_municipio/schema-staging.json
  bases/br_clp_ranking_competitividade/nota_geral_municipio/table_config.yaml
  bases/br_clp_ranking_competitividade/nota_geral_municipio/table_description.txt
  bases/br_clp_ranking_competitividade/nota_geral_uf/publish.sql
  bases/br_clp_ranking_competitividade/nota_geral_uf/schema-prod.json
  bases/br_clp_ranking_competitividade/nota_geral_uf/schema-staging.json
  bases/br_clp_ranking_competitividade/nota_geral_uf/table_config.yaml
  bases/br_clp_ranking_competitividade/nota_geral_uf/table_description.txt
Labels: data

#1507 [dados] br_clp_ranking_competitividade
  bases/br_clp_ranking_competitividade/dataset_config.yaml
Labels: data

#1509 [dados] br_clp_ranking_competitividade
  bases/br_clp_ranking_competitividade/dataset_config.yaml
  bases/br_clp_ranking_competitividade/nota_geral_municipio/publish.sql
  bases/br_clp_ranking_competitividade/nota_geral_municipio/table_config.yaml
Labels: data

#1518 [dados] br_clp_ranking_competitividade.nota_geral_uf
  bases/br_clp_ranking_competitividade/dataset_config.yaml
  bases/br_clp_ranking_competitividade/nota_geral_uf/publish.sql
  bases/br_clp_ranking_competitividade/nota_geral_uf/table_config.yaml
Labels: data

#1503 [dados] br_rj_tce_iegm
  bases/br_rj_tce_iegm/README.md
  bases/br_rj_tce_iegm/code/microdados.ipynb
  bases/br_rj_tce_iegm/dataset_config.yaml
  bases/br_rj_tce_iegm/indicadores/publish.sql
  bases/br_rj_tce_iegm/indicadores/schema-prod.json
  bases/br_rj_tce_iegm/indicadores/schema-staging.json
  bases/br_rj_tce_iegm/indicadores/table_config.yaml
  bases/br_rj_tce_iegm/indicadores/table_description.txt
Labels: data

#1505 [dados-atualziacao ] fix `br_isp_estatisticas_seguranca.taxa_evolucao_mensal_municipio`
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/publish.sql
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/schema-prod.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/schema-staging.json
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/table_config.yaml
  bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/table_description.txt
Labels: data-update

#1508 [dados-atualizacao] fix metadata `br_mobilidados_indicadores.comprometimento_renda_tarifa_transp_publico`
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/publish.sql
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/schema-prod.json
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/schema-staging.json
  bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
Labels: metadata, data-update

#1506 [dados] world_wb_wwbi
  bases/world_wb_wwbi/README.md
  bases/world_wb_wwbi/code/data.ipynb
  bases/world_wb_wwbi/country_indicators/publish.sql
  bases/world_wb_wwbi/country_indicators/schema-prod.json
  bases/world_wb_wwbi/country_indicators/schema-staging.json
  bases/world_wb_wwbi/country_indicators/table_config.yaml
  bases/world_wb_wwbi/country_indicators/table_description.txt
  bases/world_wb_wwbi/dataset_config.yaml
Labels: data

#1522 [dados-atualizacao]br_me_siorg
  bases/br_me_siorg/remuneracao/table_config.yaml
Labels: data, data-update

#1523 [dados-atualizacao]br_me_siorg
  bases/br_me_siorg/remuneracao/schema-prod.json
  bases/br_me_siorg/remuneracao/schema-staging.json
  bases/br_me_siorg/remuneracao/table_config.yaml
Labels: data, data-update

#1526 [dados] sobe cartao corporativo
  bases/br_sgp_informacao/README.md
  bases/br_sgp_informacao/dataset_config.yaml
  bases/br_sgp_informacao/despesas_cartao_corporativo/publish.sql
  bases/br_sgp_informacao/despesas_cartao_corporativo/schema-prod.json
  bases/br_sgp_informacao/despesas_cartao_corporativo/schema-staging.json
  bases/br_sgp_informacao/despesas_cartao_corporativo/table_config.yaml
  bases/br_sgp_informacao/despesas_cartao_corporativo/table_description.txt
Labels: data

#1529 [dados-atualizacao] fix encoding `br_sgp_informacao.despesas_cartao_corporativo`
  bases/br_sgp_informacao/code/cartao_corporativo.R
  bases/br_sgp_informacao/despesas_cartao_corporativo/table_config.yaml
Labels: data-update

#1524 [dados-atualizacao] update `br_ibge_pib.municipio`
  bases/br_ibge_pib/dataset_config.yaml
  bases/br_ibge_pib/municipio/publish.sql
  bases/br_ibge_pib/municipio/schema-prod.json
  bases/br_ibge_pib/municipio/schema-staging.json
  bases/br_ibge_pib/municipio/table_config.yaml
  bases/br_ibge_pib/municipio/table_description.txt
Labels: data-update

#1527 [dados-atualizacao] br_inep_censo_escolar.dicionario
  bases/br_inep_censo_escolar/dicionario/table_config.yaml
Labels: bug, data-quality

#1545 [dados-fix] world_fifa_women_world_cup
  bases/world_fifa_women_world_cup/matches/table_config.yaml
Labels: data, data-update

#1551 [dados] br_ibge_pib.uf
  bases/br_ibge_pib/code/uf.ipynb
  bases/br_ibge_pib/uf/publish.sql
  bases/br_ibge_pib/uf/schema-prod.json
  bases/br_ibge_pib/uf/schema-staging.json
  bases/br_ibge_pib/uf/table_config.yaml
  bases/br_ibge_pib/uf/table_description.txt
Labels: data

#1535 [dados]br_ibge_estadic.indicadores
  bases/br_ibge_estadic/indicadores_perfil_gestor/publish.sql
  bases/br_ibge_estadic/indicadores_perfil_gestor/schema-prod.json
  bases/br_ibge_estadic/indicadores_perfil_gestor/schema-staging.json
  bases/br_ibge_estadic/indicadores_perfil_gestor/table_config.yaml
  bases/br_ibge_estadic/indicadores_perfil_gestor/table_description.txt
  bases/br_ibge_estadic/indicadores_quantidade_vinculo/publish.sql
  bases/br_ibge_estadic/indicadores_quantidade_vinculo/schema-prod.json
  bases/br_ibge_estadic/indicadores_quantidade_vinculo/schema-staging.json
  bases/br_ibge_estadic/indicadores_quantidade_vinculo/table_config.yaml
  bases/br_ibge_estadic/indicadores_quantidade_vinculo/table_description.txt
Labels: data

#1530 [dados] br_ipea_avs
  bases/br_ipea_avs/README.md
  bases/br_ipea_avs/code/br_ipea_avs.ipynb
  bases/br_ipea_avs/dataset_config.yaml
  bases/br_ipea_avs/municipio/publish.sql
  bases/br_ipea_avs/municipio/schema-prod.json
  bases/br_ipea_avs/municipio/schema-staging.json
  bases/br_ipea_avs/municipio/table_config.yaml
  bases/br_ipea_avs/municipio/table_description.txt
Labels: data

#1553 [dados] br_ibge_pib.uf
  bases/br_ibge_pib/uf/table_config.yaml
Labels: data

#1548 [dados] br_me_clima_organizacional
  bases/br_me_clima_organizacional/README.md
  bases/br_me_clima_organizacional/code/clima-organizacional.ipynb
  bases/br_me_clima_organizacional/dataset_config.yaml
  bases/br_me_clima_organizacional/microdados/publish.sql
  bases/br_me_clima_organizacional/microdados/schema-prod.json
  bases/br_me_clima_organizacional/microdados/schema-staging.json
  bases/br_me_clima_organizacional/microdados/table_config.yaml
  bases/br_me_clima_organizacional/microdados/table_description.txt
Labels: data

#1521 [dados] br_me_exportadoras_importadoras
  bases/br_me_exportadoras_importadoras/README.md
  bases/br_me_exportadoras_importadoras/code/br_empresas_exp_imp.ipynb
  bases/br_me_exportadoras_importadoras/dicionario/publish.sql
  bases/br_me_exportadoras_importadoras/dicionario/schema-prod.json
  bases/br_me_exportadoras_importadoras/dicionario/schema-staging.json
  bases/br_me_exportadoras_importadoras/dicionario/table_config.yaml
  bases/br_me_exportadoras_importadoras/dicionario/table_description.txt
  bases/br_me_exportadoras_importadoras/estabelecimentos/publish.sql
  bases/br_me_exportadoras_importadoras/estabelecimentos/schema-prod.json
  bases/br_me_exportadoras_importadoras/estabelecimentos/schema-staging.json
  bases/br_me_exportadoras_importadoras/estabelecimentos/table_config.yaml
  bases/br_me_exportadoras_importadoras/estabelecimentos/table_description.txt
Labels: data
